### ISSUE TITLE
A problem when using engine.Alias 

### ISSUE THREAD

**Issue by kyugao** [go-xorm/xorm#1005]
`engine.Table(entity.PatientInfoBasic{}).Alias("patient").
		Join("INNER", []string{entity.PatientOutOrder{}.TableName(), "preorder"}, "preorder.PATIID = patient.PATIID").
		Where("patient.PATIID = ?", patiId).Find(result)`

below attached the log. In the sql generated, seems missing the key word 'as' between table name and alias.
> [xorm] [info]  2018/06/15 12:07:41.986696 [SQL] SELECT * FROM "patient_info_basic" "patient" INNER JOIN "HRIP"."PATI_OUT_ORDER" AS "preorder" ON preorder.PATIID = patient.PATIID WHERE (patient.PATIID = :1) []interface {}{"0000ABIU"}
> 2018/06/15 12:07:42.014 [E] [outlet.preion.go:17] ORA-00905: missing keyword
>

**Comment by lunny** [comment]
Which database did you use?

**Comment by kyugao** [comment]
oracle

**Comment by kyugao** [comment]
I solve this problem by remove the keyword 'AS' in below function
`func (engine *Engine) tbNameNoSchema(tablename interface{}) string {
	switch tablename.(type) {
	case []string:
		t := tablename.([]string)
		if len(t) > 1 {
			return fmt.Sprintf("%v AS %v", engine.Quote(t[0]), engine.Quote(t[1]))
		} else if len(t) == 1 {
			return engine.Quote(t[0])
		}
	case []interface{}:
		t := tablename.([]interface{})
		l := len(t)
		var table string
		if l > 0 {
			f := t[0]
			switch f.(type) {
			case string:
				table = f.(string)
			case TableName:
				table = f.(TableName).TableName()
			default:
				v := rValue(f)
				t := v.Type()
				if t.Kind() == reflect.Struct {
					table = engine.tbNameForMap(v)
				} else {
					table = engine.Quote(fmt.Sprintf("%v", f))
				}
			}
		}
		if l > 1 {
			return fmt.Sprintf("%v AS %v", engine.Quote(table),
				engine.Quote(fmt.Sprintf("%v", t[1])))
		} else if l == 1 {
			return engine.Quote(table)
		}
	case TableName:
		return tablename.(TableName).TableName()
	case string:
		return tablename.(string)
	case reflect.Value:
		v := tablename.(reflect.Value)
		return engine.tbNameForMap(v)
	default:
		v := rValue(tablename)
		t := v.Type()
		if t.Kind() == reflect.Struct {
			return engine.tbNameForMap(v)
		}
		return engine.Quote(fmt.Sprintf("%v", tablename))
	}
	return ""
}`
