### ISSUE TITLE
How to convert key of type struct to lowercase

### ISSUE THREAD

**Issue by nosfantasy** [go-xorm/xorm#1007]
type User struct {
	Id			int			`xorm:"int pk autoincr 'id'"`
	Name 		string  	`xorm:"varchar(255) not null unique 'name'"`
	EMail		string		`xorm:"varchar(255) unique 'email'"`
	Password	string		`xorm:"varchar(255) not null 'password'"`
	CreatedAt 	time.Time	`xorm:"'created_at'"`
	UpdatedAt 	time.Time	`xorm:"'updated_at'"`
}

when i'm get user return data key is CamelCase

var user = User{Id:1}
	has, _ := orm.Get(&user)

"Id": 1,
"Name": "test",
"EMail": "test@mail.com",
"Password": "fewfewfefewfe",
"CreatedAt": "2018-06-17T16:41:52+07:00",
"UpdatedAt": "2018-06-17T16:41:52+07:00"

**Comment by lunny** [comment]
If you mean json format, please add json tags.

**Comment by nosfantasy** [comment]
@lunny thx for reply me 

type User struct {
        Id        int    `xorm:"autoincr pk" form:"id" json:"id"`
	Name      string `xorm:"varchar(255) not null" form:"name" json:"name"`
	Email     string `xorm:"varchar(255) unique not null" form:"email" json:"email"`
}

it work :)
