### ISSUE TITLE
Add support for pure-go SQL Database engine 'ql'

### ISSUE THREAD

**Issue by twitchyliquid64** [go-xorm/xorm#101]
It would be really awesome if we could get a pure-go SQL engine integrated with this. I have been watching 'ql' for this purpose for a while, and it is suitably mature for integration. Should follow most of the same semantics as sqlite and pq, as it uses the database/sql interface.

I have no worries writing the code for this either, if someone could explain generally what needs to be changed.

**Comment by lunny** [comment]
I will close this issue since we will suggest tidb support via github.com/go-xorm/tidb and will stop to ql's support.
