### ISSUE TITLE
插入时报错：cannot return value obtained from unexported field or method [recovered]

### ISSUE THREAD

**Issue by yujianFresh** [go-xorm/xorm#1021]
嗨，我用你们例子中的结构体创建表，并且插入都是正常的。

但是我自己定义的结构体，创建表是正常的，但是插入的时候就报了上面的这个异常，我的字段全是大写的，结构体如下：

type DbBlock struct {
	Id                      int64
	DelegateRoot            string    `xorm:"notnull"`
	ExtraData               string    `xorm:"notnull"`
	GasLimit                *big.Int  `xorm:"bigint notnull"`
	GasUsed                 *big.Int  `xorm:"bigint notnull"`
	Hash                    string    `xorm:"unique notnull"`
	Number                  *big.Int  `xorm:"bigint unique notnull"`
	ParentHash              string    `xorm:"notnull"`
	ReceiptsRoot            string    `xorm:"notnull"`
	ShuffleBlockNumber      *big.Int  `xorm:"bigint notnull"`
	ShuffleDelegateListHash string    `xorm:"notnull"`
	Size                    *big.Int  `xorm:"bigint notnull"`
	StateRoot               string    `xorm:"varchar(255) notnull"`
	Timestamp               time.Time `xorm:"notnull"`
	TransactionCount        int       `xorm:"notnull"`
	TransactionsRoot        string    `xorm:"notnull"`
	ValidatorName           string    `xorm:"notnull"`
	ValidatorAddress        string    `xorm:"varchar(64) notnull"`
}

还望遇到坑的多多指教。

**Comment by yujianFresh** [comment]
发现问题了，你们不支持big.int,换成string就可以了

**Comment by lunny** [comment]
*big.Int is not supported.
