### ISSUE TITLE
how i can implement scan from raw query select in xorm

### ISSUE THREAD

**Issue by youcandoit95** [go-xorm/xorm#1033]
hello please tell me how to implement scan from raw query select with parameter in xorm ?

like in gorm below

http://gorm.io/docs/query.html in scan section in the bottom

`type Result struct {
  Name string
  Age  int
}

var result Result
db.Table("users").Select("name, age").Where("name = ?", 3).Scan(&result)

// Raw SQL
db.Raw("SELECT name, age FROM users WHERE name = ?", 3).Scan(&result)
`

**Comment by lunny** [comment]
```Go
db.Table("users").Select("name, age").Where("name = ?", 3).Get(&result)
```

**Comment by lunny** [comment]
Get means get one record. If you want to get only one column, you even use the string to do that. i.e.
```Go
var name string
db.Table("users").Select("name").Where("name = ?", 3).Get(&name)
```

**Comment by youcandoit95** [comment]
hello @lunny 

but i want  to select with raw SQL query , can you tell me ?

**Comment by lunny** [comment]
```Go
var result Result
db.SQL("SELECT name, age FROM users WHERE name = ?", 3).Get(&result)

var results []Result
db.SQL("SELECT name, age FROM users").Find(&results)

var name string
db.SQL("SELECT name FROM users WHERE id = ?", 3).Get(&name)
```

**Comment by youcandoit95** [comment]
nicee.. it's work thanks
