### ISSUE TITLE
how to check database are connected or not before query ?

### ISSUE THREAD

**Issue by youcandoit95** [go-xorm/xorm#1034]
hello ,, can somebody tell me how to check database are connected or not before query ?

or how to check database connected or not in func init main.go ?

because i've already used this code but it's not running well , when i'd unplugged internet connection the error doesn't show up

here is my code

`

	engine, err = xorm.NewEngine("mysql", ""+os.Getenv("MYSQL_DATABASE_USER")+":"+os.Getenv("MYSQL_DATABASE_PASSWORD")+"@tcp("+os.Getenv("MYSQL_DATABASE_HOST")+":"+os.Getenv("MYSQL_DATABASE_PORT")+")/"+os.Getenv("MYSQL_DATABASE_DBNAME")+"?charset=utf8&parseTime=true")
	engine.SetMapper(core.GonicMapper{})

	if err != nil {
		log.Fatal("Error init database")
	}

`

**Comment by lunny** [comment]
```Go
err = engine.Ping()
```

**Comment by youcandoit95** [comment]
@lunny thanks lunny it's work in func init on main.go

but how i can handle this error

`
[mysql] 2018/07/06 12:57:01 packets.go:36: read tcp 192.168.1.130:50937->104.215.151.230:3333: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
`

it was happened if db connection lost immediately.. please help

**Comment by youcandoit95** [comment]
done,, solved with db.ping logic :)
