### ISSUE TITLE
xorm为什么不支持where通过传入结构体查询，只能定死字段

### ISSUE THREAD

**Issue by niosi** [go-xorm/xorm#1056]
想要查询单条数据，发现没法通过where传入结构体灵活查询。
get与exist可以查询单条数据，但却不支持条件查询。
find第二个参数可以达到目的，但是参数必须是个数组，如果想要单条数据就相对麻烦。xxx[0]如果没有没有数据则会抛出异常

**Comment by lunny** [comment]
文档看过了？

**Comment by niosi** [comment]
文档都看过了哦，方法源码也看了，查询方面只有find支持condiBeans方式来查询。
希望能把这个加到where方法上，以及让单条数据查询的方法get以及exist也能支持condiBeans查询

**Comment by lunny** [comment]
如果你说你看了，那就是你没仔细看
```Go
var obj =Object{
Id: 1,
}
engine.Get(&obj)
// Select * from table where id = 1
```

**Comment by niosi** [comment]
仍有问题，已提交新的issues, 并附例子
