### ISSUE TITLE
关于 extends join的使用问题....

### ISSUE THREAD

**Issue by SSRITW** [go-xorm/xorm#1062]
type User struct {
	Id             int64          `xorm:"pk"`
	Name       String
	Roles        []*UserRole `xorm:"extends"`
}

type UserRole  struct {
	RoleId       int64          `xorm:"pk"`
        UserId       int64 
}

user := &User{}
engine.Table("user").Join("LEFT", "user_role", "user_role.user_id = user.id").find(user)

我发现当我的extends字段是slice时,是不能正常使用的,没有得到数据;
如果是struct时,是可以正常拿到数据的;
目前xorm是不支持slice字段的extends吗?

**Comment by lunny** [comment]
It's not supported.
