### ISSUE TITLE
更新不成功

### ISSUE THREAD

**Issue by magicdvd** [go-xorm/xorm#1067]
以下操作 update 永远不成功， 依照例子写的。莫名其妙

``

    rows, err := mysqlClient.MustCols("namne").Update(&models.Account{
		Name: "Hello",
	  }, &models.Account{
		Id: 2,
	  })

	if err != nil {
		t.Error(err)
	}
	if rows == 0 {
		t.Errorf("error %d", rows)
	}
``

``

结构体如下：
    type Account struct {
	Id          int64  `xorm:"bigint pk autoincr"`
	Name        string `xorm:"unique"`
	Avatar      string `xorm:"varchar(255)"`
	Mobile      string `xorm:"char(20) unique"`
	Create      int    `xorm:"created"`
	NameChanged int    `xorm:"tinyint default(0)"`
	Update      int    `xorm:"updated"`
	Lastlogin   int64  `xorm:"bigint default(0)"`
	Version     int64  `xorm:"version"`
    }
``

**Comment by lunny** [comment]
namne -> name

**Comment by magicdvd** [comment]
手误，一样的结果

**Comment by magicdvd** [comment]
只有 exec 裸写sql才成。。。我有点闷逼

**Comment by magicdvd** [comment]
好了 我懂了。。。用了version 乐观锁。。

**Comment by magicdvd** [comment]
乐观锁 必须更新时候带上原来的version数值。。
