### ISSUE TITLE
Create a xorm.Engine from a current sql

### ISSUE THREAD

**Issue by happilymarrieddad** [go-xorm/xorm#1078]
Is there a way to use a `sql.Db` to create an engine for Xorm? I want to use `github.com/DATA-DOG/go-sqlmock` to mock tests for my API but there's no way to pass in a sql.Db as xorm.Engine that I know of unless I create an interface and map everything. I was hoping there was an easier way. Also, if something changes in Xorm, that would require me to change my interface. Thanks!

**Comment by happilymarrieddad** [comment]
I guess something like
```
engine,err := xorm.EngineFromDbSql(db)
```

**Comment by happilymarrieddad** [comment]
![selection_054](https://user-images.githubusercontent.com/6416323/44485803-11e8f480-a60f-11e8-9d8b-8ecd7897fafa.png)
![selection_055](https://user-images.githubusercontent.com/6416323/44485811-17463f00-a60f-11e8-9bb1-ea9a133d8b36.png)

```
cannot use db (type *sql.DB) as type *"github.com/fusionwarellc/api.fusionware.com/vendor/github.com/go-xorm/xorm".Engine in argument to Delete
db *DB
```

**Comment by happilymarrieddad** [comment]
in case this is useful, here is the definition for `assets`. I wrote a script that dynamically builds it from the database.

![selection_056](https://user-images.githubusercontent.com/6416323/44486058-ce42ba80-a60f-11e8-90ec-865857f847b0.png)

**Comment by xflxfl** [comment]
```go
db, mock, err := sqlmock.New()
if err != nil {
     ....
}
engine.DB().DB = db
```
@happilymarrieddad

**Comment by lunny** [comment]
@xflxfl that's right, just forgot that.

**Comment by happilymarrieddad** [comment]
@lunny oh man you've saved me SO much time!!! Thanks!!!!
