### ISSUE TITLE
Is OrderBy escaped?

### ISSUE THREAD

**Issue by happilymarrieddad** [go-xorm/xorm#1082]
is OrderBy escaped? If I pass in a value from a client-side app is it safe to do that? I want to open up the orderBy to API calls. Should I just parse it and  make sure it's one of a set of allowable values and if so then allow otherwise throw out?

**Comment by lunny** [comment]
@happilymarrieddad I think no. you should not expose that to your customer. You have to check if it should be one of your allowable values.
