### ISSUE TITLE
postgresql set schema

### ISSUE THREAD

**Issue by qianfangyuan** [go-xorm/xorm#1084]
PG10:
dbname:xmonitor
schema:monitor
tablename:heartbeat

code:
	const PostgreSQLMasterDSN="user=postgres password=xxxx host=xx port=xx dbname=xmonitor connect_timeout=10 application_name=backup sslmode=disable"

	eng1,err:=xorm.NewEngine("postgres", PostgreSQLMasterDSN)
	if err != nil{
		fmt.Println(err)
		return
	}

	eng1.SetSchema("monitor")
	if err != nil{
		fmt.Println(err)
		return
	}
	defer eng1.Close()
	results, err:=eng1.Query("select * from heartbeat limit 10;")
	//results, err:=eng1.Query("select * from monitor.heartbeat limit 10;")

	if err != nil{
		fmt.Println(err)
		return
	}

SQL:select * from heartbeat limit 10; get error:pq: relation "heartbeat" does not exist
SQL:select * from monitor.heartbeat limit 10;; get relation result

function setting Schema also needed query with schema.table ?

**Comment by lunny** [comment]
Yes. Once you set schema, currently you have to do that.

**Comment by lunny** [comment]
@qianfangyuan you can set that yourself. But since there are connection pool and `set search_path='xx'` is only available on current connection. It cannot work.

**Comment by qianfangyuan** [comment]
ok,thanks
