### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by lewesYang** [go-xorm/xorm#1088]
github.com/go-xorm/builder/builder.go:295: undefined: sql.NamedArg
github.com/go-xorm/builder/builder.go:307: undefined: sql.Named
github.com/go-xorm/builder/sql.go:110: undefined: sql.NamedArg

**Comment by BetaCat0** [comment]
sql.Named is available in go 1.8+ , maybe you can try to update your sdk to solve this problem

**Comment by BetaCat0** [comment]
@lewesYang Did this solve your problem, please let me know

**Comment by lewesYang** [comment]
thinks ,upgrade  go version to 1.11 is work

**Comment by lewesYang** [comment]
thinks,upgrade go version to 1.11 is work
