### ISSUE TITLE
关于mysql 多张表查询问题

### ISSUE THREAD

**Issue by xhochipe** [go-xorm/xorm#1097]
> 我先给出sql

>     SELECT  u.`user_name`,   r.`role_name`,  s.`share_token`
        FROM `user` u,  `user_role` ur, `role` r,  `user_source` us, `source` s
       WHERE u.uid = ur.uid
      AND r.`role_id` = ur.`role_id`
      AND us.`uid` = u.uid
       AND us.`source_id` = s.`source_id`

代码中我这样处理
type UserDetail struct {
	Uid        string
	UserName   string
	Staff      int
	Status     int
	ExpireTime string
	RoleName   string
	SourceName string
	SourceOp   string
}
var users []UserDetail
find := settings.MasterDB.Table("user").Alias("u").		Select("u.uid,u.user_name,u.staff,u.status,u.expire_time,r.role_name,s.source_name,s.source_op").
		Join("INNER", []string{"user_role", "ur"}, "ur.uid=u.uid").
		Join("INNER", []string{"role", "r"}, "r.role_id = ur.role_id").
		Join("INNER", []string{"user_source", "us"}, "us.uid = u.uid ").
		Join("INNER", []string{"source", "s"}, "us.source_id = s.source_id ").
		Limit(int(settings.AppBase.PageSize), size*int(settings.AppBase.PageSize)).Find(&users)

但是这里有一个问题不是很理解，作为实现分页，那统计总数怎么去做好点？直接写sql也考虑过，但是已经用了orm，在写一个sql，不是很好的感觉

问题是想求助下，有什么好点优雅的办法统计总条数

**Comment by lunny** [comment]
`FindAndCount`

**Comment by xhochipe** [comment]
@lunny 谢谢我试试
