### ISSUE TITLE
how to do insert as select

### ISSUE THREAD

**Issue by vtolstov** [go-xorm/xorm#1104]
i have table with struct like
```
type X struct {
  UUID string
  Project string
  ID int64
}
```

I know Project and UUID, and for ID i need to specify max(ID) where Project and UUID equal my values.
As i understand i need to use SQL method, but does not understand how to use it with insert statement.

**Comment by lunny** [comment]
It's not supported. You have to `engine.Exec("insert into table1 select * from table2")` to do that currently.

**Comment by lunny** [comment]
And I'm trying to send a PR https://github.com/go-xorm/builder/pull/39 to resolve this.

**Comment by vtolstov** [comment]
Thanks! Does it possible to insert only some columns? For example select uuid from table2 and insert as one value on table1 ?

**Comment by lunny** [comment]
Since https://github.com/go-xorm/builder/pull/39 merged I will close this one.

**Comment by vtolstov** [comment]
thanks!
