### ISSUE TITLE
字段名字为field_1这种形式时不识别

### ISSUE THREAD

**Issue by usernameisnull** [go-xorm/xorm#1108]
数据库的字段名字叫field_1
转为结构体的字段名为 Field1，然后报错
Error 1054: Unknown column 'field1' in 'field list'
应该是xorm转为数据库字段名的时候出错了

**Comment by BetaCat0** [comment]
可以尝试参照如下定义``struct``:  
```
type Entity struct {
   Field1 string `xorm:"field_1"`
}
```
详情参见http://xorm.io/docs ``Column属性定义``一栏
