### ISSUE TITLE
Find 用map[int64]*Userinfo 排序无效

### ISSUE THREAD

**Issue by wxkj001** [go-xorm/xorm#1123]
> goodsCat := make(map[int]*GoodsCatTree, 0)
	err := utils.Engine.Table(new(GoodsCategory)).
		Where("is_show=1").
		OrderBy("sort_order asc").
		Find(&goodsCat)
	if err != nil {
		fmt.Println(err)
	}
这样OrderBy 完全无效

**Comment by lunny** [comment]
这个是Go语言的map的问题。
