### ISSUE TITLE
InsertOne可以返回自增长id，Insert 批量插入数据，无法返回自增的id

### ISSUE THREAD

**Issue by SecThinN** [go-xorm/xorm#1129]

**Comment by SecThinN** [comment]
type User struct{
Id int64 `json:"id"`
Name string  `json:"name"`
}

var users []*User
users = append(users,&User{
Name:"hello",
})
users = append(users,&User{
Name:"hello233",
})

_,err := engine.Insert(users)
if err != nil{
panic(err)
}

for _,eveuser := range users{
fmt.Printf("eveuser:%v\n",eveuser)
}

这里发现，没有自增长的 Id 返回，这是怎么回事，为什么InsertOne就可以返回Id呢？

**Comment by BetaCat0** [comment]
请参阅 http://xorm.io/docs 的 `插入数据`部分，并考虑将您的结构体改写为以下形式：
```
type User struct{
Id int64 `xorm:"pk autoincr 'id'" json:"id"`
Name string `xorm:"name" json:"name"`
}
```

**Comment by SecThinN** [comment]
> 请参阅 http://xorm.io/docs 的 `插入数据`部分，并考虑将您的结构体改写为以下形式：
> 
> ```
> type User struct{
> Id int64 `xorm:"pk autoincr 'id'" json:"id"`
> Name string `xorm:"name" json:"name"`
> }
> ```
你好，谢谢你，情况是这样的，Insert插入单条数据可以正常返回Id，但是sliceStruct这样无法返回
