### ISSUE TITLE
any version release plan?

### ISSUE THREAD

**Issue by FelixSeptem** [go-xorm/xorm#1137]
As go 1.11 released, go mod as the standard package manager for golang in the future. The tool go mod dep on semantic version tag [ref](https://github.com/golang/go/wiki/Modules#how-are-versions-marked-as-incompatible).
I saw the last release was released in two years ago, any plan for new version?

**Comment by lunny** [comment]
I think you missed something. We have v0.7.1 16 days ago.

![image](https://user-images.githubusercontent.com/81045/48191095-39826a00-e37f-11e8-8815-b4044fe74f7e.png)

**Comment by FelixSeptem** [comment]
Maybe something wrong happened.

<img width="1024" alt="2018-11-08 7 42 27" src="https://user-images.githubusercontent.com/15082933/48196785-83268100-e38e-11e8-8c1f-135cd96edf87.png">
