### ISSUE TITLE
这是group by 的特性还是bug？

### ISSUE THREAD

**Issue by usernameisnull** [go-xorm/xorm#1142]
err := engine.Limit(global.Limit, offset).
Where("update_date > ?", maxDate).
GroupBy("company_id").
OrderBy("level_num").Find(&bCategory)
转为sql语句是
SELECT `company_id` FROM `base_category` WHERE (update_date > '1970-01-01 16:00:01') GROUP BY company_id ORDER BY level_num LIMIT 1000
这里我是想SELECT *的，有什么办法么？

**Comment by lunny** [comment]
Any error log?

**Comment by usernameisnull** [comment]
> Any error log?

NO ERROR. I want query all fields, after use GroupBy function just return only one field(the field GroupBy),not the result i want, just want to know, this is a feature or bug?

ps: the sql statement was generated by MySQL LOG

**Comment by lunny** [comment]
This is the feature, you can use `Select(columns)` to specify you want columns but that SQL is not compitable with all databases.
