### ISSUE TITLE
Case-insensitive import collision with Xorm

### ISSUE THREAD

**Issue by Lilahamstern** [go-xorm/xorm#1150]
Hey,

When I try to run my project I am getting: `vendor\github.com\go-xorm\xorm\engine.go:22:2: case-insensitive import collision: "github.com/lilahamstern/Project/vendor/github.com/go-xorm/builder" and "github.com/lilahamstern/Project/vendor/github.com/go-xorm/builder"
vendor\github.com\go-xorm\xorm\cache_lru.go:13:2: case-insensitive import collision: "github.com/lilahamstern/Project/vendor/github.com/go-xorm/core" and "github.com/lilahamstern/Project/vendor/github.com/go-xorm/core"src\controllers\v1\router\routes.go:7:2: case-insensitive import collision: "github.com/lilahamstern/Project/vendor/github.com/go-xorm/xorm" and "github.com/lilahamstern/Project/vendor/github.com/go-xorm/xorm"`

Does anyone know how to solve that problem?

**Comment by BetaCat0** [comment]
I guess that's your project path problem. What I mean is you should not use upper case words in your project path just like `Project` in `github.com/lilahamstern/Project/vendor/github.com/go-xorm/builder`.
