### ISSUE TITLE
xorm reverse mysql 生成的结构中 CURRENT_TIMESTAMP 会多两个引号

### ISSUE THREAD

**Issue by flowercodec** [go-xorm/xorm#1153]
生成的是这样的 
CreatedTime   time.Time `xorm:"not null default 'CURRENT_TIMESTAMP' index TIMESTAMP"`
多了两个单引号，用Sync2同步时会报错

正确的应该是这样的 
CreatedTime   time.Time `xorm:"not null default CURRENT_TIMESTAMP index TIMESTAMP"`

测试环境，最新版的xorm + Win7 64位 + mysql 5.6

**Comment by lunny** [comment]
This should be fixed I think.
