### ISSUE TITLE
Looking forward to session support  multi-threaded, just like golang's context, it will not change when multi-threaded

### ISSUE THREAD

**Issue by relax-admin** [go-xorm/xorm#1155]
Is the session now supporting multi-threading?
How to fix error:Table not found,when query ?

I know that this is correct.
https://github.com/relax-space/xorm-session/blob/master/get/main.go

	func GetAll(session *xorm.Session, offset, limit int) (totalCount int64, fruits []Fruit, err error) {
		errc := make(chan error)

		go func(q xorm.Session) {
			v, err := q.Count(&Fruit{})
			if err != nil {
				errc <- err
				return
			}
			totalCount = v
			errc <- nil

		}(*session)

		go func(q xorm.Session) {
			items := make([]Fruit, 0)
			if err := q.Cols("Name,Code").Limit(limit, offset).Find(&items); err != nil {
				errc <- err
				return
			}
			fruits = items
			errc <- nil
		}(*session)

		if err := <-errc; err != nil {
			return 0, nil, err
		}
		if err := <-errc; err != nil {
			return 0, nil, err
		}
		return
	}

But I am more eager to use xorm.Interface, when using xorm.Interface, I found the following error:Table not found
https://github.com/relax-space/xorm-session/blob/master/get2/main.go

	func GetAll(session xorm.Interface, offset, limit int) (totalCount int64, fruits []Fruit, err error) {
		errc := make(chan error)

		go func() {
			v, err := session.Count(&Fruit{})
			if err != nil {
				errc <- err
				return
			}
			totalCount = v
			errc <- nil

		}()

		go func() {
			items := make([]Fruit, 0)
			if err := session.Cols("Name,Code").Limit(limit, offset).Find(&items); err != nil {
				errc <- err
				return
			}
			fruits = items
			errc <- nil
		}()

		if err := <-errc; err != nil {
			return 0, nil, err
		}
		if err := <-errc; err != nil {
			return 0, nil, err
		}
		return
	}

I found that the session transaction seems to support multi-threading.
https://github.com/relax-space/xorm-session/blob/master/insert1/main.go

**Comment by lunny** [comment]
No. `session` is not goroutine safe. You have to create different `session` on different goroutine.

**Comment by relax-admin** [comment]
I think the session only needs to save the relevant information of the database. As for the table or condition of the query, it should not be memory shared between the go routines.
