### ISSUE TITLE
xorm防SQL注入函数

### ISSUE THREAD

**Issue by Ehuos** [go-xorm/xorm#116]
部分情况下会直接拼接字符串，出于安全的考虑，xorm可以做一个SQL防注入函数

**Comment by lunny** [comment]
因为已经引入了builder，已经解决了此问题。请参考 [github.com/go-xorm/builder](http://github.com/go-xorm/builder)

**Comment by 765643729** [comment]
builder对于like的情况下只能做前后都模糊匹配,并不能只做前匹配,或者后匹配
例如:
a LIKE '123%'
的情况并没有对应的方法

builder中like的方法:
sql, args, _ := ToSQL(Like{"a", "c"})
// a LIKE ? [%c%]

**Comment by lunny** [comment]
Yes. I will send a commit to fix that.
