### ISSUE TITLE
duplicate 找不到已经存在的记录

### ISSUE THREAD

**Issue by guangbaowan** [go-xorm/xorm#1162]
mysql. 事物依次插入表A，B。并发的时候提示A duplicate, 但是此时查询的时候，偶尔会找不到这条已经存在的记录。请问是什么原因呢

**Comment by guangbaowan** [comment]
// (a,b)unique index
type TableA struct {
	a string
	b string
}
type TableB struct{
	c string
}
session.begins()
insert into TableA(a, b)
intert into TableB(c)
commit

when insert into TableA get duplicate error, but sometimes cant find the duplicate records by the inserted data, while can get the data from mysql

**Comment by guangbaowan** [comment]
qps大概2000

**Comment by guangbaowan** [comment]
is this the orm issue or mysql issue? we are using the ariadb of aws.

**Comment by BetaCat0** [comment]
@guangbaowan Seems that's an issue about transaction isolation level. Maybe you can run some experiments to verify :)

**Comment by guangbaowan** [comment]
@BetaCat0  I've checked our  transaction isolation level and do some experiments, it's repeatable read. so it shouldn't have this issue?

**Comment by BetaCat0** [comment]
Nope, I think the crux is the visibility among mysql transactions, not the xorm itself. Because, you know, 
xorm will eventually read data from db. So this might be a problem about the transactions' timeline.

**Comment by guangbaowan** [comment]
I's finished the transaction and then fetch the data . so it's strange. will dip more this weekend . perhaps it's not the orm issue ,perhaps the db issue. .thank you for you guys' help

**Comment by BetaCat0** [comment]
@guangbaowan Try this:

1. start transaction A
2. select * from table t1 in transaction A
3. insert one record into table t1 from **other** transaction
4. again, select * from table t1 in transaction A

By following steps above, you can see that the result set is same all the time, even the record is already existed in db. I think this might be one problem.

**Comment by guangbaowan** [comment]
I've tried this, and cant find the record created in table B, this seems to be the issue. thank you .

**Comment by guangbaowan** [comment]
ok .I'll show the
```
Type User struct {
 id int          (primary)
}
Type UserAccount struct{
id int         (primary)
userID int (unique)
}
func create() (*User, *UserAccount, error) {
if err := session.Begin(); err != nil {
		return nil, nil, err
	}
	ua := &userAccount{
		userID: 111,
	}
	if _, err := session.Insert(ua); err != nil {
		return nil, ua, err
	}
	u := &User{
	}
	if _, err := session.Insert(u); err != nil {
		return nil, nil, err
	}
	session.Commit()
	return u, ua, nil
}
u ,ua , err := create()
if err is duplicate {
    query date from db by ua failed
}
```

**Comment by BetaCat0** [comment]
Here are 2 questions:
1. Where does the session you used in function ``create()`` come from?
2. When ``err is duplicate``  occurrs, do you still use the same session for data ``ua`` querying?

**Comment by guangbaowan** [comment]
1. I use the connection pool ; 
2. the first function ends so this is a new session .

**Comment by BetaCat0** [comment]
Connection pool?  You mean ``engine.NewSession()``? @guangbaowan

**Comment by guangbaowan** [comment]
yes

**Comment by guangbaowan** [comment]
max idle conns = 100
max open conns = 200

**Comment by lunny** [comment]
@guangbaowan you should `defer session.Close()`, on every `NewSession`.

**Comment by guangbaowan** [comment]
@lunny , yes ,i've this

**Comment by guangbaowan** [comment]
It's very strange, one day. i update my sql to "select * from tbl where id in ", then it worked.

**Comment by lunny** [comment]
Another possible, you inserted two duplicated records on the same transaction. I will close this since it seems no clue found. Please feel free to reopen it.
