### ISSUE TITLE
定义字段名为version时给定类型为string，数据库表格生成后设置的默认值为1（int）

### ISSUE THREAD

**Issue by Cloudzp** [go-xorm/xorm#1165]
## 版本号
![image](https://user-images.githubusercontent.com/25190767/49496896-01007e00-f8a2-11e8-8c42-72de31b54b40.png)
## 结构体
![image](https://user-images.githubusercontent.com/25190767/49496923-0fe73080-f8a2-11e8-9558-936fac63783d.png)
## 自动生成的数据表
![image](https://user-images.githubusercontent.com/25190767/49496952-23929700-f8a2-11e8-9349-7cf748900fae.png)
修改字段名后无此问题
![image](https://user-images.githubusercontent.com/25190767/49496981-37d69400-f8a2-11e8-9013-06edca095c9e.png)

**Comment by aprilnops** [comment]
+1, 我也遇到了这个很诡异的问题，查了很久。
