### ISSUE TITLE
Question about Handling zero or blank

### ISSUE THREAD

**Issue by gywndi** [go-xorm/xorm#1171]
Hi,

Thanks to you guys, I can develop my program quickly and easily. But I have some question about zero value or blank string.

If I check some data exists as below,
```
g := Group{ID: 0}
orm.Get(&g)
```

I expect to SQL be generated like this.
```
select .. from group where id = 0 limit 1
```

But, XORM doesn't generate the SQL what I expected. It shows as below.
```
select .. from group limit 1
```

I have fetched the data to be updated from the Get() function result, but if I get 0, I can remove the invalid data. Is there an option to include zero or blank characters in the data processing? 

Best Regards
Chan.

**Comment by BetaCat0** [comment]
Hi chan,
  Thank you for using xorm! By default, golang treats  `0`, `false`, `""` ... as **zero** values and our xorm also use these for default settings. I suggest using this instead:   
```
var g Group
engine.Where("id = ?", id).Get(&g)
``` 
or
```
var g Group
engine.ID(id).Get(&g)
```
or
```
var g Group{ID: 0}
// allow field id using zero value, you can also use for bool values
engine.UseBool("id").Get(&g)
```
  Wish these can help :)

**Comment by gywndi** [comment]
Thanks a lot. :-)
Best Regards,
Chan.
