### ISSUE TITLE
是否考虑支持 Union

### ISSUE THREAD

**Issue by axetroy** [go-xorm/xorm#1172]
需要手动拼接SQL很是痛苦，完了还得进行一遍解析

如果能有这样的API就很棒了

```go
	if err = session.Union(table1, table2, table3).Get(&tableSlice); err != nil {
		return
	}
	
	fmt.Println(tableSlice)
```

**Comment by BetaCat0** [comment]
Hi @axetroy , maybe you can take a look at https://github.com/go-xorm/builder

**Comment by axetroy** [comment]
@BetaCat0 
Thanks for your help!

LGTM!
