### ISSUE TITLE
找不到表  Table not found

### ISSUE THREAD

**Issue by VICTORYGS** [go-xorm/xorm#1174]
不知道表是如何绑定到engine上的?
我感觉我这么写没问题啊, 有大佬知道怎么回事吗?
![image](https://user-images.githubusercontent.com/33747619/50067992-a4d11e80-01fe-11e9-9159-75f30ad8e8a3.png)

**Comment by BetaCat0** [comment]
Hi @VICTORYGS , I think you can try following code:
```
engine.Table("table name").Query(sqlOrArgs ... )
```
