### ISSUE TITLE
Find() does not use TableName() when used as interface

### ISSUE THREAD

**Issue by liepumartins** [go-xorm/xorm#1175]
First of all, I am aware of #891, #887 etc.
I have defined many structs for each table, all of those implement an interface.
I have to use `TableName()` function for xorm to get correct name. This works fine with e.g. `Get()`, however `Find()` says `Table not found`.

````
type DBType interface {
	PrimaryKey() string
	TableName() string
	Slice() []DBType
}

type user struct {
   Id   int64  `json:"id"`
   Name string `json:"name"`
}

func (*user) TableName() string {
	return "mydifferentusertablename"
}
func (*user) PrimaryKey() string {
	return "id"
}
func (*user) Slice() []DBType {
	return []DBType{&user{}}
}

var record = DBType{&user{}}

slice := record.Slice()
````

Get() works:
````
_, err = engine.Get(slice[0])
if err != nil {
	log.Print(err)
}
````
Find() does not:
````
err = engine.Find(slice)
if err != nil {
	log.Print(err)
}
````

Regular struct (not via interface) works:
````
data := make([]user, 0)
err = engine.Find(data)
if err != nil {
	log.Print(err)
}
````

Reasons why I need this, can be found [on SO](https://stackoverflow.com/questions/53777722/golang-generic-database-single-record-to-json), I will not repeat those here.

**Comment by lunny** [comment]
Currently You should use `&slice` as a parameter of `Find`.

**Comment by liepumartins** [comment]
Did you mean?

```
slice := record.Slice()
err = engine.Find(&slice)
...
```

If so, it does not work. Already tried that before creating this issue.

**Comment by lunny** [comment]
This `Find` usage is not supported, you have to use and slice of struct to do that.
