### ISSUE TITLE
Engine with PingContext  to set timeout dostn't work

### ISSUE THREAD

**Issue by dayuanyuan1989** [go-xorm/xorm#1189]
```
        PING_TIMEOUT := 5 * time.Second
        dbSourceName := user + ":" + passwd + "@tcp(" + addr + ")/" + DBName
        Engine, err = xorm.NewEngine("mysql", dbSourceName)
        if err != nil {
                logger.Error(context.TODO(), "init engine", logger.Fields{"err": err})
                return err
        }
        // ping with timeout
        ctx, cancel := context.WithTimeout(context.Background(), PING_TIMEOUT)
        defer cancel()
 =>  err = Engine.PingContext(ctx)
        fmt.Println("ping end")
//      err = Engine.Ping()
        if err != nil {
                logger.Error(context.TODO(), "init engine", logger.Fields{"err": err})
                return err
        }
```

I create a context with timeout 5s, then use engine to connect to a unreachable address , PingContext will block all the time.

**Comment by BetaCat0** [comment]
@dayuanyuan1989 After dubugging, I found this not ping-context's timeout problem. 
When you use ``Engine.Ping()`` in your code, xorm will call function [PingContext(ctx context.Context)]( 
 https://github.com/golang/go/blob/a2e79571a9d3dbe3cf10dcaeb1f9c01732219869/src/database/sql/sql.go#L725) first and then ``db.conn(ctx, cachedOrNewConn)``, in function ``db.conn(ctx, cachedOrNewConn)``, it will call function ``db.connector.Connect(ctx)`` and finally turn out to call ``t.driver.Open(t.dsn)`` which actually provided by [mysql-driver](https://github.com/go-sql-driver/mysql). Now to the point, in function [Open(dsn string) ](https://github.com/go-sql-driver/mysql/blob/c45f530f8e7fe40f4687eaa50d0c8c5f1b66f9e0/driver.go#L54), we can see it try to parse **timeout** config in your **DSN**(aka data-soure-name) but not in existed context. So I think this why PingConext block all the time :)

**Comment by dayuanyuan1989** [comment]
Thanks for your quick reply.

In my mind, when I use grpc Dial, it use DialWithContext(context.Background(),`{address}`), if the `{address}` is unreachable, it will block all the time

But, if I use DialWithContext and set the context with timeout 5s, the program will tell an timeout error

So, whether xorm has the consider to change the action like DialWithContext in grpc

**Comment by lunny** [comment]
cannot reproduce this, see https://github.com/go-xorm/xorm/pull/1193/files
