### ISSUE TITLE
want support jsoniter to en/decode json

### ISSUE THREAD

**Issue by godcong** [go-xorm/xorm#1218]
Is there a jsoniter support plan?

**Comment by lunny** [comment]
Do you mean https://github.com/json-iterator/go ?

**Comment by godcong** [comment]
yes, it's more quickly than golang json.

**Comment by lunny** [comment]
And where do you want to use?

**Comment by godcong** [comment]
to save a value with xorm with `json` tags

**Comment by lunny** [comment]
@godcong why close this one? see #1248
