### ISSUE TITLE
 Duplicate key name IDX_xxx

### ISSUE THREAD

**Issue by hyhc2016** [go-xorm/xorm#1220]
I Use Sync2 to create table or sync table;
first I desgin a struct, which some tables share one struct, for example bills_cny,bills_hkd.
I use engin.Table("table_name").sync2(new(Bills)) , it create the table,but it  cannot be repeated, 
 when I repeat it ,it show  Duplicate key name IDX_xxx.
the struct is 
```go
type Biils struct {
	Id            int64
	CoinId        int64 `xorm:"index(user_coin)"`
	UserId        int64 `xorm:"index(user_coin)"`
	Address       string
	Txid          string `xorm:"index"`
	Confirmations int
	Number        string
	NumberU       string
	Description   string
	OptType       int8
	Status        int8
	CreatedAt     int64 `xorm:"created"`
	UpdatedAt     int64 `xorm:"updated"`
}
```

**Comment by lunny** [comment]
fixed by #1445
