### ISSUE TITLE
[feature request] command to generate frequently-used crud function

### ISSUE THREAD

**Issue by huahuayu** [go-xorm/xorm#1222]
currently, xorm provides db  to struct convert & sync, but don't have the option to generate common crud operations, like: read by primary key, update by primary key, delete by primary key, select one record, select by page...

if the feature is provided it saves a lot of effort and will fulfill most of the requirements.

**Comment by lunny** [comment]
Maybe you mean the github.com/go-xorm/cmd ?

**Comment by huahuayu** [comment]
@lunny yes, the cmd can generate go struct from the database, but can't generate crud code ([beego cmd](https://github.com/beego/bee) tool can do it), I don't mean generate as many as code as `bee cmd`, I just suggest having CRUD operation code generated
