### ISSUE TITLE
how to setup connection for postgresql ?

### ISSUE THREAD

**Issue by youcandoit95** [go-xorm/xorm#1223]
how connect to postgre database ?

before i used mysql for database with this script connection

`

engine, err = xorm.NewEngine("mysql", ""+os.Getenv("MYSQL_DATABASE_USER")+":"+os.Getenv("MYSQL_DATABASE_PASSWORD")+"@tcp("+os.Getenv("MYSQL_DATABASE_HOST")+":"+os.Getenv("MYSQL_DATABASE_PORT")+")/"+os.Getenv("MYSQL_DATABASE_DBNAME")+"?charset=utf8&parseTime=true&timeout=8s&readTimeout=8s&writeTimeout=8s")
	nc := 3 // Increase if needed.
	engine.SetMaxOpenConns(nc)
	engine.SetMaxIdleConns(nc)
	engine.SetConnMaxLifetime(time.Second * 3)
	engine.SetMapper(core.GonicMapper{})

	err_db_connect := engine.Ping()
	if err_db_connect != nil || err != nil {
		fmt.Println(err_db_connect)
		log.Fatal("Error init database")
	}

`

can somebody help me ?

**Comment by lunny** [comment]
go to https://github.com/lib/pq to see the documents
