### ISSUE TITLE
engine.Exec("INSERT INTO user ...") 这种SQL插入的方式怎么获取LastInsertId？

### ISSUE THREAD

**Issue by ikool-cn** [go-xorm/xorm#1233]
engine.Exec("INSERT INTO user ...") 这种SQL插入的方式怎么获取LastInsertId？

**Comment by suifengtec** [comment]
暂时无解，sql.Result结构体的两个方法，只有RowsAffected()可用，并且数字还不是新插入的行的ID，而是1，临时办法只能再新建个唯一的字段，依靠这个字段在插入后查询一下了。

**Comment by lunny** [comment]
此种方式无法获得
