### ISSUE TITLE
check that values present in slice

### ISSUE THREAD

**Issue by vtolstov** [go-xorm/xorm#1234]
I have db, hat in one field contains slice of strings (also i have index for this field).
How in xorm i can check via some condition that string present in slice?

**Comment by vtolstov** [comment]
???

**Comment by BetaCat0** [comment]
Hi @vtolstov , Could you give us an example about it?

**Comment by vtolstov** [comment]
ok, simple struct

type Item struct {
  Name string `xorm:"blob"`
  Tags []string `xorm:"blob index"`
}

i'm insert
item := &Item{Name: "xxx", Tags: []string{"tag1","tag2"}}

i need find in table items, item that have tag tag1

**Comment by lunny** [comment]
@vtolstov this is supported by your database. I know that `postgres` may support that.

**Comment by BetaCat0** [comment]
And if you are using mysql 5.7+, you can try JSON feature for that(for example `` select * from item where JSON_CONTAINS(tags-> '$[*]' , 'tag1', '$') ``).

**Comment by vtolstov** [comment]
Nice, but to have generic variant how to deal with this task?
Now i select needed records and filter it via for loop in go to get only needed value.
How can i get this automatic via xorm?

**Comment by BetaCat0** [comment]
Nope, in `SQL` mode, you have to control your `select` conditions by yourself.
