### ISSUE TITLE
[Question] Can i share `xorm.session` across multiple function?

### ISSUE THREAD

**Issue by solarhell** [go-xorm/xorm#1244]
In my logic i will use multiple model struct.

So can i begin new transaction when i get new request in my controller, and share the session variable across the query function?

![image](https://user-images.githubusercontent.com/10279583/53865826-0ac58900-402b-11e9-90e6-f26326c06276.png)

**Comment by BetaCat0** [comment]
Of course you can. Actually you can use it for a logic transaction in your business code.(e.g. like transfer money from an account to another). I suggest using ``engine.Transaction(func(session *xorm.Session) (interface{}, error) {...})`` soyou dont need to care about ``session.Close()``.

**Comment by solarhell** [comment]
Thanks for your reply!

I just changed my code to the following style.
![image](https://user-images.githubusercontent.com/10279583/53869016-457eef80-4032-11e9-9422-ac74ec2ad500.png)

The issue is that these functions will all begin(create) their own transaction. @BetaCat0

**Comment by BetaCat0** [comment]
Almost.But be careful that you should use ``session`` instead of ``engine`` inside of function ``Transaction``, otherwise your operations is not in a same transaction.

**Comment by solarhell** [comment]
Thanks a lot!

```
func GetRecordsCountByUid(session *xorm.Session, uid int) (total int64, err error) {
	var record Record

	_, err = engine.Transaction(func(*xorm.Session) (interface{}, error) {
		total, err = session.Where("created_by = ?", uid).Count(record)
		return total, err
	})

	return total, err
}
```

this is the final version.

**Comment by BetaCat0** [comment]
If you just launch a single query(like above), usually you dont need such a transaction(use engine.session.Where() is fine :) ). But in some complex business flow like following:
```
   Transfer 100 yuan from account A to account  B
   1.  -100 yuan from account A
   2.  +100 yuan to account B
```
These must be atomic. So in such case I suggest using func ``Transaction``.

**Comment by solarhell** [comment]
Yes, i can understand.

In your example, imagine that we have two table: balance(余额) and log(转账记录).

So i need to operate balance table and log table. I need to ensure two actions(`change balance(改变A和B的余额)` and `add log（增加转账和收入记录）`) in the same one transaction.

I mean that this two actions can't use the same one transaction.
Maybe i need to make `engine` to `Engine` to let it accessible in my controller package and manually call `session := Engine.NewSession()`, so i can use only one transaction to complete my logic?

**Comment by BetaCat0** [comment]
You mean separately session? ``engine.Where()`` and ``engine.NewSession()`` are both okay.

**Comment by solarhell** [comment]
My english is poor 😅. May i have you IM account so i can directly send message to you? I just sent an email to you.

**Comment by BetaCat0** [comment]
你可以加QQ群来探讨问题😁
