### ISSUE TITLE
含后缀表操作问题（operate table with suffix）

### ISSUE THREAD

**Issue by bluesky1024** [go-xorm/xorm#1245]
xorm要对表进行加后缀，是针对 orm.Engine设置 SetTableMapper(core.NewSuffixMapper(core.SnakeMapper{},"_201903"))，这个后缀的设置对使用该engine的所有表都有效。
所以使用的时候发现这两个问题，
1.首先是如果一次查询需要跨多个时间段的话，如果想同时查询是否需要实例化多个engine？
2.如果我需要进行事务操作，这时候需要在一个engine里，如果涉及事务的这几张表的后缀格式不同，是否就无法进行事务操作了？

**Comment by BetaCat0** [comment]
1. 可以在每次查询都通过``.Table()``来指定表，(这时候使用同样的entity是ok的)
2. 不是同一个engine, 而是应该在同一个session(这样可以全量回滚)，如果表都在一起，通过``engine.Transaction(...)``来创建一个自动提交的事务(失败会自动回滚)。具体可以参考[这里](https://github.com/go-xorm/xorm/issues/1244)

**Comment by bluesky1024** [comment]
多谢你的帮助了，我先尝试一下操作。
