### ISSUE TITLE
是否可以配置where为空时报错

### ISSUE THREAD

**Issue by eleztian** [go-xorm/xorm#1251]
在使用过程中，可能忘了进行参数检查导致全表更新或者拉取全表的灾难性错误。是否可以配置不允许where为空。

**Comment by BetaCat0** [comment]
建议业务代码经过充分测试再行发布，在更新/删除场景建议使用``engine.Transaction``(``NewSession``也可以，但是记得声明``defer session.Close()``及时关闭session)。当更改发生后，通过校验返回的``effect``值来判断是否符合预期，如不符合，则通过抛出``error``的方式来回滚事务。

**Comment by lunny** [comment]
We can refactor xorm via `statement.last_error`
