### ISSUE TITLE
update更新字段失败

### ISSUE THREAD

**Issue by AIBUSHISHOU** [go-xorm/xorm#1254]
struct 定义
type Users struct {
	Id            string    `xorm:"id" json:"id"`
	Name          string    `xorm:"name" json:"name"`
	Phone         string    `xorm:"phone" json:"phone"`
	Email         string    `xorm:"email" json:"email"`
	Password      string    `xorm:"password" json:"password"`
	IP            string    `xorm:"ip" json:"ip"`
	Status        int       `xorm:"status" json:"status"`
	Role          int       `xomr:"role" json:"role"`
	LastLoginTime time.Time `xorm:last_login_time" json:"last_login_time"`
}
uu := &Users{
	Status: 0,
}

Engine.Table("users").Where("id =?", id).Update(uu)

执行update后，没有更新数据库中status的值，实际数据库中的status的值仍然为1，返回提示说没有可更新的字段。

**Comment by solarhell** [comment]
零值需要加上 `Cols('status')` 强制更新。

**Comment by solarhell** [comment]
文档有提到
```
这里需要注意，Update会自动从user结构体中提取非0和非nil得值作为需要更新的内容，因此，如果需要更新一个值为0，则此种方法将无法实现，因此有两种选择：
```

**Comment by AIBUSHISHOU** [comment]
好的，是我的疏忽，谢谢你的回复。 @solarhell
