### ISSUE TITLE
使用Were（builder.In()）等条件编辑器报错

### ISSUE THREAD

**Issue by YanserLiu** [go-xorm/xorm#1261]
使用builder接口添加查询mysql数据库
![image](https://user-images.githubusercontent.com/26165104/55373667-7de1f280-5538-11e9-814a-4bb5d4f98e55.png)

func (this *PlacementReq) GetAllPlacementInfo(offset, limit int) ([]Placement, error) {
	placement := make([]Placement, 0)
	err := Engine.Where(builder.NotIn("Id", 1, 2)).Limit(limit, offset).Find(&placement)
	if err != nil {
		logs.Error(err)
		return nil, err
	}
	return placement, nil
}

报错打印：
2019/04/02 11:10:04.416 [E] [placement_controller.go:98]  Unsupported condition type

尝试了builder其他接口，好像也不能使用。不知道是哪里错误了

**Comment by lunny** [comment]
Which version of your xorm and builder?
