### ISSUE TITLE
Generating SQL statements for Oracle database driver oci8 is to cancel double quotation marks for database name

### ISSUE THREAD

**Issue by FirewoodBloody** [go-xorm/xorm#1268]
Novice: The Sql statement database name generated during Oracle project has double quotation marks, which makes it impossible to identify the database name.

I modified it manually, and added DriverName to store the driver name. In the operation of database name, I made IF judgment.

**Comment by lunny** [comment]
Could you send a PR to fix that?

**Comment by FirewoodBloody** [comment]
understand。How to proceed    Transformation Golang time.Time and Oracle Date

**Comment by FirewoodBloody** [comment]
understand。How to proceed Transformation Golang time.Time and Oracle Date
