### ISSUE TITLE
the Get() method does not support extended struct

### ISSUE THREAD

**Issue by MarkLux** [go-xorm/xorm#1275]
the `Get()` method does not work well when I use a extended struct like below:

```
type BaseDO struct {
	CreatedAt int64
	UpdatedAt int64
}

type User struct {
	Id int64
	Name string
	Email string
	Password string
	AddOn string
	BaseDO // extend two members from BaseDO
}
```

when I execute the code below, I got an error of `not supported {0 0} as []`:

```
u := User{
		Email: "marlx6590@163.com",
	}
res, err := engine.Get(&u)
```

I wonder how should I handle this situation? There are many structs that need `CreatedAt` and `UpdatedAt`.

env:

- golang 1.12.1 on osX 10.11
- x-orm v0.7.1 from go mod

**Comment by lunny** [comment]
You should add a tag on `BaseD0`
```
 BaseD0 `xorm:"extends"`
```

**Comment by MarkLux** [comment]
Thanks a lot!
