### ISSUE TITLE
多列索引在查询时自动添加条件

### ISSUE THREAD

**Issue by youtwo123** [go-xorm/xorm#1278]
如果表中含有多列索引，在查询时会自动添加查询条件，比如表结构如下
create table instances (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `deleted` tinyint(1) DEFAULT NULL,
  `uuid` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `instances_uuid_deleted_idx` (`uuid`,`deleted`),
) ENGINE=InnoDB  DEFAULT CHARSET=utf8；

xorm条件如下
err = engine.Table("instances").In("uuid", uuids).Find(&instances)
instances结构如下
type Instances struct {
	Uuid    string `json:"uuid" xorm:"uuid"`
	Host    string `json:"host" xorm:"host"`
	Deleted int    `json:"deleted" xorm:"deleted"`
}

xorm解析出来的语句如下
SELECT `uuid`, `host`, `deleted` FROM `instances` WHERE `uuid` IN (?,?) AND (`deleted` IS NULL OR `deleted`=?) []interface {}{"92852c10-db1b-473c-b85f-f5e506c1b3ed", "e4966c33-8702-471d-b13c-93cee0a706f7",, "0001-01-01 00:00:00"}

求解！

**Comment by lunny** [comment]
deleted is a keyword of xorm, you could use `xorm:"'deleted'"` to avoid that.

**Comment by youtwo123** [comment]
It works, thanks!
