### ISSUE TITLE
Log off does not take effect

### ISSUE THREAD

**Issue by relax-admin** [go-xorm/xorm#1279]
## Log off does not take effect

    db.SetLogLevel(core.LOG_OFF)
    db.Ping()

### exp

Do not output any logs

### act

[mysql] 2019/04/25 06:20:54 packets.go:41: unexpected EOF

### Log Lever

> I think LOG_OFF should be the highest priority, but now the latest xorm highest priority is LOG_UNKNOWN.

	const (
		// !nashtsai! following level also match syslog.Priority value
		LOG_DEBUG LogLevel = iota
		LOG_INFO
		LOG_WARNING
		LOG_ERR
		LOG_OFF
		LOG_UNKNOWN
	)

**Comment by lunny** [comment]
That log outputed by mysql driver, not XORM.

**Comment by relax-admin** [comment]
ok,I make an issue in mysql

https://github.com/go-sql-driver/mysql/issues/956

**Comment by relax-admin** [comment]
Is it possible to close all logs via xorm, including the mysql log?

**Comment by lunny** [comment]
@relax-admin that's impossible. Please go to github.com/go-sqli-driver/mysql to fire an issue.

**Comment by relax-admin** [comment]
ok

https://github.com/go-sql-driver/mysql/issues/956
