### ISSUE TITLE
create table with int error

### ISSUE THREAD

**Issue by efineBai** [go-xorm/xorm#1286]
engine.CreateTables(&UserInfo{}) error occured ,with 
type UserInfo struct {
	uid          int64	  `xorm:"pk notnull"` // this field is ok
	timeZone     	int8 // this field will panic. If add extra xorm config like uid field, the error below will disapper
}

panic stack is :
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface(0x16f7d40, 0xc0001a20f8, 0x36, 0x16f7d01, 0xc0001a20f8, 0x36)
	/usr/local/go/src/reflect/value.go:990 +0x1bf
reflect.Value.Interface(...)
	/usr/local/go/src/reflect/value.go:979
github.com/go-xorm/xorm.(*Engine).mapType(0xc0000aaa90, 0x1781360, 0xc0001a20f0, 0x199, 0x1781300, 0xc0001a20f0, 0x16)
	/Users/castlebai/go/pkg/mod/github.com/go-xorm/xorm@v0.7.1/engine.go:1003 +0x9fe
github.com/go-xorm/xorm.(*Engine).autoMapType(0xc0000aaa90, 0x1781360, 0xc0001a20f0, 0x199, 0x0, 0x0, 0x0)
	/Users/castlebai/go/pkg/mod/github.com/go-xorm/xorm@v0.7.1/engine.go:817 +0x154
github.com/go-xorm/xorm.(*Statement).setRefBean(0xc0001bbca8, 0x16f8bc0, 0xc0001a20f0, 0xc0001bbc38, 0x168b1bb)
	/Users/castlebai/go/pkg/mod/github.com/go-xorm/xorm@v0.7.1/statement.go:218 +0x69
github.com/go-xorm/xorm.(*Session).createTable(0xc0001bbc90, 0x16f8bc0, 0xc0001a20f0, 0x194f0c0, 0xc000010010)
	/Users/castlebai/go/pkg/mod/github.com/go-xorm/xorm@v0.7.1/session_schema.go:35 +0x4e
github.com/go-xorm/xorm.(*Engine).CreateTables(0xc0000aaa90, 0xc0001bbf78, 0x1, 0x1, 0x0, 0x0)
	/Users/castlebai/go/pkg/mod/github.com/go-xorm/xorm@v0.7.1/engine.go:1312 +0x12d
main.main()
	/Users/castlebai/Documents/git/unigo/unifiedLoginSys/dao/db.go:67 +0x294

**Comment by lunny** [comment]
```
cannot return value obtained from unexported field or metho
```
field name should be upper.
