### ISSUE TITLE
A question about usage of 'affected'

### ISSUE THREAD

**Issue by CrazyNash** [go-xorm/xorm#1289]
'affected' returned together with error from lots' of executions, such as

```
affected, err := engine.Exec("update user set age = ? where name = ?", age, name)
```

Is it necessary to check 'affected' to ensure success even err==nil?

**Comment by lunny** [comment]
@CrazyNash You could check that is the expected to confirm that your SQL is not wrong one. And I think most situations, ignore that will be OK.

**Comment by CrazyNash** [comment]
Thank you @lunny
