### ISSUE TITLE
New Query API

### ISSUE THREAD

**Issue by ahall** [go-xorm/xorm#129]
From #110. Currently the session API is tightly coupled with the statement and the session should be only encapsulating an isolated database session / transaction. It would be preferable to expose only .MakeQuery() instead of having the session expose operations such as .Count(), .Find() etc. but rather move this functionality inside a query struct which can then be extended by the caller in order to make a friendly abstraction. To implement this fully we'd need to break backwards compatibility so I suggest we don't remove operations such as .Count(), .Find() but instead make the session have a default query which is used, but normally the caller would construct a query and then use it and execute it for example:

    query := session.MakeQuery()
    query = query.And("username = ?", "username)
    query = query.And("email = ?", "email")
    // bunch of other filters dynamically built up

    count, err := query.Count(&User{})
    err := query.Find(&users)

This means less book keeping for the session.

Another brilliant use of having the Query struct abstraction would be to build your own Query struct e.g.:

    type UserQuery struct {
        Query *xorm.Query
    }

    func (this *UserQuery) FindByName(name string) *UserQuery {
        return this.Query.Where("name = ?", name)
    }

And various other cool stuff. Also subqueries:

    query := session.Query()

    var ids []int64
    idsQuery := session.Query().Where(...)
    query.Where("id in ?", idsQuery)

Subqueries suport is something that would be cool in the future.

**Comment by lunny** [comment]
This will not be implemented since I have implemented `github.com/go-xorm/builder` and create a new xorm branch builder. This branch will be merged to master some time later. So I close this issue. If you have any issue, please open it.
