### ISSUE TITLE
xorm可以支持达梦数据库吗

### ISSUE THREAD

**Issue by flame2017** [go-xorm/xorm#1291]

**Comment by flame2017** [comment]
如果不支持的话，需要什么dialect?

**Comment by lunny** [comment]
Currently there is no Go database driver I think.

**Comment by flame2017** [comment]
Thanks


发自网易邮箱大师


在2019年05月7日 09:44，Lunny Xiao<notifications@github.com> 写道：

Currently there is no Go database driver I think.
