### ISSUE TITLE
sync2 不支持自定义表名且表存在情况下的同步

### ISSUE THREAD

**Issue by meiyang1123** [go-xorm/xorm#1295]
是否可以考虑先简单的把
https://github.com/go-xorm/xorm/blob/6a1dd5973789318df3a253c0d42345ac5a9abd00/session_schema.go#L251
更改为

![image](https://user-images.githubusercontent.com/48953728/57288628-6cb67380-70ec-11e9-901c-6304e3119eaf.png)

**Comment by lunny** [comment]
fixed by #1445
