### ISSUE TITLE
开启缓存后的查询会产生2次这个怎么解决呢?

### ISSUE THREAD

**Issue by boneq** [go-xorm/xorm#1298]
<img width="1298" alt="屏幕快照 2019-05-09 23 17 12" src="https://user-images.githubusercontent.com/24372727/57465388-19d9e900-72b1-11e9-9e26-65f53ced0585.png">

caches := xorm.NewLRUCacher(xorm.NewMemoryStore(), 1000)
	Db.SetDefaultCacher(caches)

开启缓存后会产生2次查询，如果查到了就不会出现2次查询，如果没有查到每次都会产生2次查询，这个怎么解决呢？

**Comment by jinjiang2009** [comment]
我测试开启缓存？然后修改数据库的数据，比如name字段“joe”改成了“limei”，可是查询结果也变成了“limei”，内存缓存中应该还是"joe"吧？

**Comment by boneq** [comment]
@jinjiang2009 你是用数据库管理工具修改的？
