### ISSUE TITLE
Query result to struct

### ISSUE THREAD

**Issue by huahuayu** [go-xorm/xorm#1299]
Hi as the docs shows, engine.Query method can get rows in forms of map[string]string or map[string]interface{}, but how can I transform the map to struct?  

```
results, err := engine.Query("select * from user")
results, err := engine.Where("a = 1").Query()

results, err := engine.QueryString("select * from user")
results, err := engine.Where("a = 1").QueryString()

results, err := engine.QueryInterface("select * from user")
results, err := engine.Where("a = 1").QueryInterface()
```

**Comment by lunny** [comment]
```go
var user User
engine.SQL("select * from user").Get(&user)
```

**Comment by huahuayu** [comment]
as per the Get() method comments:  
```
// Get retrieve one record from the database, bean's non-empty fields
// will be as conditions
```
it will only retrieve one record from the database, but if the SQL returns multi records, dose Get() still works?

**Comment by lunny** [comment]
For multiple records,
```go
var users []User
engine.SQL("select * from user").Find(&users)
```

**Comment by huahuayu** [comment]
> For multiple records,
> 
> ```go
> var users []User
> engine.SQL("select * from user").Find(&users)
> ```

yep, just noticed, but why the method name is Find(), which makes me confused, kind of misleading, makes me think it's used to search some specific data.
