### ISSUE TITLE
between support

### ISSUE THREAD

**Issue by huahuayu** [go-xorm/xorm#1300]
hi, it seems xorm don't support mysql `bewteen` operation, my sql is like below and get an error, how to deal it with xorm way?
```
	err = DB.Table("sell").Alias("a").
		Select("c.asset_platform, c.asset_identifier, a.update_ts, c.debtor,c.amount,a.apr,c.due_dt,b.rating,d.trade_credit").
		Join("LEFT OUTER", []string{"asset", "b"}, "a.asset_id = b.id").
		Join("LEFT OUTER", []string{"assetdetail", "c"}, "b.asset_platform = c.asset_platform and b.asset_identifier = c.asset_identifier").
		Join("LEFT OUTER", []string{"user", "d"}, "a.user_id = d.id").
		In("c.asset_platform", param.AssetPlatform).
		Where(fmt.Sprintf("c.amount between %s and %s", param.AmountLow, param.AmountHigh)).
		Where(fmt.Sprintf("a.apr between %s and %s", param.AprLow, param.AprHigh)).
		Where(fmt.Sprintf("b.rating between %s and %s", param.RatingLow, param.RatingHigh)).
		Where(fmt.Sprintf("d.trade_credit between %s and %s", param.TradeCreditLow, param.TradeCreditHigh)).
		OrderBy("a.update_ts desc").
		Limit(param.Page, param.Offset).
		Find(assetlist1)

	if err != nil {
		logrus.Panic("组合查询失败" + err.Error())
	}
```

error:  
```
{"level":"panic","msg":"组合查询失败Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%!s(float64=0) and %!s(float64=9.99999999e+08)) AND (a.apr between %!s(int=0) an' at line 1","time":"2019-05-16T14:54:58+08:00"}
```

by the way, how to print the final sql executed in MySQL, so I can debug?

**Comment by BetaCat0** [comment]
Hi @huahuayu , I think you could use ``Where("condition_a = ? and condition_b = ?", param_a, param_b)`` instead of using ``fmt.Sprintf(...)`` directly. Moreover, I suggest you using ``Where... (And/Or) ...`` instead of ``Where... Where...`` which is more readable.

**Comment by huahuayu** [comment]
> Hi @huahuayu , I think you could use `Where("condition_a = ? and condition_b = ?", param_a, param_b)` instead of using `fmt.Sprintf(...)` directly. Moreover, I suggest you using `Where... (And/Or) ...` instead of `Where... Where...` which is more readable.

Thank you, yes, `Where("condition_a = ? and condition_b = ?", param_a, param_b)` do the trick, the sql don't painc now, but no data returned, which way do you suggest I to print the final sql executed in MySQL, so I can check the issue.

**Comment by BetaCat0** [comment]
You can set ``engine.ShowSQL(true)`` to get final SQL. It's useful in dev mode.

**Comment by huahuayu** [comment]
> You can set `engine.ShowSQL(true)` to get final SQL. It's useful in dev mode.

do the trick

**Comment by lunny** [comment]
If you have many conditions, I suggest you to use `github.com/go-xorm/builder` to compose your conditions.
