### ISSUE TITLE
dynamic order by

### ISSUE THREAD

**Issue by huahuayu** [go-xorm/xorm#1301]
hi, I need to write a sql for dynamic sort, which is quite common(I think this scenario is worth to be added to examples), user can choose to sort by some fields.   

I don't want to evaluate the sort fields and write different sql, by default it's sort by update_timestamp desc, but it can be more fields, ascending or descending.    

What's the best practice to implement in xorm?   

![image](https://user-images.githubusercontent.com/1725060/57835721-c3f5cb80-77f1-11e9-84de-332408d94fb4.png)

by default, order by update_ts desc, I have this sql:  
```
	err = DB.Table("sell").Alias("a").
		Select("c.asset_platform, c.asset_identifier, a.update_ts, c.debtor,c.amount,a.apr,c.due_dt,b.rating,d.trade_credit").
		Join("LEFT OUTER", []string{"asset", "b"}, "a.asset_id = b.id").
		Join("LEFT OUTER", []string{"assetdetail", "c"}, "b.asset_platform = c.asset_platform and b.asset_identifier = c.asset_identifier").
		Join("LEFT OUTER", []string{"user", "d"}, "a.user_id = d.id").
		In("c.asset_platform", param.AssetPlatform).
		Where("c.amount between ? and ?", param.AmountLow, param.AmountHigh).
		Where("a.apr between ? and ?", param.AprLow, param.AprHigh).
		Where("b.rating between ? and ?", param.RatingLow, param.RatingHigh).
		Where("d.trade_credit between ? and ?", param.TradeCreditLow, param.TradeCreditHigh).
		OrderBy("a.update_ts desc").
		Limit(param.Offset, param.Page).
		Find(assetlist1)
```
@BetaCat0

**Comment by BetaCat0** [comment]
Since ``xorm.session`` is using builder pattern, you are free to build query conditions. 
Assume you have a list of ``ORDER BY`` condition, you may try:
```
session := engine.Table("table_name").Where(....)
// here we deal with ORDER BY conditons
for _, cond := range orderByConditions {
   session = session.OrderBy(fmt.Sprintf("%v %v", cond.ParamName, cond.Order))
}

session.Find(...)
```

**Comment by huahuayu** [comment]
@BetaCat0 thank you! New skill get ✔
