### ISSUE TITLE
sql result queried by xorm is different then I executed from client 

### ISSUE THREAD

**Issue by huahuayu** [go-xorm/xorm#1308]
## problem summary
the sql result queried by xorm is different then I executed from client  
I found this issue in my project and create a repo to demonstrate it, please check   

## environment
go: 1.12.4  
mysql: 5.7.12  

## steps to reproduce
1. clone this repo  https://github.com/huahuayu/xorm-issue 
1. have mysql installed  
1. create a database named asset  
1. execute the init.sql script to import the tables  
1. modify main.go accordingly(DSN part)  
1. go run main.go  
1. check the output, the orderId result is not right

@lunny @BetaCat0

**Comment by lunny** [comment]
You should rename `OrderID` -> `OrderId` or you can use core.LintGonicMapper.

**Comment by huahuayu** [comment]
@lunny you are right, problem solved, thank you!
