### ISSUE TITLE
xorm is generating enormous amount of SQL queries

### ISSUE THREAD

**Issue by ahall** [go-xorm/xorm#131]
I'm using xorm extensively in a project of mine and I'm modelling the relationships/associations in a composed object instead of referencing the Id's as an integer such as (I've excluded few properties there on purpose): 

	type Platform struct {
		Id          int64  `xorm:"id"`
		Name        string `xorm:"name"`
		Description string `xorm:"description"`
	}
	type Device struct {
		Id                int64        `xorm:"id"`
		Uuid              string       `xorm:"uuid"`
		Hostname          string       `xorm:"hostname"`
		CreatedAt         time.Time    `xorm:"created_at"`
		Platform          Platform     `xorm:"platform_id"`
	}

First I want to ask if you think it's a bad idea to do this, should have take out the Platform and use PlatformId as int64 and just load the relationships myself? What I like about doing it this way is having it be able to load it for me and then caching it within the session. When I'm querying it using the xorm session I'd prefer it not to be loaded by default but have a method to load it for me, and an option to eagerly load the Platform. It seems to be eagerly loading it and seems to do it twice. I'm doing:

    has, err := session.Where("uuid = ?", authInfo.Uuid).Get(&device)

And the SQL generated is as follows:

    [xorm] 2014/06/11 15:19:59.321855 [info] [sql] SELECT "id", "uuid", "description", "hostname", "auth_pass", "created_at", "last_activity_at", "platform_id", "agent_architecture_id", "organization_id" FROM "devices" WHERE uuid = $1 LIMIT 1 [args] [5ee29b7f-61a5-47c2-78ff-65f6336e477c]

    [xorm] 2014/06/11 15:19:59.322952 [debug] empty zone key[%v] : %v | zone: %v | location: %+v
     created_at 2014-06-10 17:38:38 +0000 +0000  { [{ 0 false}] [{-9223372036854775808 0 false false}] -9223372036854775808 9223372036854775807 0xc2101059a0}

    [xorm] 2014/06/11 15:19:59.322968 [debug] empty zone key[%v] : %v | zone: %v | location: %+v
     last_activity_at 2014-06-10 17:38:38 +0000 +0000  { [{ 0 false}] [{-9223372036854775808 0 false false}] -9223372036854775808 9223372036854775807 0xc210105a00}

    [xorm] 2014/06/11 15:19:59.322992 [info] [sql] SELECT "id", "name", "description" FROM "platforms" WHERE "id" = $1 LIMIT 1 [args] [1]

    [xorm] 2014/06/11 15:19:59.326805 [info] [sql] SELECT "id", "name", "description" FROM "platforms" WHERE "id" = $1 LIMIT 1 [args] [1]

    [xorm] 2014/06/11 15:19:59.327232 [info] [sql] SELECT "id", "name", "description" FROM "architectures" WHERE "id" = $1 LIMIT 1 [args] [2]

    [xorm] 2014/06/11 15:19:59.327772 [info] [sql] SELECT "id", "name", "description" FROM "architectures" WHERE "id" = $1 LIMIT 1 [args] [2]

    [xorm] 2014/06/11 15:19:59.328345 [info] [sql] SELECT "id", "name", "created_at", "description", "secret", "created_by_id" FROM "organizations" WHERE "id" = $1 LIMIT 1 [args] [1]

    [xorm] 2014/06/11 15:19:59.328892 [debug] empty zone key[%v] : %v | zone: %v | location: %+v
     created_at 2014-06-10 15:35:05 +0000 +0000  { [{ 0 false}] [{-9223372036854775808 0 false false}] -9223372036854775808 9223372036854775807 0xc2100ed4e0}

    [xorm] 2014/06/11 15:19:59.328935 [info] [sql] SELECT "id", "created_at", "username", "email", "fullname", "password", "api_key", "active", "activation_code", "activation_code_expiry", "forgotpass_code", "forgotpass_code_expiry" FROM "users" WHERE "id" = $1 LIMIT 1 [args] [1]

    [xorm] 2014/06/11 15:19:59.332707 [debug] empty zone key[%v] : %v | zone: %v | location: %+v
     created_at 2014-06-09 22:20:58 +0000 +0000  { [{ 0 false}] [{-9223372036854775808 0 false false}] -9223372036854775808 9223372036854775807 0xc21000aee0}

    [xorm] 2014/06/11 15:19:59.332780 [info] [sql] SELECT "id", "created_at", "username", "email", "fullname", "password", "api_key", "active", "activation_code", "activation_code_expiry", "forgotpass_code", "forgotpass_code_expiry" FROM "users" WHERE "id" = $1 LIMIT 1 [args] [1]

    [xorm] 2014/06/11 15:19:59.333172 [debug] empty zone key[%v] : %v | zone: %v | location: %+v
     created_at 2014-06-09 22:20:58 +0000 +0000  { [{ 0 false}] [{-9223372036854775808 0 false false}] -9223372036854775808 9223372036854775807 0xc2100b7d60}

    [xorm] 2014/06/11 15:19:59.333398 [info] [sql] SELECT "id", "name", "created_at", "description", "secret", "created_by_id" FROM "organizations" WHERE "id" = $1 LIMIT 1 [args] [1]

    [xorm] 2014/06/11 15:19:59.333729 [debug] empty zone key[%v] : %v | zone: %v | location: %+v
     created_at 2014-06-10 15:35:05 +0000 +0000  { [{ 0 false}] [{-9223372036854775808 0 false false}] -9223372036854775808 9223372036854775807 0xc21010cb80}

    [xorm] 2014/06/11 15:19:59.333767 [info] [sql] SELECT "id", "created_at", "username", "email", "fullname", "password", "api_key", "active", "activation_code", "activation_code_expiry", "forgotpass_code", "forgotpass_code_expiry" FROM "users" WHERE "id" = $1 LIMIT 1 [args] [1]

    [xorm] 2014/06/11 15:19:59.334195 [debug] empty zone key[%v] : %v | zone: %v | location: %+v
     created_at 2014-06-09 22:20:58 +0000 +0000  { [{ 0 false}] [{-9223372036854775808 0 false false}] -9223372036854775808 9223372036854775807 0xc21010f680}

    [xorm] 2014/06/11 15:19:59.334324 [info] [sql] SELECT "id", "created_at", "username", "email", "fullname", "password", "api_key", "active", "activation_code", "activation_code_expiry", "forgotpass_code", "forgotpass_code_expiry" FROM "users" WHERE "id" = $1 LIMIT 1 [args] [1]

    [xorm] 2014/06/11 15:19:59.334710 [debug] empty zone key[%v] : %v | zone: %v | location: %+v
     created_at 2014-06-09 22:20:58 +0000 +0000  { [{ 0 false}] [{-9223372036854775808 0 false false}] -9223372036854775808 9223372036854775807 0xc210115420}

As you can see here it's loading the platforms and architectures twice. Then it's repeating the same queries over and over again multiple times.

Any idea what's going on here?

**Comment by glight2000** [comment]
I got this error when update the time column with "time.Now()".
The struct is like this:
```go
type User struct{
    Id int64
    LoginTime time.Time    //with no Tags
}
```
The first time I updated the default empty column, the data would be "0001-01-01 00:00".
And the second time I updated this column will cause the error:
```
[xorm] [debug] 2016/03/07 19:02:05.288149 empty zone key[create_time] : 2016-03-04 09:42:57 +0000 +0000 | zone:  | location: {name: zone:[{name: offset:0 isDST:false}] tx:[{when:-9223372036854775808 index:0 isstd:false isutc:false}] cacheStart:-9223372036854775808 cacheEnd:9223372036854775807 cacheZone:0xc8201874c0}
[xorm] [debug] 2016/03/07 19:02:05.288187 empty zone key[update_time] : 2016-03-04 09:42:57 +0000 +0000 | zone:  | location: {name: zone:[{name: offset:0 isDST:false}] tx:[{when:-9223372036854775808 index:0 isstd:false isutc:false}] cacheStart:-9223372036854775808 cacheEnd:9223372036854775807 cacheZone:0xc8201874c0}
[xorm] [debug] 2016/03/07 19:02:05.288207 empty zone key[last_login] : 0001-01-01 00:00:00 +0000 +0000 | zone:  | location: {name: zone:[{name: offset:0 isDST:false}] tx:[{when:-9223372036854775808 index:0 isstd:false isutc:false}] cacheStart:-9223372036854775808 cacheEnd:9223372036854775807 cacheZone:0xc8201874c0}
&{27 13ca3fb45351b96d09f948c6ccfa0193 afb8966018895b02215f80c1c12314f0 15210600905 2     false 0  2016-03-04 09:42:57 +0800 CST 2016-03-04 09:42:57 +0800 CST 0001-01-01 00:00:00 +0800 CST 0 1}
```
Please help .
Thank you very much.
