### ISSUE TITLE
Insert方法传入指针数组调用后，数组中所有元素的id没有赋值，updated字段赋值了（postgres数据库）

### ISSUE THREAD

**Issue by vvnotw** [go-xorm/xorm#1310]
ENV:
github.com/go-xorm/builder
v0.3.4
github.com/go-xorm/core
v0.6.2
github.com/go-xorm/xorm
v0.7.1

Code:
package main

import (
	"fmt"
	"time"

	"github.com/go-xorm/xorm"
	_ "github.com/lib/pq"
)
type User struct {
	Id         int64 `xorm:"pk autoincr"`
	UpdateTime time.Time `xorm:"updated"`
}

func main() {
        //init your engine
        // engine, _ := xorm.NewEngine("postgres", "") 
	fengine, err
	engine.Sync2(new(User))
	var user User
	var user2 User
	users := []*User{&user, &user2}
	fmt.Printf("%v %v\n", users[0], users[1])
	fmt.Println(engine.Insert(users))
	fmt.Printf("%v %v\n", users[0], users[1])
	orm.Close()
}

Output：
&{0   0001-01-01 00:00:00 +0000 UTC} &{0   0001-01-01 00:00:00 +0000 UTC}
2 <nil>
&{0   2019-05-29 12:58:38.341254738 +0800 CST} &{0   2019-05-29 12:58:38.341254738 +0800 CST}

Expected output:
&{0   0001-01-01 00:00:00 +0000 UTC} &{0   0001-01-01 00:00:00 +0000 UTC}
2 <nil>
&{1   2019-05-29 12:58:38.341254738 +0800 CST} &{2   2019-05-29 12:58:38.341254738 +0800 CST}

**Comment by lunny** [comment]
This is the behaviour by design.
