### ISSUE TITLE
engine.Query 返回 []map[string][]byte ???

### ISSUE THREAD

**Issue by wulove** [go-xorm/xorm#132]
能否增加另一个函数返回[]map[string]interface{},  有时（在不知道数据表中列数据类型的时候）会在查询结果后使用switch type断言来转换数据，而现在这种engine.Query 返回 []map[string][]byte ???返回无法做到

**Comment by mingpen** [comment]
@lunny  这个ScanMap不好使，interface{}里面还是存放的 []byte

**Comment by lunny** [comment]
嗯。因为mysql的驱动返回的是[]byte，而xorm没有做处理。
