### ISSUE TITLE
how can i do this operate, `update table set col1=col1+?,col2=col2+?`

### ISSUE THREAD

**Issue by fangdingjun** [go-xorm/xorm#1322]
how can i do this operate, `update table set col1=col1+?,col2=col2+?`

if I do this, it will cause race condition on multi thread update same row 

    row := Balance{ID:1}
    session.Get(&row)
    session.Table(balance).ID(row.ID).Update(map[string]int{"col1":row.Col1+3,"col2":row.Col2+5})

**Comment by lunny** [comment]
```Go
session.ID(row.ID).Incr("col1",3).Incr("col2", 5).Update(new(Balance))
```

**Comment by fangdingjun** [comment]
Thank you.
