### ISSUE TITLE
db.ping() error invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by myansenr** [go-xorm/xorm#1323]
here is my error

[xorm] [info]  2019/06/12 11:14:33.164535 PING DATABASE mysql
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x76093f]

goroutine 1 [running]:
github.com/go-xorm/xorm.(*Engine).DriverName(...)
        /home/nakama/Documents/go/pkg/mod/github.com/go-xorm/xorm@v0.7.1/engine.go:142
github.com/go-xorm/xorm.(*Session).Ping(0xc0002f1b48, 0x0, 0x0)
        /home/nakama/Documents/go/pkg/mod/github.com/go-xorm/xorm@v0.7.1/session_schema.go:21 +0x3f
github.com/go-xorm/xorm.(*Engine).Ping(0x0, 0x0, 0x0)
        /home/nakama/Documents/go/pkg/mod/github.com/go-xorm/xorm@v0.7.1/engine.go:325 +0xc5
main.main()
        /home/nakama/Documents/go_module/go-nsq-redis/main.go:104 +0x78d
exit status 2

here in my code 

`package main

import (
	"fmt"
	"log"
	"os"
	"regexp"
	"time"

	_ "github.com/go-sql-driver/mysql"
	"github.com/go-xorm/core"
	"github.com/go-xorm/xorm"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"github.com/youcandoit95/go-nsq-redis/services"
	"gopkg.in/go-playground/validator.v9"
)

type (
	SecureConfigAPI struct {
		XSSProtection         string
		ContentTypeNosniff    string
		XFrameOptions         string
		HSTSMaxAge            int
		ContentSecurityPolicy string
	}
)

var engine *xorm.Engine

func init() {
	

	// START - DATABASE PREPARATION
	MYSQL_DATABASE_DBNAME := "mydb"
	

	engine, err := xorm.NewEngine("mysql", ""+os.Getenv("MYSQL_DATABASE_USER")+":"+os.Getenv("MYSQL_DATABASE_PASSWORD")+"@tcp("+os.Getenv("MYSQL_DATABASE_HOST")+":"+os.Getenv("MYSQL_DATABASE_PORT")+")/"+MYSQL_DATABASE_DBNAME+"?charset=utf8&parseTime=true&timeout=8s&readTimeout=8s&writeTimeout=8s")
	nc := 3 // Increase if needed.
	engine.SetMaxOpenConns(nc)
	engine.SetMaxIdleConns(nc)
	engine.SetConnMaxLifetime(time.Second * 3)
	engine.SetMapper(core.GonicMapper{})

	err_db_connect := engine.Ping()
	if err_db_connect != nil || err != nil {
		fmt.Println(err_db_connect)
		log.Fatal("Error init database")
	}
	// END - DATABASE PREPARATION
}

func (cv *CustomValidator) Validate(i interface{}) error {
	return cv.validator.Struct(i)
}

func main() {
	e := echo.New()

	// START - MIDDLEWARE
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())
	e.Use(middleware.RequestID())
	e.Use(middleware.GzipWithConfig(middleware.GzipConfig{
		Level: 7,
	}))

	//CORS
	e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins: []string{"*"},
		AllowMethods: []string{echo.GET, echo.POST},
	}))
	// END - MIDDLEWARE

	// START - VALIDATOR
	validator := validator.New()
	validator.RegisterValidation("alphaNumeric", Is_alphaNumeric)

	e.Validator = &CustomValidator{validator}
	// END - VALIDATOR

	// START - ROUTER
	// e.POST("/", services.Healthcheck(engine))
	e.POST("/getListUser", services.GetListUser(engine))

	engine.Ping()`  this line got error

please help

**Comment by lunny** [comment]
`engine is nil`
