### ISSUE TITLE
problem xorm generate SQL stmt with WHERE when column name is SQL keyword

### ISSUE THREAD

**Issue by huanjinzi** [go-xorm/xorm#1324]
xorm生成的SQL语句：
```
SELECT `Id`, `Index`, `Platform` FROM `recommend` WHERE Index=? AND Platform=? LIMIT 1[1 1]
```
` WHERE Index=? AND Platform=?`，

* 正确 \`Index\`
* 错误 Index，没有(`)
>Index为关键字，所以SQL执行时候会有语法错误

**Comment by lunny** [comment]
Could you give your code here?

**Comment by huanjinzi** [comment]
@lunny 
when I execute code below:
```
engine := this.GetReadEngine()
engine.Where(query)
```
`xorm` will generate SQL statement with `WHERE`,in `WHERE` sub statement,column name don't quoted by **(`)**.

when column name is SQL keyword,such as `SELECT`、`INDEX`, SQL statement execute with sytax error!

**Comment by lunny** [comment]
How is the `query`'s struct's definition?

**Comment by huanjinzi** [comment]
model struct
```go
type Recommend struct {
	Id         int       `xorm:"not null pk autoincr comment('') INT(11)"`
	Index      int       `xorm:"not null comment('') INT(11)"`
	Platform   int       `xorm:"not null comment('') INT(11)"`
}
```
```go
var r *Recommend
var query = map[string]interface{}{}
query["Platform"] = 1
query["Index"] = 1

engine := this.GetReadEngine()
engine.Where(query).Get(r)
```
execute above code, will see from `xrom` debug log:
```sql
SELECT `Id`, `Index`, `Platform` FROM `recommend` WHERE Index=? AND Platform=? [1 1]
```

because `Index` is SQL keyword, above SQL statement has syntax error.

when use:
```go
query["`Platform`"] = 1
query["`Index`"] = 1
```
`xorm` SQL debug log is:
```sql
SELECT `Id`, `Index`, `Platform` FROM `recommend` WHERE `Index`=? AND `Platform`=? [1 1]
```
it works.

**Is this a problem?**
