### ISSUE TITLE
Link in README.md is not available

### ISSUE THREAD

**Issue by tommy-sho** [go-xorm/xorm#1328]
## Problem
I got a 404 error when I tried to visit to Manual page in Document from the README link.
And `https://xorm.io/en/` is also unavailable, that loop redirecting.
![image](https://user-images.githubusercontent.com/37259600/59590667-8bfee280-9127-11e9-97f2-c74a6c844747.png)

**Comment by lunny** [comment]
It has been fixed. Thanks for your report.
