### ISSUE TITLE
怎么忽略结构体中一些字段

### ISSUE THREAD

**Issue by button-chen** [go-xorm/xorm#1329]
你好： 比如我数据库表有字段 A,B,C ,   然后我的结构体是
type Ty strcut {
A int
B int
C int
D int
}
我想查询的时候忽略D字段改怎么做？ 

我想这个功能是有用的， 所以这样修改：
ormTagStr := tag.Get(engine.TagIdentifier)
if ormTagStr == "ignore" {
	continue
}
就是标签为 ： `xorm:"ignore"` 的字段忽略掉。 你看可以吗  如果可行我可以提一个pr  谢谢

**Comment by lunny** [comment]
`xorm:"-"`

Please see http://gobook.io/read/github.com/go-xorm/manual-zh-CN/chapter-02/4.columns.html

**Comment by button-chen** [comment]
非常感谢
