### ISSUE TITLE
Can xorm supports batch query?

### ISSUE THREAD

**Issue by talexu** [go-xorm/xorm#1332]
Hi,

I am wondering if xorm supports batch query for large result?
In Rails, the batch query is like the following:

```
Model.find_each do |item|
   # item is corresponding to a row
end
```
What the above code doing is fetching rows in batch like:

```
SELECT * FROM models OFFSET 0 LIMIT 500
SELECT * FROM models OFFSET 500 LIMIT 500
SELECT * FROM models OFFSET 1000 LIMIT 500
SELECT * FROM models OFFSET 1500 LIMIT 500
...
```
Is this kind of query supported in xorm? It is very useful when there is a large amount of response.

**Comment by lunny** [comment]
```go
engine.BufferSize(500).Iterate(func(i int, bean interface{})error{
})
```

**Comment by talexu** [comment]
> ```go
> engine.BufferSize(500).Iterate(func(i int, bean interface{})error{
> })
> ```

Thank you @lunny !
