### ISSUE TITLE
Why xorm only call ModifyColumnSql() on varchar or text columns when using db.Sync2() ?

### ISSUE THREAD

**Issue by giter** [go-xorm/xorm#1336]
See code:  https://github.com/go-xorm/xorm/blob/c9b14f9487006ec5f7638cd5f08d2c988b0ebd76/session_schema.go#L290-L325

Any technical reasons?

**Comment by lunny** [comment]
I haven't found a safe way to convert other types columns

**Comment by giter** [comment]
Totally there should not be so unsafe.  And we should be able to migrate database changes on our own.

**Comment by lunny** [comment]
Please feel free to reopen it.

**Comment by giter** [comment]
Yeah cool, but we've cloned and add this feature on our own repository
