### ISSUE TITLE
go.mod error

### ISSUE THREAD

**Issue by moggle-mog** [go-xorm/xorm#1340]
go get -u gitea.com/xorm/core
go: gitea.com/xorm/core@v0.6.3: parsing go.mod: unexpected module path "xorm.io/core"
go get: error loading module requirements

**Comment by lunny** [comment]
core has been moved to xorm.io/core, you could use `go get -u xorm.io/core`

**Comment by moggle-mog** [comment]
```bash
go get -u xorm.io/xorm
go: finding xorm.io/xorm v0.7.3
go: xorm.io/xorm@v0.7.3: parsing go.mod: unexpected module path "github.com/go-xorm/xorm"
go get: error loading module requirements
```

**Comment by moggle-mog** [comment]
> core has been moved to xorm.io/core, you could use `go get -u xorm.io/core`

using `xorm.io/core ` is work! Another question: `xorm.io/xorm`

**Comment by moggle-mog** [comment]
> ```shell
> go get -u xorm.io/xorm
> go: finding xorm.io/xorm v0.7.3
> go: xorm.io/xorm@v0.7.3: parsing go.mod: unexpected module path "github.com/go-xorm/xorm"
> go get: error loading module requirements
> ```

use `github.com/go-xorm/xorm` is work!
Thanks!

**Comment by moggle-mog** [comment]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/11258254/60398105-16632f80-9b87-11e9-835c-aafd3aaf1f17.png">

**Comment by ttsszzyy** [comment]
I have the same problem?

**Comment by ttsszzyy** [comment]
![image](https://user-images.githubusercontent.com/9651736/60935966-2b199300-a2fe-11e9-9a0d-b36cc42fa376.png)

**Comment by lunny** [comment]
github.com/go-xorm/core -> xorm.io/core
github.com/go-xorm/builder -> xorm.io/builder

**Comment by ttsszzyy** [comment]
Thanks very much!

**Comment by qq737310694** [comment]
> github.com/go-xorm/core -> xorm.io/core
> github.com/go-xorm/builder -> xorm.io/builder

how can I use this? Can you show me? thanks

**Comment by kylebrandt** [comment]
In my situation this was an indirect dependency, so changing the name wasn't really an option.

The following got me past this in my `go.mod`, may be an abuse of what `require` is meant for - I have no idea:

```
module foo/foo/foo

replace github.com/go-xorm/core => xorm.io/core v0.6.2

replace github.com/go-xorm/xorm => xorm.io/xorm v0.7.0

go 1.12
```

**Comment by lunny** [comment]
Did that work for you?
