### ISSUE TITLE
逆向时 DECIMAL 映射成string了

### ISSUE THREAD

**Issue by ycc297876771** [go-xorm/xorm#1341]
SkuPrice   string     `json:"sku_price" xorm:"not null default 0.00 comment('单价') DECIMAL(10,2)"`
VipPrice    string    `json:"vip_price" xorm:"not null default 0.00 DECIMAL(10,2)"`

使用reverse逆向时.....如上~

**Comment by lunny** [comment]
I think you should report this issue on https://gitea.com/xorm/cmd .

**Comment by ycc297876771** [comment]
> I think you should report this issue on https://gitea.com/xorm/cmd .

thank you!
