### ISSUE TITLE
Sync2 does not delete abandoned columns

### ISSUE THREAD

**Issue by TheCGDF** [go-xorm/xorm#1361]
Before:
```
type User struct{
    Name string `xorm:"notnull"`
    Sex string `xorm:"notnull"`
}
```
After:
```
type User struct{
    Name string `xorm:"notnull"`
}
```
`Sync2` will not delete `Sex` column, and it will be impossible to insert any row because `sex` is `notnull`.

**Comment by lunny** [comment]
@TheCGDF yes, this is by design. It will show warning logs. And you have to drop the columns use mysql client or other tools.
