### ISSUE TITLE
How to define a virtual column?

### ISSUE THREAD

**Issue by TheCGDF** [go-xorm/xorm#1369]
I want to query like this:
```
select
	(select count(*) from table1 where ...) as virtual,
	* 
from Table2
```
`virtual` is always generated temporarily.

My current design is:
```
type Table2 struct {
	Id      int64
	Name    string
	Virtual string `xorm:"<-"`
}

var tables []Table2
db.Select("(select count(*) from table1 where ...) as virtual, *").Find(&tables)
```

But when I use `Sync2`, xorm will create `virtual` column.
How to avoid creating `virtual` column?

**Comment by TheCGDF** [comment]
Is there any instant solution like
`
type Table2 struct {
	Id      int64
	Name    string
	Virtual string `xorm:"as( (select count(*) from table1 where ...) "`
}
`
to solve this problem?

**Comment by lunny** [comment]
I think I will make `<-` not create column but that will break the compatible with before. Currently, you have to use two structs to do that.

```
type Table struct {
	Id      int64
	Name    string
}

type Table2 struct {
      Table `xorm:"extends"`
     Virtual string
}
```

**Comment by TheCGDF** [comment]
anticipated
