### ISSUE TITLE
hit cache isn't reset Session.statement

### ISSUE THREAD

**Issue by xux1217** [go-xorm/xorm#1376]
When I use cache to get and find operation, if hit the data, the statement isn't reset, and then I can't use this session for other operations.

I read the source code, when not hit data, xorm would call "session.queryRows", and this function call the "resetStatement" function to reset the statement.

**Comment by lunny** [comment]
@xux1217 I think #1375 fixed this?

**Comment by xux1217** [comment]
yep, the bug has fixed, thanks.
