### ISSUE TITLE
同步表时出现了一个错误:"Unknown colType: regclass"

### ISSUE THREAD

**Issue by githubyb** [go-xorm/xorm#1377]
之前一直都是没有问题的,在使用了pathman这个pg插件后engine.Sync2()这个方法会报一个"Unknown colType: regclass"的错误,看了一下pathman这个插件会在我们的数据库下创建好几张表,其中有一张表的列类型是"regclass",按道理这个表不是我要同步的表,不应该报错才对

**Comment by githubyb** [comment]
追踪发现是dialect_postgres.go文件的1041行报的错,此时col.SQLType.Name是"REGCLASS"
然而core.SqlTypes这个map里是没有这个键的,因此就报错了,直接return
这个要怎么改呢?
`if _, ok := core.SqlTypes[col.SQLType.Name]; !ok {
	return nil, nil, fmt.Errorf("Unknown colType: %v", dataType)
}`

**Comment by lunny** [comment]
I think we should support user-define column types.

**Comment by githubyb** [comment]
Thank you for your attention
I found someone saying that regclass is an alias for oid datatype,but I don't know what this means.

**Comment by smilucky** [comment]
遇到同样的问题，急需解决，为了避免这个错误去掉同步后遇到了更大的升级失败问题。有解决deadline吗？
