### ISSUE TITLE
xorm does not support struct inherited?

### ISSUE THREAD

**Issue by focusonline** [go-xorm/xorm#1390]
for example,

```
type a struct  {
Id int64 `orm:"pk"
}
type B struct {
a
UserName string `orm:"column:user_name"`
}

```
func (engine *Engine) mapType(v reflect.Value) (*core.Table, error) {
there are some common fields for many tables like id or create_time and so forth.
but common fields in a hidden struct because it can not be used by others.
when using B to query, the func mapType will raise error at engine.go:1021
`if _, ok := fieldValue.Addr().Interface().(core.Conversion); ok {`
will this be fixed to support inheritance for common fields?

I added some code to skip processing hidden properties and error disappeared,
but it can not find common fields as well, always tells me no primiary key..

for this issue, I suggest strongly to refer to other ORM framework go-pg, it is awesome and perfect to handle this complicated situation. I really think go-pg is the best ORM tool although it is for postgresql only.

**Comment by lunny** [comment]
type A struct  {
Id int64 `orm:"pk"
}
type B struct {
A `xorm:"extends"`
UserName string
}

**Comment by focusonline** [comment]
> ```go
> type A struct  {
> Id int64 `orm:"pk"
> }
> type B struct {
> A `xorm:"extends"`
> UserName string
> }
> ```

I tried, but it does not work. it still tells me no primary keys, that means ID defined in parent struct can not be found.
here is another issue.

```
type B struct {
   A `xorm:"extends"`
   tableName struct{} `other tags`
}
```
if I have some unexported special properties in struct,  for example, go-pg needs it to match tag as table name, but xorm always failed for it, is there any way to avoid such special case? anyway, basically there are some unexported properties in struct usually. xorm should not take care of unexported properties unless they have xorm tag defined.

thank you for your help.

**Comment by lunny** [comment]
You should keep first character of field upper. The tag should be `xorm:"pk"` not `orm:"pk"`

**Comment by focusonline** [comment]
orm tag is just a typo, same result with correct spelling.
```
// Common 公共字段
type Common struct {
	ID      int64  `xorm:"pk" gorm:"primary_key" sql:",pk" json:"id,omitempty"`
	Keyword string `sql:"-" json:"keyword,omitempty"`
}
type User struct {
   Common `xorm:"extends"`
   UserName string
   tableName     struct{}   `sql:"users"` // here is for go-pg table name only
}
```
above is my code,  1. tableName will trap the reflection of mapping xorm column type,  2.No matter the common is capitalized or not, xorm can not find parent property if parent is not a table just only collection of common fields. 
maybe you could show me more examples? thanks

**Comment by lunny** [comment]
Please feel free to reopen it.
