### ISSUE TITLE
执行多条sql报错

### ISSUE THREAD

**Issue by wangzd1** [go-xorm/xorm#1400]
Exec(`update tb_order_item set height='{"h1":1400,"h2":1000,"h":2400}',width='{"w1":650,"w2":1350,"w":2000}',weight=16.85,price=168.30,num=1 where id='XCA15662901114450';update tb_order_item set height='{"h1":1400,"h2":1000,"h":2400}',width='{"w1":650,"w2":1750,"w":2400}',weight=24.19,price=241.90,num=1 where id='XCA15662901114451';`)

执行两条sql报错。

**Comment by lunny** [comment]
What's the error? Please give more details

**Comment by wangzd1** [comment]
![image](https://user-images.githubusercontent.com/23433396/63396445-a9874b80-c3f9-11e9-9567-80aca3a0d53e.png)

**Comment by wangzd1** [comment]
有执行多条sql的例子吗

**Comment by lunny** [comment]
You should invoke `Exec` twice.

**Comment by wangzd1** [comment]
ok,thanks.
