### ISSUE TITLE
go mod download get stuck at xorm.io/core

### ISSUE THREAD

**Issue by Revolution1** [go-xorm/xorm#1419]
I use a Dockerfile to build my code.

In order to speedup the build process,
I use these command to cache the dependencies

```dockerfile
FROM golang
COPY go.mod go.sum .
RUN go mod download
COPY . .
RUN go build
```
But, every time when I need to download the deps, I get stuck at xorm.io/core while other libraries went smoothly.

output like this
```
go: finding xorm.io/builder v0.3.5
go: finding xorm.io/core v0.7.0
```

Don't know why.

btw: Why put `core` to `xorm.io` in the first place?

**Comment by Revolution1** [comment]
I see...
You put this project on gitee.com and some how the `xorm/core` of it have pretty slow net connection.

My local ISP is "SINGNET SingNet, SG"

**Comment by lunny** [comment]
@Revolution1 Not gitee.com, it's in https://gitea.com/xorm/core. It should be a network problem. For a speed up, I think use a goproxy is a better choice and will keep that more stable.
