### ISSUE TITLE
undefined: builder.StringBuilder

### ISSUE THREAD

**Issue by stubbornTanzhe** [go-xorm/xorm#1430]
`github.com/go-xorm/xorm@v0.7.6/engine.go:193:9: undefined: builder.StringBuilder`  
it seems that xorm used `https://gitea.com/xorm/builder` not `https://github.com/go-xorm/builder`  
and it be modifed 19 hours ago.   
so pls fix it asap,so mush 3ks!

**Comment by uSmile-Y** [comment]
I had the same problem.

**Comment by lunny** [comment]
github.com/go-xorm/xorm@v0.7.6 requires `xorm.io/builder v0.3.5` which haven't remove StringBuilder. Could you confirm you are using `xorm.io/builder v0.3.5`.

**Comment by lunny** [comment]
Or you can upgrade xorm to v0.7.7
