### ISSUE TITLE
建议增加函数式定义表特殊连击神技..

### ISSUE THREAD

**Issue by insionng** [go-xorm/xorm#16]
Define(table).PK("id").Col("college1","student1","college2","student2").Type("string").Col("old").Type("int64")

Define(table).PK(id).Str(colLen,f1,f2,f3).Int(colLen, f5, f6).Index(f1, f2).UI(f3,f2)

**Comment by lunny** [comment]
@admpub，你要实现这个吗？

**Comment by lunny** [comment]
暂时先关闭，如果有需要再开。
