### ISSUE TITLE
对于ShowSQL的建议

### ISSUE THREAD

**Issue by ohohco** [go-xorm/xorm#160]
当xorm开启debug模式后，打印的sql的针对全局的，即凡是与数据库打交道了就会打印sql。
这种有点不友好的是，对于web开发，如果有多个请求，比如包括查询多条记录，或者单条记录。
我需要找某单条记录的打印时就比较麻烦。
建议可开启局部的debug模式

**Comment by lunny** [comment]
目前可通过engine.ShowSQL(true or false)来开启和关闭。
