### ISSUE TITLE
sqlite3 - database is locked error message

### ISSUE THREAD

**Issue by compressed** [go-xorm/xorm#161]
When running gogs with sqlite3, the method:

``` go
func (session *Session) Iterate(bean interface{}, fun IterFunc)
```

around line 901 in session.go is returning an error that the database is locked.

This method seems to initiate the `UpdateHookTask` method (line 232 in models/webhook.go for gogs), which subsequently fails and the task is not updated. The database is not locked after the command fails.

Steps to replicate:
1. Use sqlite as backend for gogs
2. Add webhook to repo
3. Commit to repo
4. Look in log for database locked message.

Trying with MySQL, I'm not able to replicate the problem.

**Comment by lunny** [comment]
Is this still a problem?

**Comment by Unknwon** [comment]
@lunny SQLite3 cannot do session and global x at same time for same table, different tables are OK. Based on my experiences.

**Comment by stevenh** [comment]
Seeing this here as well, our little app has multiple goroutines all running queries and it often fails with "database is locked" :(

we're running with:
```go
db, err := sql.Open("sqlite3", "test.db?cache=shared&mode=rwc")
```

```sqlite
PRAGMA journal_mode = WAL;
PRAGMA synchronous = NORMAL;
```

**Comment by wangtao3133** [comment]
it  is  great

**Comment by lunny** [comment]
Please follow https://github.com/mattn/go-sqlite3/issues/39's comments to resolve the problem.
