### ISSUE TITLE
关于查询后排序条件的bug

### ISSUE THREAD

**Issue by mu2611** [go-xorm/xorm#162]
Engine.Table("topic").Where("topic.nid <> 99 and topic.pid=? or topic.id=?", pid, pid).Limit(limit, offset).Asc("topic.id").Join("LEFT", "user", "user.id = topic.uid").Find(tps)

在mysql的环境下，上面这个查询的Asc里面的参数被转成下面的这个order by 有问题了。。。不应该带那两个单引号的？？？还有默认不填表名直接Asc("id")也会报错。

SELECT * FROM `topic` LEFT JOIN user ON user.id = topic.uid WHERE topic.nid <> 99 and topic.pid=? or topic.id=? ORDER BY `topic.id` ASC [args] [5 5]

**Comment by lunny** [comment]
此问题应该已解决，如有问题，请再重开。
