### ISSUE TITLE
Is it support Oracle now?

### ISSUE THREAD

**Issue by ZetaChow** [go-xorm/xorm#164]
I found goracle_driver.go and others file look like support for Oracle, then I had install oci8 and create engine:
    engine, err := xorm.NewEngine("oci8", "name/password@127.0.0.1:1521/orcl")
Successful.
but , I use err := engine.CreateTables(new(MyUser))
return a error  "ORA-00922: missing or invalid option"
I have seen the generated SQL statements, that is not the Oracle SQL statements.

Is it support Oracle now?
If not , when will?

**Comment by mkozjak** [comment]
Any news on the support of that driver now?

**Comment by lunny** [comment]
There is no news about this issue. We currently have no oracle environment to continue the work. Since in fact adding an oracle dialect is easy for xorm.

**Comment by lunny** [comment]
There is an experiment support for oracle now. I will close this and you can reopen it if you have further problem.

**Comment by shawnye** [comment]
I've test for `oci8`:
change Parse() in `%GOPATH%\src\github.com\go-xorm\xorm\dialect_oracle.go`
to support `dataSourceName=user/password@sic` as oci8 required:
<pre>
dsnPattern := regexp.MustCompile(
		`^(?P<user>.*)\/(?P<password>.*)@` + // user:password@ 
			`(?P<dbname>.*)`) // dbname
</pre>

well 
<pre>
	os.Setenv("NLS_LANG", "AMERICAN_AMERICA.UTF8") // SIMPLIFIED CHINESE_CHINA.ZHS16GBK  AMERICAN.ZHS16GBK
	engine, err = xorm.NewEngine("oci8", "user/pwd@sid")
       //it will be ok is your oracle TNS work well.
</pre>
