### ISSUE TITLE
sqlserver 数据字段为varchar查询不到数据问题

### ISSUE THREAD

**Issue by muei** [go-xorm/xorm#170]
如果sqlserver的某数据字段为varchar类型，那么在engine.Find(&xxx)会查不到数据。
当然你将数据库字段改为nvarchar问题就解决了，但是很多时候 数据库字段不是你想改就能改。
然后我想是不是因为查询时要加`N`的问题，比如select \* from t where clo=N'xxx'.嗯！用engine.Query("your sql"),your sql加不加N都能得到数据，那么问题来了。这是为什么了。

**Comment by lunny** [comment]
Closed since I cannot reproduce this now. Please feel free to reopen it.
