### ISSUE TITLE
exec执行很慢

### ISSUE THREAD

**Issue by decker502** [go-xorm/xorm#172]
执行简单的select，返回很慢，将近2秒。通过tcpdump抓包，mysql返回是毫秒级，时间都去哪了

**Comment by nashtsai** [comment]
@decker502 how is this a bug? the 1st sql doesn't have limit clause which took 1s to return results but there is no information how many records has been returned?

**Comment by lunny** [comment]
I just close this issue here since we cannot find the problem. If you have more infomation, please reopen this issue.
