### ISSUE TITLE
一个表 是否可以使用 Join 两次？

### ISSUE THREAD

**Issue by fengcen** [go-xorm/xorm#186]
type Message struct {
	    Id 			int64		`xorm:"int(11) pk autoincr"`
	    Title 		string		`xorm:"varchar(100) notnull"`
	    Content 	string		`xorm:"text notnull"`
	    Uid 		int64		`xorm:"int(11) notnull"`
	    ToUid 		int64		`xorm:"int(11) notnull"`
	    CreateTime 	time.Time	`xorm:"datetime notnull created"`
    }

    type MessageExtend struct {
	    Message			`xorm:"extends"`
	    User			`xorm:"extends"`
	    ToUser	User	`xorm:"extends"`
    }

期望代码：

    list := make([]MessageExtend, 0)
    err := db.Table("message").Join("LEFT", "user", "user.uid=message.uid").Join("LEFT", "user", "user.uid=message.to_uid").Where("message.uid="+strconv.FormatInt(uid, 10)).Find(&list)

是否可以像上面这样使用两次 Join 相同的表？

**Comment by li76168** [comment]
請問這功能實現了嗎? 覺得非常需要 謝謝

**Comment by lunny** [comment]
目前还没实现。我看下实现难度。

**Comment by lunny** [comment]
配合Alias是可以的。
```Go
list := make([]MessageExtend, 0)
err := db.Table("message").Join("LEFT", []string{"user", "sender"}, "sender.uid=message.uid").Join("LEFT", []string{"user", "receiver"}, "receiver.uid=message.to_uid").Where("message.uid="+strconv.FormatInt(uid, 10)).Find(&list)
```
