### ISSUE TITLE
软删除 deleted 和 多表 Count 方法的问题，ambiguous

### ISSUE THREAD

**Issue by fengcen** [go-xorm/xorm#189]
使用 软删除后，对多表进行 Join 和 Where 方法，然后对单表使用 Count，会出现 deleted_at 的 ambiguous sql错误

代码如下：

    count, err := db.Table("history").Join("LEFT", "resource", "resource.rid=history.rid").Join("LEFT", "user", "user.uid=history.uid").Where(where).Count(new(History))

**Comment by nashtsai** [comment]
@fengcen I cannot tell what is the variable "where" contents from your example code

**Comment by fengcen** [comment]
@nashtsai where = “history.deleted_at > '0000-00-00 00:00:00'"

**Comment by lunny** [comment]
This is a bug in session.go#1145

**Comment by lunny** [comment]
```Go
type History struct {
	Rid       int64
	Uid       int64
	DeletedAt time.Time `xorm:"deleted"`
}

type Resource struct {
	Rid int64
}

type NewUser struct {
	Uid int64
}

func (NewUser) TableName() string {
	return "user"
}

func joinCount2(engine *xorm.Engine, t *testing.T) {
	err := engine.Sync2(new(History), new(Resource), new(NewUser))
	if err != nil {
		t.Error(err)
		panic(err)
	}

	var where = "history.deleted_at > '0000-00-00 00:00:00'"
	count, err := engine.Table("history").Join("LEFT", "resource", "resource.rid=history.rid").Join("LEFT", "user", "user.uid=history.uid").Where(where).Count(new(History))
	if err != nil {
		t.Error(err)
		panic(err)
	}
	fmt.Println(count)
}
```
I have tested it and not found issue. Maybe it has been fixed sometime.
I will close this issue.
