### ISSUE TITLE
mssql 对应数据库uniqueidentifier类型（UUID）

### ISSUE THREAD

**Issue by llearn** [go-xorm/xorm#190]
使用github.com/denisenkom/go-mssqldb 操作mssql；
数据库里面定义好的Id类型是uniqueidentifier，如下：
Id  uniqueidentifier  
对应的实体类型如下：
Id          string    `xorm:"'Id' pk uuid notnull"`

取出来的值Id 是"\ufffdt\ufffd\ufffdI^h@\ufffd\ufffdL;pvV7"
这个应该是对应的二进制值。
怎么取到对应uuid的string表示？

**Comment by p581581** [comment]
請問MSSQL UUID還有在更新嗎

**Comment by p581581** [comment]
@lunny I simply add UniqueIdentifier type in core/types.go. Maybe it could fix this bug. See [https://github.com/go-xorm/core/pull/38](https://github.com/go-xorm/core/pull/38)

**Comment by miffa** [comment]
use  []byte

**Comment by lunny** [comment]
So this is closed by https://github.com/go-xorm/core/pull/38
