### ISSUE TITLE
datetime字段 需要插入null，默认插入的不是 null

### ISSUE THREAD

**Issue by fengcen** [go-xorm/xorm#191]
字段定义：

    DeleteTime 		time.Time	`xorm:"datetime null"`

代码：

    _, err := db.Insert(resource)

生成的sql：

    INSERT INTO `resource` (`uid`, `title`, `intro`, `cover`, `status`, `comment_status`, `views`, `comment_num`, `note_num`, `rating`, `file_status`, `order_value`, `top`, `main_fid`, `access`, `password`, `create_time`, `update_time`, `lang`, `type`, `delete_time`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [args] [1 title intro  0 1 0 0 0 0  0 0 0 public  2015-01-04 11:25:35 2015-01-04 11:25:35 zh-CN  0001-01-01 00:00:00]

请问应该如何操作让null字段默认插入null 而不是 0001-01-01 00:00:00 ？

**Comment by lunny** [comment]
```
db.Omit("delete_time").Insert()
```

**Comment by fengcen** [comment]
好的，谢谢，建议将 omit 的用法在 【更新数据】和【插入数据】的文档中提一下。
