### ISSUE TITLE
panic: reflect: slice index out of range

### ISSUE THREAD

**Issue by blu3gui7ar** [go-xorm/xorm#193]
https://github.com/go-xorm/xorm/blob/master/session.go#L2023

It is dangerous to access  `bean := sliceValue.Index(0).Interface()` without check whether the slice is empty.

```
panic: reflect: slice index out of range

goroutine 16 [running]:
runtime.panic(0x87ada0, 0xc208140410)
        /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
reflect.Value.Index(0x861820, 0xc2081091a0, 0x0, 0x172, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/pkg/reflect/value.go:1008 +0x316
github.com/go-xorm/xorm.(*Session).innerInsertMulti(0xc20811fd40, 0x861820, 0xc2081091a0, 0x172, 0x0, 0x0)
        /home/ec2-user/go/src/github.com/go-xorm/xorm/session.go:2023 +0x20c
github.com/go-xorm/xorm.(*Session).Insert(0xc20811fd40, 0xc208140400, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/ec2-user/go/src/github.com/go-xorm/xorm/session.go:1990 +0x30b
github.com/go-xorm/xorm.(*Engine).Insert(0xc20805a120, 0xc208140400, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/ec2-user/go/src/github.com/go-xorm/xorm/engine.go:1265 +0x9b
```

**Comment by lunny** [comment]
Hi, you are right! I should return an error instead of panic. Thanks!

**Comment by lunny** [comment]
Discuss: if slice is empty, should I return an error or return no error? @blu3gui7ar

**Comment by lunny** [comment]
OK. Then we return an error instead of panic.

**Comment by blu3gui7ar** [comment]
I guess usually the error would be ignored.  To me, I would prefer return no error. 
Call insert will empty collection with nothing happened seems straight forward, and conforms to my expectation. After all, the object in the collection is just a need for implementation. 

With error returned, I need to write more handling code, which is not necessary. Cause the caller should be aware of the empty collection before call.

If error is returned, I would like to suggest well documentation and sample code for this behavior.
```
if rs, err := xxx.Insert(xxxx); err != nil {
     if (empty(xxx) && err == EmptyParamsError){
         //no need to handle
     } else {
         //handle the error
     }
}
```

**Comment by lunny** [comment]
I think your codes could be. It's more simple and efficient.

```Go
if len(xxxx) > 0 {
     if rs, err := xxx.Insert(xxxx); err != nil {
         //handle the error
     }
}
```

**Comment by blu3gui7ar** [comment]
It is OK, but unnatural to me.
An empty array should not be considered as something special.
