### ISSUE TITLE
Uppercase Initialisms get mapped wrong

### ISSUE THREAD

**Issue by phsmit** [go-xorm/xorm#197]
In Go, there seems to be a consensus to keep initialisms upppercase: https://github.com/golang/go/wiki/CodeReviewComments#initialisms

This means that Id is preferably written as ID and HttpServer as HTTPServer.

Could the SnakeMapper be updated to follow the following pattern:
Id -> id
UserId -> user_id
UserID -> user_id
HTTPServer ->  http_server

In other words, if there are multiple uppercase letters, split before the last one in the sequence, unless it is the end of the word.

Also, I'm not sure if xorm does this already, but can ID be recognized as the standard primary key as well.

(if you agree, I am happy to look to the code and make a pr for this)

**Comment by phsmit** [comment]
I made the pr's already, but feel free to ignore them if you feel that xorm should not behave this way.

**Comment by lunny** [comment]
This issue will be closed since we added GonicMapper. If you have any new idea, please discuss here continue.
