### ISSUE TITLE
Mysql 下 group by 之后查询的字段中只能查询group by的字段，不能获得其他该表的字段

### ISSUE THREAD

**Issue by seago** [go-xorm/xorm#199]
err := X.Where(...).Order(...).GroupBy("hid").Find(&ps)
ps[0].Hid == 123

ps[0]中只有Hid的值，木有其他字段的值。

生成sql 对应如下：

select `hid` from p where ... order ... group by hid

**Comment by lunny** [comment]
This change will let postgres panic on tests. So I will reopen this and use a new method to resolve it.

**Comment by lunny** [comment]
```Go
err := X.Cols("").Where(...).Order(...).GroupBy("hid").Find(&ps)
```
I think we should use Cols() to ask to select some columns.
