### ISSUE TITLE
官网的使用手册内容显示有问题

### ISSUE THREAD

**Issue by lxingh** [go-xorm/xorm#204]
Google Chrome ,  IE 11, Firefox 三个里都会显示不全,应该是CSS没调好..

![image](https://cloud.githubusercontent.com/assets/1501974/6131369/499aa9c2-b186-11e4-90b9-e382d0b7dd84.png)

**Comment by lxingh** [comment]
刚找到 http://lunny.gitbooks.io/xorm-manual-zh-cn/ 这个地方的显示是正常的

**Comment by lunny** [comment]
http://gobook.io/read/go-xorm/manual-zh-cn/，在这里也可以。
