### ISSUE TITLE
Session.Update如果传入的bean参数是map，而且有字段tag为version的话，会出错！

### ISSUE THREAD

**Issue by chnykn** [go-xorm/xorm#205]
Session.Update如果传入的bean参数是map，而且有字段tag为version的话，会出错！，因为Column.ValueOfV 一点要FieldByName 找Version那一列的名称的Field，但是map肯定没有，同样在Session当中试图去设置ver+1也同样会出错，我已经做了修改，请老大审核后合并代码吧，

代码基于master的2015.02.12的版本，做了如下修改，行号请参考图片：

 ---------------- column.go ----------------

![1](https://cloud.githubusercontent.com/assets/4152089/6184527/bad968ee-b39d-11e4-9aa2-31a4f36078fc.jpg)
增加部分的代码如下：
```
    if dataStruct.Type().Kind() == reflect.Map {
        var keyValue reflect.Value

        if len(col.fieldPath) == 1 {
            keyValue = reflect.ValueOf(col.FieldName)
        } else if len(col.fieldPath) == 2 {
            keyValue = reflect.ValueOf(col.fieldPath[1])
        }else {
            return nil, fmt.Errorf("Unsupported mutliderive %v", col.FieldName)
        }

        fieldValue = dataStruct.MapIndex(keyValue)
        return &fieldValue, nil
    }
```

 ---------------- session.go  ----------------
![2](https://cloud.githubusercontent.com/assets/4152089/6184543/13426012-b39e-11e4-8c71-afee266d5d2a.jpg)
增加部分的代码如下：
```
        //--->>> added by yangkn 2015.02.11 但是bean的确有可能是map 所以加多一行判断
        if t.Kind() != reflect.Map {
        //---<<<
            verValue.SetInt(verValue.Int() + 1)
        }
···

**Comment by lunny** [comment]
非常不错。如果能够支持Map是非常好的。但是可否fork之后发送pull request？

**Comment by chnykn** [comment]
啊，太麻烦了，老大， 您审核一下，如果觉得代码OK，合并到您代码当中得了

**Comment by lunny** [comment]
。。。这样我没法合并啊。我要测试后才能合并。

**Comment by chnykn** [comment]
既然您在线，我就顺便再提多两个问题：
1、Find方法如果参数给的是map，即 make(map[string]*User)，注意这里的key是string，因为User的定义Id也是string， 但是这样用的话，Find会报错的：panic: reflect.Value.SetMapIndex: value of type int64 is not assignable to type string， 应该是map的方式不支持key为非int类型吧；
2、Insert方法，如果参数我给的是一个对象，而且对象当中有version的tag的话，在Insert之后对象的ver字段是会自动+1的，但是如果参数我给的是一个数字或切片，那么就不自动维护ver了，行为不一致啊

**Comment by lunny** [comment]
嗯。这两个问题我都先记下。

**Comment by chnykn** [comment]
哦 原来是这样才能合并啊，不好意思， 因为我对Github不熟悉，之前只是用这个下载代码，那我研究一下如何fork和pull request

**Comment by lunny** [comment]
好的。先谢谢了！

**Comment by chnykn** [comment]
刚才有错别字： “数字或切片”-> “数组或切片”

**Comment by chnykn** [comment]
一楼当中的 if verValue.Kind() != reflect.Map 应该改为 if t.Kind() != reflect.Map

**Comment by lunny** [comment]
```Go
users := make(Map[string]User)
engine.Find(&users)
```
这个现在解决了。

**Comment by chnykn** [comment]
最开头那个问题还没解决（合并？）

**Comment by lunny** [comment]
那个还没有，你的代码我没法合并啊。行号也没有。

**Comment by chnykn** [comment]
老大， 我更新帖子了，请参考一楼内容，行号在抓图当中能看到

**Comment by lunny** [comment]
插入多条记录的问题，可以新开一个issue，暂时没想到如何做，又能保证效率。

**Comment by chnykn** [comment]
好的
