### ISSUE TITLE
New method for session to rollback if not committed and close

### ISSUE THREAD

**Issue by phsmit** [go-xorm/xorm#206]
In Gogs, we currently have the following pattern a lot:

    sess := x.NewSession()
    defer sess.Close()
    
    // do thing 1
    if err != nil {
        sess.Rollback()
        return err
    }

    // do thing 2
    if err != nil {
        sess.Rollback()
        return err
    }
    
    // repeat couple more times
    
    return sess.Commit()

Having all these Rollbacks in the code makes it a bit messy, plus it is easy to forget.

The following pattern would be nicer:

    sess := x.NewSession()
    defer func() {
        if !sess.IsCommitedOrRollbacked {
            sess.Rollback()
        }
        sess.Close()
    }
    
    // do thing 1
    if err != nil {
        return err
    }

    // do thing 2
    if err != nil {
        return err
    }
    
    // repeat couple more times
    
    return sess.Commit()

It would be nice if xorm would have this anonymous method for us:

    sess := x.NewSession()
    defer sess.RollbackIfNotCommitedAndClose()

Unfortunately the name is ugly, but it shows the intent.

My questions

 - Is there maybe already a method like this that I overlooked?
 - Would it be incorrect to add this behaviour to Close() itself if a session is not an auto-commiting session
 - If you would like to introduce this function, what would be a good name for it?

I am happy to make a PR with this addition, but naming is hard and I think RollbackIfNotCommitedAndClose is a bit long...

**Comment by lunny** [comment]
This code will be ok. No need to add new method.
```Go
var err error
sess := x.NewSession()
defer func() {
    if err != nil {
        sess.Rollback()
    }
    sess.Close()
}()

// do thing 1
if err != nil {
    return err
}

// do thing 2
if err != nil {
    return err
}

// repeat couple more times

return sess.Commit()
```

**Comment by phsmit** [comment]
It is not necessary, but I would be great if xorm would already contain that (here anonymous) function. Especially if you also think this is a good paradigm.

**Comment by Unknwon** [comment]
:+1: add this to xorm

**Comment by lunny** [comment]
Sorry. I don't think a new method is needed.

**Comment by lunny** [comment]
I will resolve this feature on #221. 
I will check if a transaction has been commit or rollback on session.Close() be invoked. If not, I will call rollback.

**Comment by phsmit** [comment]
Perfect, that is great!
