### ISSUE TITLE
Insert对象的数组或切片，而且对象当中有version的tag的字段，在Insert之后vert没有自动+1

### ISSUE THREAD

**Issue by chnykn** [go-xorm/xorm#209]
Insert方法，如果参数我给的是一个对象，而且对象当中有version的tag的话，在Insert之后对象的ver字段是会自动+1的，但是如果参数我给的是一个数组或切片，那么就不自动维护ver了，行为不一致

**Comment by lunny** [comment]
这应该是一个bug。
