### ISSUE TITLE
建议：在session关闭前，增加一个事务检测，默认采用rollback处理

### ISSUE THREAD

**Issue by sunvim** [go-xorm/xorm#221]
之所以提出这个建议，是因为很多新手程序员，在使用xorm的时候由于理解不深刻，自以为NewSession后，加一个session.close，就会关闭数据库连接了！事实上，我们在新的session打开一个事务后，常出现忘记commit或rollback，在这个情况下，session虽关闭了，但连接并没有释放，如此持续下去，应用服务程序最终会出现“无法连接数据库”而终止服务！

因此建议：在session关闭前，增加一个事务检测，如若有事务未commit或rollback操作则默认采用rollback处理

**Comment by lunny** [comment]
For example:
```Go
sess := orm.NewSession()
defer sess.Close()

if err := sess.Begin(); err != nil {
	return err
}

_, err = sess.Id(id).Delete(new(Article))
if err != nil {
	return err
}

err = os.Remove(filepath.Join(articleDir, fmt.Sprintf("%d", id)))
if err != nil {
	return err
}

return sess.Commit()
```

**Comment by Unknwon** [comment]
Very well!

**Comment by Unknwon** [comment]
@lunny I think you need to update https://github.com/go-xorm/xorm/blob/master/xorm.go#L16 as well.

**Comment by lunny** [comment]
You are right. @Unknwon, Have been done.
