### ISSUE TITLE
adjacency list or parent-child tree

### ISSUE THREAD

**Issue by thrisp** [go-xorm/xorm#224]
Perhaps someone can assist, I couldn't find what I'm looking for in the documentation or the tests.

I have one struct:
```
type Node struct {
	Id       int64 `xorm:"pk autoincr"`
	ParentId int64
	Parent   *Node `xorm:"node_id BIGINT"`
        //Children []*Node `xorm:"node_id BIGINT"`
}
```
each node can be attached to other nodes as parent or child; the parent part seems to work here, but I cannot determine how to get a slice of *Nodes. I am guessing I'll need to write something like:

```
func (n *Node) getChildren  (s *xorm.Session) []*Node {
    var nodes []*Node
    err := s.Where("parent_id" == n.Id).Find(&nodes)
    return nodes
}
```

but the point is I'm having difficulty about how to catalog & gather relations 1-to-1 seems to work, but I'm having difficulty seeing other relations in the documentation or code, yet.

**Comment by lunny** [comment]
Hi, currently we haven't provide 1-to-N, only 1-to-1. And we encourage you to use join instead relations, you can find the manual on [gobook](http://gobook.io/read/go-xorm/manual-en-us/), and find join section on [How to use join](http://gobook.io/read/go-xorm/manual-en-us/chapter-13/).

**Comment by thrisp** [comment]
ok
