### ISSUE TITLE
Build is breaking

### ISSUE THREAD

**Issue by bhuwan-joshi** [go-xorm/xorm#225]
Hi,
I was trying to do "go get.." xorm. But it is failing with below error:
/Users/bhuwan/Go/src/github.com/go-xorm/core/db.go:360: undefined: reflect.SliceOf
/Users/bhuwan/Go/src/github.com/go-xorm/core/dialect.go:198: method db.dialect.Quote is not an expression, must be called
/Users/bhuwan/Go/src/github.com/go-xorm/core/dialect.go:211: method db.dialect.Quote is not an expression, must be called
/Users/bhuwan/Go/src/github.com/go-xorm/core/type.go:255: t.ConvertibleTo undefined (type reflect.Type has no field or method ConvertibleTo)

Please help me out.

**Comment by lunny** [comment]
```go get -u -v github.com/go-xorm/xorm```

**Comment by bhuwan-joshi** [comment]
Seems i was using the old go version. After upgrading it has build successfully.

**Comment by lunny** [comment]
OK. It's great.
