### ISSUE TITLE
pgsql 删除不了数据，后台有正确的sql输出。版本都是最新的。

### ISSUE THREAD

**Issue by 858806258** [go-xorm/xorm#227]
ids := []int{1,2,3}	
u := new(User)
_, err := engine.In("Id", ids).Delete(u)

[xorm] [info]  2015/03/31 10:18:02.719815 [sql] DELETE FROM "user" WHERE ("Id" I
N ($1)) [args] [52]

**Comment by lunny** [comment]
I will check this.

**Comment by 858806258** [comment]
解决了，原来字段名字要和数据库里面的一样，我写的和struct里面的字段名字一样了。这里把“Id”改成"id"就好了！

**Comment by lunny** [comment]
OK.
