### ISSUE TITLE
Oracle数据库NVARCHAR2类型错误

### ISSUE THREAD

**Issue by ilisin** [go-xorm/xorm#229]
如果数据中已经存在类型为NVARCHAR2的数据表，再调用Sync，追踪到oracle_dialect.go中的GetColumns函数中
    if _, ok := core.SqlTypes[col.SQLType.Name]; !ok {
        return nil, nil, errors.New(fmt.Sprintf("unkonw colType %v %v", *dataType, col.SQLType))
    }
错误

**Comment by lunny** [comment]
fixed by 7fd31fc7e76529b64cba7c91ff8ad0d48bf2b1c1
