### ISSUE TITLE
insertOne 是否考慮改成返回新增Id

### ISSUE THREAD

**Issue by li76168** [go-xorm/xorm#230]
session.go 3103行 
return res.RowsAffected() 改成 LastInsertId()

謝謝

**Comment by lunny** [comment]
如果插入成功，LastInsertId已经赋值回结构体中的ID的值。

**Comment by viney** [comment]
这个确实会让人产生误解
看到注释是:The return parameter is inserted and error

是否要标注下rows affected？

**Comment by lunny** [comment]
注释在哪里？可能是忘记改了。

**Comment by viney** [comment]
https://github.com/go-xorm/xorm/blob/master/session.go#L3193

**Comment by lunny** [comment]
在插入场景下，`inserted == rows affected`， `inserted != last insert id`
