### ISSUE TITLE
建议增加外键约束在tag里面定义

### ISSUE THREAD

**Issue by zileyuan** [go-xorm/xorm#232]
类似sql：alter table SEC_AUTHORITY_RESOURCE add constraint FK_AUTHORITY_RESOURCE1 foreign key (AUTHORITY_ID) references SEC_AUTHORITY (ID);

主要在两个定义好的表格字段之间建立外键，通过sync2的时候可以快速建立！

**Comment by lunny** [comment]
duplicated with #141
