### ISSUE TITLE
运行出现了一些特殊提示，部分能操作数据库

### ISSUE THREAD

**Issue by bkjewlr** [go-xorm/xorm#233]
用无闻老师的例子（https://github.com/Unknwon/go-rock-libraries-showcases/tree/master/lectures/02-xorm ），讲解的原文件。放入GO运行。打开就提示如下信息。数据库操作不能正常运行。
错误信息：
[xorm] [info]  2015/04/19 18:33:14.814907 [sql] SELECT name FROM sqlite_master WHERE type='table' and name = ? and ((sql like '%`id`%') or (sql like '%[id]%')) [account]
[xorm] [info]  2015/04/19 18:33:14.816907 [sql] SELECT name FROM sqlite_master WHERE type='table' and name = ? and ((sql like '%`name`%') or (sql like '%[name]%')) [account]
[xorm] [info]  2015/04/19 18:33:14.817907 [sql] SELECT name FROM sqlite_master WHERE type='table' and name = ? and ((sql like '%`balance`%') or (sql like '%[balance]%')) [account]
[xorm] [info]  2015/04/19 18:33:14.817907 [sql] SELECT name FROM sqlite_master WHERE type='table' and name = ? and ((sql like '%`version`%') or (sql like '%[version]%')) [account]
[xorm] [info]  2015/04/19 18:33:14.817907 [sql] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [account]

操作也会提示：Fail to transfer: UNIQUE constraint failed: account.name 

这是什么出错才会显示这些信息呢？库什么的都是新下载的。。本人环境： win7 X64 go1.42

**Comment by lunny** [comment]
sample1还是sample2？

**Comment by bkjewlr** [comment]
两个都提示啊。
[xorm] [info]  2015/04/22 11:43:25.857052 [sql] SELECT name FROM sqlite_master WHERE type='table' and name = ? and ((sql like '%`id`%') or (sql like '%[id]%')) [account]
2015/04/22 11:43:25 before insert: joe0
[xorm] [info]  2015/04/22 11:43:25.857552 [sql] SELECT name FROM sqlite_master WHERE type='table' and name = ? and ((sql like '%`name`%') or (sql like '%[name]%')) [account]
[xorm] [info]  2015/04/22 11:43:25.858052 [sql] SELECT name FROM sqlite_master WHERE type='table' and name = ? and ((sql like '%`balance`%') or (sql like '%[balance]%')) [account]
[xorm] [info]  2015/04/22 11:43:25.858052 [sql] SELECT name FROM sqlite_master WHERE type='table' and name = ? and ((sql like '%`version`%') or (sql like '%[version]%')) [account]
[xorm] [info]  2015/04/22 11:43:25.858052 [sql] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [account]
这是现在运行的提示。。我又下载了更新了xrom库，还有更新了 liteide x27.2 都是一样的提示。

**Comment by lunny** [comment]
明天我测试下。

**Comment by lunny** [comment]
没有发现此问题。暂时先关闭，如果再发现了可重新开启。
