### ISSUE TITLE
BUG: column 属性中，unique不生效BUG: column 属性中，unique不生效

### ISSUE THREAD

**Issue by erica-zhou** [go-xorm/xorm#239]
struct 定义：
<a href="https://www.flickr.com/photos/99335802@N03/17297873441" title="屏幕快照 2015-04-28 下午4.15.18 by X Monster, on Flickr"><img src="https://farm9.staticflickr.com/8737/17297873441_bc05b76f3a_b.jpg" width="1024" height="161" alt="屏幕快照 2015-04-28 下午4.15.18"></a>

生成的表：
<a href="https://www.flickr.com/photos/99335802@N03/17297873451" title="屏幕快照 2015-04-28 下午4.16.33 by X Monster, on Flickr"><img src="https://farm9.staticflickr.com/8791/17297873451_42efd67bd8_b.jpg" width="1024" height="549" alt="屏幕快照 2015-04-28 下午4.16.33"></a>

**Comment by lunny** [comment]
你的User 的 tag 里面多了个双引号。你用`Desc test`看下。

**Comment by erica-zhou** [comment]
这一次是从文档中copy的例子，但是依然没有在数据库中显示unique

```go
type Test struct {
	Id   int64
	Name string `xorm:"varchar(25) notnull unique 'usr_name'"`
}
```

数据库中的显示如下
```
mysql> show create table test\G
*************************** 1. row ***************************
       Table: test
Create Table: CREATE TABLE `test` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `usr_name` varchar(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
1 row in set (0.00 sec)

+----------+-------------+------+-----+---------+----------------+
| Field    | Type        | Null | Key | Default | Extra          |
+----------+-------------+------+-----+---------+----------------+
| id       | bigint(20)  | NO   | PRI | NULL    | auto_increment |
| usr_name | varchar(25) | NO   |     | NULL    |                |
+----------+-------------+------+-----+---------+----------------+
2 rows in set (0.00 sec)

```

**Comment by lunny** [comment]
Which method did you use? `CreateTables` or `Sync` ? If you use the first, you should call `CreateUniques` also.

**Comment by erica-zhou** [comment]
是即使表本来不存在，也不能使用CreateTables来创建Unique么？那使用sync能自动创建么？

**Comment by lunny** [comment]
`CreateTables`只创建表，`Sync`和`Sync2`是既创建表，又创建索引。

**Comment by rowe0x** [comment]
@lunny 这个方式容易漏，不能也把索引同时加上？
