### ISSUE TITLE
能否将func (session *Session)query2(sqlStr string, paramStr ...interface{}) (resultsSlice []map[string]string, err error) 这个私有方法开放出来？

### ISSUE THREAD

**Issue by WhiteBatman** [go-xorm/xorm#244]
在session.go中有这样一个方法
// =============================
// for string
// =============================
func (session *Session) query2(sqlStr string, paramStr ...interface{}) (resultsSlice []map[string]string, err error) {
    session.queryPreprocess(&sqlStr, paramStr...)

```
if session.IsAutoCommit {
    return query2(session.DB(), sqlStr, paramStr...)
}
return txQuery2(session.Tx, sqlStr, paramStr...)
```

}

能否将这个方法开放出来？

并在engine.go中增加下面这个方法
// Exec a raw sql and return records as []map[string]string
func (engine *Engine) Query2(sql string, paramStr ...interface{}) (resultsSlice []map[string]string, err error) {
    session := engine.NewSession()
    defer session.Close()
    return session.Query2(sql, paramStr...)
}

这样就可以直接使用SQL查询时候使用这个方法了

sql := "select \* from userinfo"
results, err := engine.Query2(sql)
当调用Query时，第一个返回值results为[]map[string]string的形式。

好处是我可以直接转成json表达式，这样出来的json中的值就是我在数据库中存的数据，而不是一个[]byte

会方便很多

**Comment by hzmnet** [comment]
同意

**Comment by lunny** [comment]
可以考虑，不过Query2这个名字不是太好，有什么更好的名字建议？

**Comment by hzmnet** [comment]
还是建议Find 扩展个FindMap    QueryMap

**Comment by lunny** [comment]
```Go
QueryMapInterface
QueryMapString
```
这样吗？FindMap是如何的？

**Comment by hzmnet** [comment]
FindMap 提供在没有结构体的情况下返回[]Map[string]interface{} 数据集使用
FindMap和Find一样使用只是返回数据不一样而已
在没有结构体的情况下，转Json和XML 比较方便 相比[]Map[string][]byte

**Comment by lunny** [comment]
resolved by 5497f76
