### ISSUE TITLE
能否增加一个QueryToJsonStr的方法啊？直接将使用SQL语句查询的结果返回为一个json字符串？

### ISSUE THREAD

**Issue by WhiteBatman** [go-xorm/xorm#245]
能否增加一个QueryToJsonStr的方法啊？直接将使用SQL语句查询的结果返回为一个json字符串？

很多ActiveRecord框架都有类似的方便的方法

我本地自己修改了代码

**Comment by lunny** [comment]
既然encoding/json已经可以把slice, map, struct转为json了，所以xorm不考虑提供这个功能。
