### ISSUE TITLE
开启缓存后，使用Sql（）执行join查询语句报错！！！

### ISSUE THREAD

**Issue by Alex110120** [go-xorm/xorm#248]
c:/go/src/pkg/runtime/panic.c:552 (0x41200e)
	panicstring: runtime·panic(err);
c:/go/src/pkg/runtime/panic.c:466 (0x411c4e)
	panicindex: runtime·panicstring("index out of range");
C:/goworkspace/src/github.com/go-xorm/xorm/session.go:901 (0x5b7bd6)
	(*Session).cacheFind: session.Engine.LogWarn("[cacheFind] cache no hit:", tableName, ides[j])

**Comment by lunny** [comment]
fixed via fb995894f00f1a8f8f013fcaaa500b3546a1ff5d
