### ISSUE TITLE
当struct中除了Id以外的字段值与数据库中的值不一致时，则此Id的记录无法删除

### ISSUE THREAD

**Issue by aminic** [go-xorm/xorm#250]
如有下代码:
dx1 := Department{}
dx1.Name = "add batch depart 1"
dx1.Description = "description"
dx1.PinYinCode = "ABD1"
dx1.DictCode = "00001"
e.ShowSQL = true
e.Id(dx1.Id).Delete(dx1)
会生成SQL:
[xorm] [info]  2015/05/31 19:44:11.083134 [sql] DELETE FROM "department" WHERE "id" = $1 AND "name" = $2 AND "pin_yin_code" = $3 AND "description" = $4 AND "dict_code" = $5 [args] [1 add batch depart 1 ABD1 description 00001]

在这里的条件只是Id，而生成的SQL里面把字段都做条件，当struct中除了Id以外的字段值与数据库中的值不一致时，则此Id的记录无法删除，生成这样就够了:
DELETE FROM "department" WHERE "id" = $1  [args] [1]

**Comment by aminic** [comment]
dx1是有id的，已存在于表中的

**Comment by lunny** [comment]
``go
e.Id(dx1.Id).Delete(new(Department))
```

**Comment by aminic** [comment]
Delete的参数有可能是运行时确定的，所以我现在只能反射创建一个空 struct

**Comment by lunny** [comment]
```Go
e.Id(dx1.Id).NoAutoCondition().Delete(dx1)
```
使用`NoAutoCondition()`可以禁止自动条件。
