### ISSUE TITLE
revel + xorm 卡死了

### ISSUE THREAD

**Issue by baiyuxiong** [go-xorm/xorm#254]
sql := "truncate table users"
_, err := app.Engine.Query(sql)
执行这个SQL，页面完全卡死了，有碰到这个问题的吗？

**Comment by baiyuxiong** [comment]
bug也太多了吧……

helpers.go
函数 func rows2maps
197行for rows.Next()  这里卡死了

**Comment by baiyuxiong** [comment]
执行 
sql := "delete from users"
_, err := app.Engine.Query(sql)
同样会卡死
项目太不成熟了

看了下源码，一个_test.go文件都没有
作者不作测试就把项目放出来，太不负责任了吧？？！！

**Comment by lunny** [comment]
测试文件在 github.com/go-xorm/tests，是一个独立的工程。如果你觉得不成熟，可以不用。@baiyuxiong

**Comment by admpub** [comment]
@baiyuxiong 没有碰到过这个问题，你的users表数据量是不是很大？

**Comment by xormplus** [comment]
sql := "truncate table users"
_, err := app.Engine.Query(sql)

先学习下官方文档，你的truncate语句  用的是Query方法 ，本身 用法就是错误的

**Comment by baiyuxiong** [comment]
我的用法不对，应该是app.Engine.Exec方法，不是Query
Sorry

**Comment by lunny** [comment]
如果没有问题，我先关闭此issue。如果有问题，请重新打开本issue。

**Comment by nashtsai** [comment]
@baiyuxiong which DB driver are you using, in such case I would suggest feedback this problem to driver creator where "truncate" command will fail fast with its Queryer implementation
