### ISSUE TITLE
Why connection changed.

### ISSUE THREAD

**Issue by narita-takeru** [go-xorm/xorm#255]
Hi, there.
I'm using xorm package. It's very fantastic for me.
I have a favor to ask you about xorm.Session.

For example:

```
var session xorm.Session
...DB Setup...

session.Insert(...) // connection A
session.Exec("select last_insert_id() as id") // connection A or connection B
```

I got a different connection when call Exec() after calling Insert().
I guess that the connection shouldn't be changed.

What do you think? 

Please, help me. :D

**Comment by lunny** [comment]
```session``` is also based connection pool. So every command will get a connection from pool not every session.
Of course, you can call ```session.Begin()``` before all commands, to ask transaction, then it will on a connection.

**Comment by narita-takeru** [comment]
Thanks. :)
