### ISSUE TITLE
希望添加Page方法

### ISSUE THREAD

**Issue by zihuxinyu** [go-xorm/xorm#264]
请添加一个方法，
目的是读取数据时更方便，比如取第二页，每页20条 Page(2,20)

func (engine *Engine) Page(pageIndex int, pageSize int) *Session {
	session := engine.NewSession()
	session.IsAutoClose = true
	limit:=pageSize
	start:=(pageIndex-1)*pageSize

	return engine.Limit(limit, start)
}

**Comment by lunny** [comment]
。。。没这个必要吧。自己加下就行了啊。

**Comment by zihuxinyu** [comment]
这个功能还是很方便的。
方便不好么？

**Comment by admpub** [comment]
@zihuxinyu 你可以针对你自己的需要新建一个go文件，自己的扩展代码就放在这个新文件中，这样拉取更新的时候也不会覆盖自己的代码，还是很方便的，我就是这个干的。

**Comment by okliwei** [comment]
可参考 https://github.com/xorm-page/page
