### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by yrmt** [go-xorm/xorm#266]
Hello, I'm trying to package xorm, but I'm getting the following build failure:

env GOPATH=/pkgsrc-work/obj/wip/go-xorm/work:/usr/pkg/gopkg go install -v github.com/go-xorm/xorm/...
github.com/go-xorm/xorm
\# github.com/go-xorm/xorm
/pkgsrc-work/obj/wip/go-xorm/work/src/github.com/go-xorm/xorm/engine.go:1130: cannot use col.Name (type string) as type *core.Column in argument to session.Engine.dialect.IsColumnExist
/pkgsrc-work/obj/wip/go-xorm/work/src/github.com/go-xorm/xorm/mssql_dialect.go:215: cannot use db (type *mssql) as type core.Dialect in argument to db.Base.Init:
	*mssql does not implement core.Dialect (wrong type for IsColumnExist method)
		have IsColumnExist(string, string) (bool, error)
		want IsColumnExist(string, *core.Column) (bool, error)
/pkgsrc-work/obj/wip/go-xorm/work/src/github.com/go-xorm/xorm/mssql_dialect.go:245: undefined: core.Json
/pkgsrc-work/obj/wip/go-xorm/work/src/github.com/go-xorm/xorm/mssql_dialect.go:488: cannot use db (type *mssql) as type core.Dialect in argument to col.String:
	*mssql does not implement core.Dialect (wrong type for IsColumnExist method)
		have IsColumnExist(string, string) (bool, error)
		want IsColumnExist(string, *core.Column) (bool, error)
/pkgsrc-work/obj/wip/go-xorm/work/src/github.com/go-xorm/xorm/mssql_dialect.go:490: cannot use db (type *mssql) as type core.Dialect in argument to col.StringNoPk:
	*mssql does not implement core.Dialect (wrong type for IsColumnExist method)
		have IsColumnExist(string, string) (bool, error)
		want IsColumnExist(string, *core.Column) (bool, error)
/pkgsrc-work/obj/wip/go-xorm/work/src/github.com/go-xorm/xorm/mysql_dialect.go:228: undefined: core.Json
/pkgsrc-work/obj/wip/go-xorm/work/src/github.com/go-xorm/xorm/oracle_dialect.go:509: cannot use db (type *oracle) as type core.Dialect in argument to db.Base.Init:
	*oracle does not implement core.Dialect (wrong type for IsColumnExist method)
		have IsColumnExist(string, string) (bool, error)
		want IsColumnExist(string, *core.Column) (bool, error)
/pkgsrc-work/obj/wip/go-xorm/work/src/github.com/go-xorm/xorm/oracle_dialect.go:525: undefined: core.Json
/pkgsrc-work/obj/wip/go-xorm/work/src/github.com/go-xorm/xorm/oracle_dialect.go:600: cannot use b (type *oracle) as type core.Dialect in argument to col.StringNoPk:
	*oracle does not implement core.Dialect (wrong type for IsColumnExist method)
		have IsColumnExist(string, string) (bool, error)
		want IsColumnExist(string, *core.Column) (bool, error)
/pkgsrc-work/obj/wip/go-xorm/work/src/github.com/go-xorm/xorm/postgres_dialect.go:776: cannot use db (type *postgres) as type core.Dialect in argument to db.Base.Init:
	*postgres does not implement core.Dialect (wrong type for IsColumnExist method)
		have IsColumnExist(string, string) (bool, error)
		want IsColumnExist(string, *core.Column) (bool, error)
/pkgsrc-work/obj/wip/go-xorm/work/src/github.com/go-xorm/xorm/postgres_dialect.go:776: too many errors
*** Error code 2

**Comment by lunny** [comment]
Hi, could you go get -u github.com/go-xorm/xorm first?

**Comment by lunny** [comment]
Please visit https://drone.io/github.com/go-xorm/tests/latest, this is the build and tests of xorm. It's OK. I will close this issue now, if you have any issue, just reopen it.
