### ISSUE TITLE
tag设置默认值为1，struct里面没有指定参数，数据插入的时候值为0

### ISSUE THREAD

**Issue by viney** [go-xorm/xorm#267]
type User struct{
    Id int64 `xorm:"pk autoincr NOT NULL"`
    Name string `xorm:"pk varchar(20)"`
    Status int `xorm:"INT(3) NOT NULL DEFAULT 1"`
}

user:=&User{
    Name: "viney",
}

engine.InsertOne(user)
以上代码只是提供思路
结果status值为0
用的mysql数据库，请问是我写法有误还是存在bug？

**Comment by admpub** [comment]
User中的属性Status是int类型，而该类型的默认值是0，程序无法判断出你对Status值是故意设置为0还是使用的默认0值。

**Comment by viney** [comment]
如果这样的话，我设置默认值的意义就没有了！

**Comment by lunny** [comment]
```Go
engine.Omit("status").InsertOne(user)
```
这样就可以了。因为无法区分你是要插入0，还是没有赋值，所以你需要这样插入默认值。
