### ISSUE TITLE
无法填充反射创建的struct数组

### ISSUE THREAD

**Issue by aminic** [go-xorm/xorm#268]
代码如下：
////////////////////////////////////////////////////////////////////////////////////////
func GET_ALL() {
	dep := Department{}
	depsValue := reflect.MakeSlice(reflect.SliceOf(reflect.TypeOf(dep)), 0, 0)
	deps := depsValue.Interface()
	log.Printf("deps is :%#v", deps)  //输出 deps is :[]models.Department{}

	err = e.Find(&deps)
	if err != nil {
		log.Fatalf("GET_ALL is error : %#v", err) //输出 GET_ALL is error : &errors.errorString{s:"needs a pointer to a slice or a map"}
	}

	log.Printf("deps is : %#v", deps)

	return
}
////////////////////////////////////////////////////////////////////////////////////////
以&传递反射创建的数组无法得到期望结果。

**Comment by wixb50** [comment]
你好，请问这个你是怎么解决的？

**Comment by lunny** [comment]
```Go
deps := depsValue.Addr().Interface()
err = e.Find(deps)
```
