### ISSUE TITLE
struct 与数据库字段不对应的错误提示？

### ISSUE THREAD

**Issue by zihuxinyu** [go-xorm/xorm#271]
type AuthUserInfo struct {
	CorpId string `json:"corpid"`
	Email  string `json:"email"`
}
在oracle中
字段CorpId 在对应sql的字段应该是corp_id,此时如果数据库并没有这个字段，那么程序就出错了，
Handler crashed with error runtime error: invalid memory address or nil pointer dereference
这种情况下，能否给出具体的错误提示？

**Comment by lunny** [comment]
你这个错误看起来不像是这个原因造成的。

**Comment by lunny** [comment]
可以给出更详细的错误信息吗？如果没有的话，我将关闭此Issue。
