### ISSUE TITLE
如何用xorm实现not in

### ISSUE THREAD

**Issue by YueHonghui** [go-xorm/xorm#272]
在xorm里只找到了In语句, 没找到not in语句, 请问要用哪个方法达到这个目的?

**Comment by lunny** [comment]
目前只能用`Where("a not in (?,?,?)", slice...)`

**Comment by lunny** [comment]
This feature have been implemented in branch builder and will be merged to master some time later.

**Comment by lunny** [comment]
The newest version v0.6.0 has resolved this issue. You can `Where(builder.NotIn("a", 1, 2, 3))`.
