### ISSUE TITLE
Oracle插入正常，但出现错误提示，不影响结果！。

### ISSUE THREAD

**Issue by xpbliss** [go-xorm/xorm#282]
使用oci8。
type Dxh struct {
	Id        string `xorm:"not null pk VARCHAR(40)"`
	Content   string `xorm:"Text"`        
}
使用如下：
		aa := models.Dxh{}
		aa.Id = "111111"
		aa.Content = "我的测试，插入数据"
		has, err := models.Engine.Insert(&aa)
		if err != nil {
			revel.WARN.Println(has)
			revel.WARN.Printf("错误: %v", err)
		}
出现错误提示：“错误: ORA-01403: no data found”，但是不影响插入的结果(数据已插入)。其中的"has"为0.

但是，使用原生的insert into。。。。。。（不用xorm），则正常。

**Comment by lunny** [comment]
生成的SQL可以显示下吗？

**Comment by xpbliss** [comment]
Listening on :59734...
[xorm] [info]  2015/08/22 19:00:26.225541 [sql] INSERT INTO "dxh" ("id", "content") VALUES (:1, :2) [args] [111111 我的测试，插入数据]
[xorm] [info]  2015/08/22 19:00:26.231541 [sql] BEGIN TRANSACTION
[xorm] [info]  2015/08/22 19:00:26.234541 [sql] COMMIT
WARN  2015/08/22 19:00:26 app.go:22: 0
WARN  2015/08/22 19:00:26 app.go:23: 错误: ORA-01403: no data found

**Comment by lunny** [comment]
似乎是出在自增id的赋值上。

**Comment by xpbliss** [comment]
而且用 
dxh := []models.Dxh{}
models.Engine.Limit(10, 0).Find(&dxh)
输出的sql是：
[xorm] [info]  2015/08/23 09:09:38.654104 [sql] SELECT "id", "content" FROM (SELECT "id", "content",ROWNUM RN FROM (SELECT "id", "content" FROM "dxh") at WHERE ROWNUM <= 10) aat WHERE RN > 0
尤其是后面的 "at.................aat......."

**Comment by lunny** [comment]
那个是分页

**Comment by xpbliss** [comment]
如果用update也是同样的错误：“ 错误: ORA-01403: no data found”

**Comment by xpbliss** [comment]
希望作者能尽快改一下啊。  以便我继续测试啊。

**Comment by lunny** [comment]
OK。

**Comment by xpbliss** [comment]
Go-OCI8的驱动改了一点，希望尽快修正啊！
