### ISSUE TITLE
When stuct contains another struct, xorm can insert but can not query

### ISSUE THREAD

**Issue by codeskyblue** [go-xorm/xorm#283]
My struct is
![image](https://cloud.githubusercontent.com/assets/3281689/9430829/8ffd8082-4a34-11e5-97a6-c7001ac97314.png)
![image](https://cloud.githubusercontent.com/assets/3281689/9430832/a1670a50-4a34-11e5-8cce-63d665ffdd28.png)

When I change
```
T Task `xorm:"-"`
```
to
```
T Task `xorm:"task"`
```

xorm panics with

```
panic: not supported {    map[] false} as []
```

**Comment by lunny** [comment]
Task should has one primary key so we can insert on Record table. Please check your database if there is a column named t? If there is please ensure the column type is the same as task table's primary key's type.

**Comment by lunny** [comment]
Just use `xorm:"json"` to resolve it.
