### ISSUE TITLE
某些场景下Engine.Tables未包含需要的表信息

### ISSUE THREAD

**Issue by chenghuama** [go-xorm/xorm#284]
如下面的代码，如果直接对a进行赋值，然后再赋值给b，对b进行插入的时候，没有保存对象的key，而是将a转为是json字符串进行了保存。如果对a.guid赋值后，先对a进行get，问题就不存在。经排查，是因为没有先get的情况下，Db_write.Tables中不包含A，导致插入的时候作为json处理。

type A struct {
	Guid string `xorm:"varchar(36) pk"`
}
type B struct {
	A *A `xorm:"varchar(36)"`
	B string
}

func TestSum(t *testing.T) {
	Db_write, err := NewEngine("mysql", "root:@tcp(127.0.0.1:3306)/test?charset=utf8")
	if err != nil {
		t.Fatal(err)
	}
	a := &A{}
	a.Guid = "0b7a4362-ea92-4e6a-a049-634c14912856"

	b := &B{}
	b.A = a

	//		Db_write.Get(a)

	t.Log(Db_write.Insert(b))

}

**Comment by lunny** [comment]
已由 a01186e 解决。

**Comment by lunny** [comment]
先关闭此issue，如有问题可再开。
