### ISSUE TITLE
[pg] Incorrect parsing of connection configuration

### ISSUE THREAD

**Issue by michalbachowski** [go-xorm/xorm#285]
The connection string with empty password:

```user=XXX password= host=/tmp port=5432 dbname=XXX sslmode=disable```

Is incorrectly parsed as:

```map[password:host=/tmp dbname:XXX sslmode:disable host:localhost port:5432 extra_float_digits:2 user:XXX```

Because ```password=``` is empty parser treats entire ```host=/tmp``` as password. If Password is explicitely given - everything works fine:
```user=XXX password=- host=/tmp port=5432 dbname=XXX sslmode=disable```
becomes:
```map[password:- host:/tmp dbname:XXX sslmode:disable host:localhost port:5432 extra_float_digits:2 user:XXX```

Please fix it.

Best regards

Michał Bachowski

**Comment by lunny** [comment]
OK. And you can use another formal connection string temporiroy. postgres://root:@host:port/dbname?sslmode=

**Comment by michalbachowski** [comment]
I use go-xorm as part of [grafana](http://github.com/grafana/grafana) project, so I can not change it. Looking forward to this being fixed.

Best regards

Michał Bachowski

**Comment by lunny** [comment]
@michalbachowski 

Both `user=XXX password=- host=/tmp port=5432 dbname=XXX sslmode=disable` and `postgres://root:@host:port/dbname?sslmode=` are supported by lib/pq and xorm.

I have checked the xorm's codes and it's ok. And then I found the documentation [http://godoc.org/github.com/lib/pq](http://godoc.org/github.com/lib/pq)

```
Use single quotes for values that contain whitespace:

"user=pqgotest password='with spaces'"
```
So I think if you use single quote as empty password or remove empty value k/v pair, it will ok.

**Comment by lunny** [comment]
I close this issue since grafana/grafana#2553 is closed.
