### ISSUE TITLE
有计划支持自定义pg数据库的schema吗？

### ISSUE THREAD

**Issue by tossp** [go-xorm/xorm#286]
现在的设计只支持schema=="public"

**Comment by lunny** [comment]
怎么支持呢？如果支持了，用起来像什么样子？

**Comment by lunny** [comment]
可以在connstr里面加个参数，来指明schema，在dialect中保存，不过有些地方需要改动。

**Comment by tossp** [comment]
我现在想的是，在设置数据库连接字段的时候，设置schema，默认为public

还有一个纠结的就是，schema不存在时候，是否尝试自动创建？
然后就是获取实体表名的时候schema.tablename的格式

**Comment by lunny** [comment]
嗯。似乎有点麻烦。

**Comment by tossp** [comment]
GetColumns函数的sql语句补全了，然后就是暴露出去的接口怎么设计的问题了
是要修改`Dialect `接口？还是扩展？还是另写一个？这个我对xorm还没有一个整体的把握，，，
不敢乱设计，幸苦您了

**Comment by tossp** [comment]
刚查看一下，确认支持自定义schema的话，我再去改`IndexCheckSql` `TableCheckSql`等等这些函数的sql

**Comment by lunny** [comment]
可能要对PostgresDialect做少量修改，如果需要，也有可能少量修改接口。

**Comment by tossp** [comment]
PostgresDialect，我敢动Dialect就不敢乱动了，，，

**Comment by lunny** [comment]
那你先动PostgresDialect吧。需要动Dialect的我来。

**Comment by tossp** [comment]
第二个问题
在做CRUD拼接sql和修改表结构时，需要在类似`statement.TableName()`中，给`tableName`补上前缀，格式`schemaName.tableName`,
比如：`SELECT * FROM public.access_log`

ps：tableName应为需要在类似`IndexCheckSql`这种功能查询中需要，所以我考虑的是不修改`tableName`为带schema前缀的保存名

ps2：新增表和修改表结构最后都是调用到`ModifyColumnSql`接口方法上吧？

**Comment by lunny** [comment]
```Go
type postgres struct {
    core.Base
    pgSchema string
}
```
这个跟我想的一样，但名字我觉得直接用schema就可以。

每个Driver都可以实现自己的`Parse(driverName, dataSourceName string) (*core.Uri, error)`，因此，可以在core.Uri这个结构体中新增一个schema，然后在pgDriver的Parse中将schema赋值。

PS2: yes.

**Comment by tossp** [comment]
dataSourceName我想应该符合
http://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
的定义，这样子自定义真的好么？

不过自定义的dataSourceName真的是很有效率的办法

**Comment by tossp** [comment]
to #361
