### ISSUE TITLE
查询表和JOIN的表含有相同字段名且设置了deleted标签时出错

### ISSUE THREAD

**Issue by howcrazy** [go-xorm/xorm#288]
两个表JION时如都有DeleteAt字段且设置了`xorm:"deleted"`标签
生成的SQL中会因含有(`delete_at` IS NULL or `delete_at` = '0001-01-01 00:00:00')报错
修改xorm/session.go:1213加上table.Name临时暴力解决

**Comment by lunny** [comment]
哦？我测试下。
