### ISSUE TITLE
update自动过滤掉实际需要更新的字段

### ISSUE THREAD

**Issue by qzyuanmu** [go-xorm/xorm#291]
func (ns *News) Add() *News {
	if ns.Id <= 0 {
		_, err := jtool.Engine.Insert(ns)
		if err != nil {
			jtool.Log.Error("插入公告信息失败 :", err)
		}
	} else {
          
		_, err := jtool.Engine.Id(ns.Id).Update(ns)
		 
		if err != nil {
			jtool.Log.Error("更新公告信息失败 :", err)
		}
	}

	return ns
}
结构体为：
type News struct {
	Id int `xorm:"pk autoincr"` 
	Title       string    `xorm:"varchar(250)" `
	Type       string    `xorm:"varchar(250)" `
	WxChatId    int  `xorm:"default 0"`
	WxKey      string    `xorm:"varchar(250)" `
	Info        string    `xorm:"text" `  
	Sort       int       `xorm:"default 20"`
	UserId   int       `xorm:"default 0"`
	UpdateTime time.Time `xorm:"created "`
	//1为启用，2为未启用
	Status int `xorm:"default 1"`
}
 当更新的时候，总是过滤掉Info字段，求解？

**Comment by qzyuanmu** [comment]
if engine.dialect.DBType() == core.MSSQL && col.SQLType.Name == core.Text {
			continue
		}
这个为什么要跳过呢，改成 varchar(max)可以

**Comment by lunny** [comment]
更新的时候默认会自动忽略为""，0，nil的字段。如果需要更新所有的话加个`.AllCols().`

**Comment by qzyuanmu** [comment]
是有内容的，如果是xorm:"text"的话就会忽略的，数据库是mssql

**Comment by lunny** [comment]
这个是自动生成条件，而不是自动生成要更新的内容。mssql下面，text字段内型是不能作为查询字段的。所以这里忽略了。

**Comment by 58243586** [comment]
数据库中 int 类型的字段也会被忽略，导致更新失败。
我注释掉
xorm/hepers.go 文件中的第 325 行，之后就可以更新。 如下所示：
 
		if col.MapType == core.ONLYFROMDB {
			//	continue
		}


我想问一下 为什么要明确的忽略掉int类型的字段？

**Comment by lunny** [comment]
我想你可能理解错了。int为0会被忽略，请先查看文档。

**Comment by qzyuanmu** [comment]
text字段内型是不能作为查询字段的。所以这里忽略了。？
在mssql内，text应该也是可以查询的，希望可以修改下

**Comment by lunny** [comment]
http://stackoverflow.com/questions/4350060/where-clause-on-sql-server-text-data-type, 你看下这个，text是不能够直接作为查询条件的。用varchar(max)是可以。

**Comment by qzyuanmu** [comment]
varchar(max) 经过xorm处理会变为 varchar(1)

**Comment by 58243586** [comment]
恩，看了下update的文档， 当要更新的字段值为 0 或者nil的时候才会被忽略。

为什么要这么设计呢 ？

**Comment by lunny** [comment]
@qzyuanmu , ```varchar(max)```确实没支持。
@58243586, 一般情况下我们只需要更新有意义值的字段就行了啊。所以这么设计的。这只是默认情况，你也可以用`AllCols`, `MustCols`, `Cols`, `Omit`等函数来解决你的问题。

**Comment by 58243586** [comment]
我想问一下， 把一个人的朋友数量清空，减少为0 。这在业务上是有意义的吧。  但开发者却要明确的去把某个字段特别标示出来。岂不是很麻烦。

**Comment by qzyuanmu** [comment]
0值是个取舍的问题，我认为这样也不错，开发的时候多注意点

**Comment by lunny** [comment]
@58243586, 没发现更好的办法，受到Go语言限制。

**Comment by lunny** [comment]
暂时先关闭这个issue了，如果有需要再打开。

**Comment by jmesyan** [comment]
@lunny ,我刚遇到更新的问题了，遇到0值我觉得没有必要这要屏蔽，我们数据库有很多这种状态值 0-标识关闭，1-标识开启，你们这样设计每次更新都得加个allcols
