### ISSUE TITLE
go get reports errors docs submodules

### ISSUE THREAD

**Issue by pmezard** [go-xorm/xorm#294]
Hello,
go getting xorm displays the following with Go 1.5 on OSX:
```
$ go get github.com/go-xorm/xorm
# cd .; git --git-dir=~/go/dev/src/github.com/go-xorm/xorm/.git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'docs/manual-en-US'
package github.com/go-xorm/xorm: exit status 1
```
I do not know if it is a real problem, but it is not nice to see.

**Comment by lunny** [comment]
I can not reproduce the problem. My env is the same as you. And I find this article http://stackoverflow.com/questions/4185365/no-submodule-mapping-found-in-gitmodule-for-a-path-thats-not-a-submodule, maybe it can resolve your question.

**Comment by pmezard** [comment]
FWIW, it does not happen if I go get with Go 1.4.2. Also, other people report similar things with other projects : https://groups.google.com/forum/#!topic/golang-nuts/XNJ_vfai9Io . I will let you handle the issue, feel free to close it if you consider this is a Go issue. But you might want to track it regardless and see where it goes, or even reach Go people.

**Comment by lunny** [comment]
It seems it's a bug of Go 1.5 when you use vendor feature.

**Comment by lunny** [comment]
I think it could be closed since the last Go version has fixed the issue. See https://github.com/golang/go/issues/12573 .
