### ISSUE TITLE
软删除后恢复的问题

### ISSUE THREAD

**Issue by defia** [go-xorm/xorm#297]
由于xorm根据deleted_at字段的内容判断是否为未删除行,如果为NULL时间,或者0001-01-01 00:00:00,则为未删除

如果想恢复删除,我尝试使用 `s.Id(id).Unscoped().Nullable("deleted_at").Update(&Obj{DeletedAt:xorm.NULL_TIME})` 结果是没用的,生成的sql并不包含deleted_at字段的操作
不知道这个NULL_TIME具体是用于什么的?
需要将deleted_at设为哪个值才可正确置NULL?

**Comment by defia** [comment]
又试了一下,即使update delete_at字段为0001-01-01 00 00 00,也无效..生成的sql种并没该字段

**Comment by lunny** [comment]
可以考虑加一个Restore的方法，将软删除的的记录恢复。@defia

**Comment by lunny** [comment]
现在，这句
```
s.Id(id).Unscoped().Nullable("deleted_at").Update(&Obj{DeletedAt:xorm.NULL_TIME})
```
应该生效了。
