### ISSUE TITLE
Can xorm print the raw sql statement?

### ISSUE THREAD

**Issue by clinyong** [go-xorm/xorm#298]
I enable the ShowSQL.

```go
db.ShowSQL = true
```

And it will print the statement in like

```go
[xorm] [info]  2015/09/14 18:08:29.358438 [sql] SELECT "id", "name", "password", "is_vistor" FROM "user" WHERE name = $1 LIMIT 1 [args] [clyyyyy]
```

Can xorm print the raw statement like

```go
SELECT "id", "name", "password", "is_vistor" FROM "user" WHERE name = 'clyyyy' LIMIT 1
```

Which can be directly execute in psql console.

**Comment by lunny** [comment]
```Go
engine.Query(sqlstr)
```

**Comment by lunny** [comment]
You can try to use yourself logger implement to replace the default. Please checkout https://github.com/go-xorm/xorm/blob/master/logger.go#L37 and write yours.

**Comment by lunny** [comment]
I will close this currently, if you have any new problem. Please reopen this issue.

**Comment by happilymarrieddad** [comment]
@lunny can you give an example? I would love to try to do this but I really don't know where to start. Thanks!

**Comment by lunny** [comment]
@happilymarrieddad You can find an example here https://gitea.com/xorm/gitea_log_bridge/src/branch/master/bridge.go

This bridge will use `code.gitea.io/log` as an log infrastruct  instead of internal one.
