### ISSUE TITLE
 如何做count的同时又返回结果?

### ISSUE THREAD

**Issue by williambao** [go-xorm/xorm#306]
一般有分页查询时, 都会返回where满足的总数据条数和当前页的数据. 但是我先做count后再find. 发现count步骤成功了, 但是find部分所有的where条件丢失, 返回了所有数据. 
请问如何去做这类的操作?  另, 文档部分太过简陋, 应该给出几列常见的串联操例子比只写单个方法功能更好.

我的代码如下:
数据库有三条记录, 传了username应只拿到一条记录. 但最后count这一步正确, 值是1. 但最终find时返回了三条记录.

```
    username := "oo"
    nickname := ""
    email := ""
	engine := models.Engine()
	where := engine.Where("nickname like ? and username like ? and email like ? ",
		"%"+nickname+"%", "%"+username+"%", "%"+email+"%")

    // total 值为1, 是正确的
	total, _ := where.Count(&models.User{})
	users := make([]models.User, 0)

	if err := where.Limit(pagesize, pagesize*(page-1)).Asc("created_at").Find(&users); err != nil {
		return nil, err
	}

    // 此处users为全部三条数据, 是错误的
    return users, nil
```

**Comment by lunny** [comment]
username := "oo"
    nickname := ""
    email := ""
    engine := models.Engine()
    where := func() *xorm.Session {
        return engine.Where("nickname like ? and username like ? and email like ? ",
        "%"+nickname+"%", "%"+username+"%", "%"+email+"%")
   }

    // total 值为1, 是正确的
    total, _ := where().Count(&models.User{})
    users := make([]models.User, 0)

    if err := where().Limit(pagesize, pagesize*(page-1)).Asc("created_at").Find(&users); err != nil {
        return nil, err
    }

    // 此处users为全部三条数据, 是错误的
    return users, nil

**Comment by williambao** [comment]
@lunny 可以了, 谢.
