### ISSUE TITLE
XORM doesn't honor 0 values for Int in Sqlite3

### ISSUE THREAD

**Issue by VarunBatraIT** [go-xorm/xorm#307]
```
type User struct {
	Id                       int64  `xorm: "INT not null pk autoincr"`
	BadWordsInUser           string `xorm:"TEXT default ''"`
	ConsiderBadWordsInUser   bool   `xorm:"BOOLEAN not null default false`
}
```

```
auser := new(Bot)
auser.BadWordsInUser = "test,admin"
auser.ConsiderBadWordsInUser = true
engine.Id(1).update(user)
```

```
[xorm] [info]  2015/10/17 22:59:51.441757 [sql] UPDATE `user` SET `bad_words_in_user` = ?  WHERE `id` = ? [args] ["test,admin" 1]
```

ConsiderBadWordsInUser is vanished and ignored completely

**Comment by VarunBatraIT** [comment]
Sorry I believe it is a wrong issue considering that I should use int instead of boolean in case of Sqlite3. I didn't consider it when I moved from mysql.

**Comment by VarunBatraIT** [comment]
Reopening issue considering that: Even when I tried int, even then it doesn't support 0 as insertion


It works fine if I am inserting it for the first time.  
Example 

```
user.Active = 0 //works on insert
engine.Id(id).Insert(user)
user.Active = 1 //works on update
engine.Id(id).Update(user)
user.Active=0 //doesn't work on update
engine.Id(id).Update(user)
```

```
type User struct {
...
Active                   int8   `xorm:"TINYINT(4)"`
}
````

**Comment by VarunBatraIT** [comment]
Funny this works

```
engine.Table(new(User)).Id(id).Update(map[string]interface{}{"Active":0})
```

**Comment by lunny** [comment]
For update, the default action is it will update all columns which is not 0 and not nil. So if you want to force to update some columns, you can use 
```Go
engine.MustCols("Active").Id(id).Update(user)
```

**Comment by VarunBatraIT** [comment]
Can I vote that it is a serious design flaw? Like I can nil or assign zero to a column. I believe it is quite normal and often used. Do do you think? :+1:

**Comment by lunny** [comment]
Hi, I think sometimes you want to update all columns, sometimes you want to update some columns. And for Golang, we cannot know if you want to update some column if it is zero or nil? Am I right. If you have new idea, please let me know. I think I can consider to implement it. Thanks. @VarunBatraIT

**Comment by VarunBatraIT** [comment]
Oh Lunny I have no idea. It is my first static typed language. :)
I think you are right in case default value is 0 for int and "" for string so we never know.
