### ISSUE TITLE
mysql 同步不完全

### ISSUE THREAD

**Issue by mohong122** [go-xorm/xorm#308]
是用engine.Sync2(new(User),new(Group),...)
同步数据库时，当一个Sync2中出现beans数量比较多的情况下，只同步前面几个，后面的不在同步了
再写一个engine.Sync2(beans...) 才会同步接下来的数据库

**Comment by lunny** [comment]
有多少个beans？

**Comment by mohong122** [comment]
13个时，只同步了11个，后面的两个未同步

**Comment by lunny** [comment]
有返回错误吗？

**Comment by mohong122** [comment]
@lunny 没有错误信息，返回的都是nil

**Comment by jeremyzhou2001** [comment]
@lunny 这个问题有解决么？版本0.5.5，批量操作数据库也偶现丢几条记录，最新版本0.6.3是否修复？

**Comment by lunny** [comment]
没有重现到这个问题，也许你可以试下最新版本

**Comment by lunny** [comment]
Please feel free to reopen it.
