### ISSUE TITLE
mssql 时间类型(Datetime)从数据库取出来的值和实际值相差8小

### ISSUE THREAD

**Issue by shengzhi** [go-xorm/xorm#310]
mssql 时间类型(Datetime)从数据库取出来的值和实际时间相差8小时, 这是个bug还是我使用的方式不对?

driver: denisenkom/go-mssqldb

**Comment by 287008** [comment]
同样碰到这个问题，请问楼上怎么解决的？也是在疑惑是bug还是使用方式不对？Xorm好像默认数据库中的时间类型为UTC时间。 @shengzhi   谢谢！

**Comment by lunny** [comment]
```Go
location, err = time.LoadLocation("Asia/Shanghai")
engine.TZLocation = location
```

**Comment by qzyuanmu** [comment]
使用了楼主的方法，也有同样的问题。数据库里的时间是对的

**Comment by shengzhi** [comment]
@287008 , 我用的笨方法, 为每个struct写了调整时间的方法, 项目紧, 没时间去研究

**Comment by lunny** [comment]
This should be fixed by #604
