### ISSUE TITLE
query 返回的是Map[string][]byte 比 Map[string]interface{}有什么好处？

### ISSUE THREAD

**Issue by hzmnet** [go-xorm/xorm#314]
根据代码原Pkg 是将字段类型转成不同类型的数据存入interface{}。而XORM则强制转成[]Byte 类型。让原本可以判断的类型无法判断了。query 强制返回的是Map[string][]byte 比 Map[string]interface{}有什么好处？

**Comment by lunny** [comment]
也不一定哪个更好。

**Comment by lunny** [comment]
见 #339
