### ISSUE TITLE
请教group by用法

### ISSUE THREAD

**Issue by williambao** [go-xorm/xorm#315]
你好,
有一个用法问题请教, 一直想不出来如何去做.
如现在系统都有一个私信/聊天模块, 我现在想拿到会话记录, 也就是每个用户一条记录, 以用户最后一次聊天时间来倒序.
假设表结构如下:
```go
type Message struct{
  Id int64
  UserId int64
  FriendId int64
 Content string
 CreatedAt time.Time
}
```
此时我想拿指定UserId下的回话列表? 也就是对FriendId进行group操作. 
如果来写orm语句呢?

望知道的教下:), 谢

**Comment by lunny** [comment]
```Go
engine.Where('user_id=?', userId).Desc('created_at').GroupBy('friend_id').Find(&messages)
```
这样可以吗？

**Comment by lunny** [comment]
如果没有问题，就先关闭了。

**Comment by williambao** [comment]
@lunny  不好意思, 刚看到您的回复. 
你这个写法是无法获取的, 再最后的messages里只有friend_id一个字段是有值的. 
但是其他字段都无内容.
