### ISSUE TITLE
MySQL中使用created和updated字段,插入、更新数据时，返回"updated": "0001-01-01T00:00:00Z"

### ISSUE THREAD

**Issue by SmarkSeven** [go-xorm/xorm#320]
结构体如下：
type Schedule struct {
	Id       int64    
	CoachId  int64     `json:"coachId"`
	Number   int       `json:"number"`   
	Max      int       `json:"max"`    
	Subject  int       `json:"subject"` 
	Datetime time.Time 
	Status   int      
	Created  time.Time `xorm:"created" json:"created`
	Updated  time.Time `xorm:"updated" json:"updated"`
}
当更新数据时，返回结果如下：
{
  "code": 1,
  "errorInfo": "",
  "data": {
    "id": 25,
    "coachId": 32,
    "number": 0,
    "max": 0,
    "subject": 2,
    "datetime": "2015-12-09T13:00:00Z",
    "status": 1,
    "Created": "0001-01-01T00:00:00Z",
    "updated": "0001-01-01T00:00:00Z"
  }
}
数据库中，updated的值却又是更新记录的时间

**Comment by lunny** [comment]
你的xorm版本？

**Comment by SmarkSeven** [comment]
xorm v0.4.4.1203

**Comment by lunny** [comment]
Hi，请重新获取最新版本测试下，这个问题应该在某个版本中解决了。@SmarkSeven

**Comment by SmarkSeven** [comment]
我后来发现是在使用事务时，在提交事务之前返回结果才得到以上的情况。

**Comment by SmarkSeven** [comment]
我后来发现是在使用事务时，在提交事务之前返回结果才得到以上的情况。

**Comment by lunny** [comment]
提交事务前，理论上应该也要是对的才对。如果再发现此类问题，再打开此issue。

**Comment by lunny** [comment]
还是有问题吗？

**Comment by SmarkSeven** [comment]
OK啦，谢谢！

**Comment by ElvinChan** [comment]
我也遇到这个问题了，开了一个新的Issue #633
