### ISSUE TITLE
给mysql timestamp 类型设置默认值后, 使用xorm工具倒出model,插入时生成的SQL语句有错.

### ISSUE THREAD

**Issue by johnnyluo586** [go-xorm/xorm#321]

**Comment by lunny** [comment]
代码能贴下吗？

**Comment by johnnyluo586** [comment]
//CheckTime     time.Time `xorm:"TIMESTAMP"`
CheckTime time.Time `xorm:"not null default '2000-01-01 00:00:00' TIMESTAMP"`
1 为没有设置默认值. 使用engine.Insert()正常.
2. 为设置了默认值.报错, 生成的SQL为:
INSERT INTO `item` (`id`, `name`, `url`, `cur_version`, `cur_uptime`, `new_version`, `new_uptime`, `regexp_version`, `regexp_uptime`, `00:00:00'`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [args] [0    2015-12-16  0001-01-01   2015-12-15 08:00:00]

**Comment by hsyan2008** [comment]
我的问题和这个差不多，见https://github.com/go-xorm/xorm/issues/328

**Comment by lunny** [comment]
resolved by 8700152b6cbbf6a221e7ca59ef55e21ef73cf580
