### ISSUE TITLE
无法创建索引

### ISSUE THREAD

**Issue by fym201** [go-xorm/xorm#322]
调用engine.CreateIndexes()方法后生成的sql为 
CREATE INDEX `IDX_balance_amount` ON `balance` (`amount`);
然后收到错误：
panic: Error 1142: INDEX command denied to user 'xxxx'@'192.168.1.1' for table 'balance'

**Comment by lunny** [comment]
你的数据库权限没有设置正确。

**Comment by fym201** [comment]
的确是这个问题
