### ISSUE TITLE
请问什么时候可以支持cassandra？

### ISSUE THREAD

**Issue by cnwangzd** [go-xorm/xorm#323]
请问什么时候可以支持cassandra？或是，是否有这个意向？：）

Thanks！

**Comment by fuxiaohei** [comment]
目前没有对nosql的支持意向，

主要还是支持sql数据库

**Comment by lunny** [comment]
他说的可能是基于cassandra的sql？@fuxiaohei 目前似乎没有兼容的driver。@cnwangzd

**Comment by cnwangzd** [comment]
我指的是xrom for cassandra的driver。 感谢指教！ 发自网易邮箱大师 在2015年12月26日 23:12 ，Lunny Xiao写道： 他说的可能是基于cassandra的sql？@fuxiaohei 目前似乎没有兼容的driver。@cnwangzd — Reply to this email directly or view it on GitHub.

**Comment by lunny** [comment]
短期内不会支持。
