### ISSUE TITLE
xorm的严重性能问题

### ISSUE THREAD

**Issue by fishedee** [go-xorm/xorm#326]
我用xorm与gorm对比做benchmark，
对本地的mysql做1W次select * from t_user的操作
发现xorm比gorm慢了很多，
xorm性能大概是500次/s
而gorm大概是1500次/s

后来将代码中发现session中的Find方法，先执行doPrepare,以后执行Query。
直接修改源代码为只有一次Query后
性能提升到和gorm跟差不多

具体原因还在排查中，希望大大帮忙看下啥问题。
为什么xorm的版本性能会与gorm差那么远。

![screen shot 2015-12-29 at 1 23 25 pm](https://cloud.githubusercontent.com/assets/4318347/12029838/72675ad4-ae2f-11e5-92bf-3a550f3006c7.png)
修改前，xorm中session.go的源代码，benchmark为 500request/s

![screen shot 2015-12-29 at 1 23 48 pm](https://cloud.githubusercontent.com/assets/4318347/12029846/a5343356-ae2f-11e5-98b8-1d5b5bb4be4b.png)
修改后，xorm中session.go的源代码，benchmark为 1500request/s，大概为原来的3倍。

希望作者大大帮忙看看这个问题，性能问题还是非常重要的，谢谢～

**Comment by lunny** [comment]
xorm的这段默认使用的Prepare Statement，所以对于首次运行会比较慢，但是持续运行，后面性能应该是越来越快。当然如果更好的方案是作为一个可选项，可设置为是否使用Prepare Statement。

**Comment by lunny** [comment]
如果是单线程，用下面的代码，性能会比较高。
```
sess := engine.NewSession()
sess.IsAutoClose = false
for {
sess.Find()
}
```

**Comment by fishedee** [comment]
作者大大，我测过了，跑过一段时间以后，再跑这个测试，也是一样的慢哈，只有500 request/s。看了gorm与gorp的源代码，也是直接用query，没有prepare的。麻烦大大也可以提供Prepare Statement的开关，谢谢～

**Comment by lunny** [comment]
正在改为默认不开Prepare Statement。

**Comment by fishedee** [comment]
太好了，谢谢大大，还有，xorm的接口很漂亮，赞一个～

**Comment by fishedee** [comment]
![screen shot 2015-12-30 at 12 26 06 pm](https://cloud.githubusercontent.com/assets/4318347/12046271/a1a54024-aef0-11e5-91d1-238ff3abb9dc.png)
大大，你的innerQuery函数貌似还没有改，导致执行Count()查询时还是走prepare逻辑，测了下执行Count操作时仍然只有500 request/s。
麻烦大大看看

**Comment by lunny** [comment]
Core包也修改过了，所以更新要注意同时更新core包
```
go get -u
```

**Comment by yh453926638** [comment]
@fishedee  http://dev.cmcm.com/archives/288 看这个说明
