### ISSUE TITLE
能否提供结构体组合的功能

### ISSUE THREAD

**Issue by hsyan2008** [go-xorm/xorm#328]
比如
type A struct {
    Id int64
    Updatedat time.Time
}
type B struct {
    A
    Username string
}

b := new(B)
b.Username = "test"
engine.Insert(b)

SQL报错，报字段a不存在，能否实现和https://github.com/jinzhu/gorm差不多的方式

**Comment by lunny** [comment]
```Go
type B struct {
A `xorm:"extends"
Username string
}
```
请参见文档http://gobook.io/read/go-xorm/manual-zh-cn/chapter-05/5.join.html

**Comment by hsyan2008** [comment]
看了下，不知道是不是我还没学会用，我再描述下具体问题
我们这里有个规则，就是所有的表必须有is_deleted，updated_at，created_at
我想把这三个字段放在A结构体里，作为公用的
其他的表的结构体叫B、C之类的，都内嵌A结构体

**Comment by lunny** [comment]
```Go
type A struct {
IsDeleted bool
UpdatedAt time.Time `xorm:"updated"`
CreatedAt time.Time `xorm:"created"`
}

type B struct {
A `xorm:"extends"`
...
}

type C struct {
A `xorm:"extends"`
...
}
```

**Comment by hsyan2008** [comment]
现在OK了，是我的失误

**Comment by hsyan2008** [comment]
现在碰到个新的问题，测试代码生成的时候，生成的代码如下（package model改成package daos）
package daos

import (
        "time"
)

type Mails struct {
        Id        int       `xorm:"not null pk autoincr INT(11)"`
        Username  string    `xorm:"not null default '' VARCHAR(255)"`
        Password  string    `xorm:"not null default '' VARCHAR(255)"`
        Status    string    `xorm:"not null default 'N' ENUM('S','E','N')"`
        IsDeleted string    `xorm:"not null default 'N' ENUM('N','Y')"`
        UpdatedAt time.Time `xorm:"not null default '0000-00-00 00:00:00' TIMESTAMP"`
        CreatedAt time.Time `xorm:"not null default 'CURRENT_TIMESTAMP' TIMESTAMP"`
}
执行的代码如下
        mail := new(Mails)
        mail.Username = "aa@qq.com"
        mail.Password = "test"
        mail.Status = "N"
        rs, err := engine.Insert(mail)

        logger.Warn(rs, err, &mail)

执行的时候报如下错误
[xorm] [info]  2016/01/02 00:05:28.785403 [sql] INSERT INTO `mails` (`username`, `password`, `status`, `is_deleted`, `00:00:00'`, `created_at`) VALUES (?, ?, ?, ?, ?, ?) [args] [a
a@qq.com test N  0001-01-01 00:00:00 0001-01-01 00:00:00]
[xorm] [debug] 2016/01/02 00:05:28.786018 [time] INSERT INTO `mails` (`username`, `password`, `status`, `is_deleted`, `00:00:00'`, `created_at`) VALUES (?, ?, ?, ?, ?, ?) - args [
aa@qq.com test N  0001-01-01 00:00:00 0001-01-01 00:00:00] - execution took: 590231ns
2016/01/02 00:05:28.786092 mails.go 26 [WARN  [0 Error 1054: Unknown column '00:00:00'' in 'field list' 0xc820036b90]]

帮忙看下。。

**Comment by hsyan2008** [comment]
另外反馈个问题
type Public struct {
        Id        int64 `xorm:"pk autoincr"`
        IsDeleted string
        UpdatedAt time.Time `xorm:"updated"`
        CreatedAt time.Time `xorm:"created"`
}
type Mails struct {
        Id        int       `xorm:"not null pk autoincr INT(11)"`
        Username  string    `xorm:"not null default '' VARCHAR(255)"`
        Password  string    `xorm:"not null default '' VARCHAR(255)"`
        Status    string    `xorm:"not null default 'N' ENUM('S','E','N')"`
        IsDeleted string    `xorm:"not null default 'N' ENUM('N','Y')"`
        UpdatedAt time.Time `xorm:"not null default '0000-00-00 00:00:00' TIMESTAMP"`
        CreatedAt time.Time `xorm:"not null default 'CURRENT_TIMESTAMP' TIMESTAMP"`
        Public    `xorm:"extends"`
}

这两个结构体有相同字段，生成的sql是
[xorm] [info]  2016/01/02 14:17:49.754679 [sql] INSERT INTO `mails` (`username`, `password`, `status`, `is_deleted`, `00:00:00'`, `created_at`, `is_deleted`, `updated_at`, `created_at`) VALUES (?, ?, ?, ?, ?, ?, ?
, ?, ?) [args] [aa@qq.com test N  0001-01-01 00:00:00 0001-01-01 00:00:00  2016-01-02 14:17:49 2016-01-02 14:17:49]
[xorm] [debug] 2016/01/02 14:17:49.755274 [time] INSERT INTO `mails` (`username`, `password`, `status`, `is_deleted`, `00:00:00'`, `created_at`, `is_deleted`, `updated_at`, `created_at`) VALUES (?, ?, ?, ?, ?, ?, 
?, ?, ?) - args [aa@qq.com test N  0001-01-01 00:00:00 0001-01-01 00:00:00  2016-01-02 14:17:49 2016-01-02 14:17:49] - execution took: 490822ns
2016/01/02 14:17:49.790647 mails.go 27 [WARN  [0 Error 1054: Unknown column '00:00:00'' in 'field list' 0xc820036018]]

**Comment by lunny** [comment]
你有两个Id是什么意思呢？

**Comment by lunny** [comment]
见 #321， 已解决。

**Comment by hsyan2008** [comment]
是这样的，在golang里面，自身的字段会覆盖内嵌的结构体相同的字段，但这里没有，所以出现了2个相同的字段

**Comment by lunny** [comment]
不覆盖。所以你这个你需要重新设计你的结构体。
