### ISSUE TITLE
能否支持在程序里获取sql语句

### ISSUE THREAD

**Issue by hsyan2008** [go-xorm/xorm#329]
目前支持用engine.ShowXXX系统的变量来设置打印SQL
但是这样会有一些问题
1、无法用自己的logger来打印
2、不管执行成功或失败，都会打印或都不打印
而我想在执行失败的时候，才用自己的logger来打印，这个是否可以支持下

**Comment by lunny** [comment]
你可以调用`session.LastSQL()`来获取该session最后一次执行的SQL语句以及参数。engine目前的想法是采用一个回调函数，实现上还需要时间。

**Comment by hsyan2008** [comment]
赞，非常棒，可以加到文档了
