### ISSUE TITLE
Add support for ModifiedAt timestamp

### ISSUE THREAD

**Issue by codefx9** [go-xorm/xorm#332]
We would like to see support for `ModifiedAt` tag similar to `Created` tag. Also, We would like option to configure these tag names to fit our column names. Is this someone we can expect to be added to XORM?

**Comment by lunny** [comment]
Hi, I think we already have this feature named Updated. You just only need to add `xorm:"updated"` to the field. For example,

```Go
type MyTable struct {
CreatedAt time.Time `xorm:"created"`
ModifiedAt time.Time `xorm:"updated"`
DeltedAt time.Time `xorm:"deleted"`
}
```

I have improved the document. And you can find them [here](http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-06/2.updated.html) and [here](http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-07/1.deleted.html)

**Comment by codefx9** [comment]
Awesome, lunny. One more question, is there a way to customize these column names? I am thinking something like this:

    dateModified time.Time `xorm:"dateModified,updated"`

The second string can be hint that this column should be treated like `updated` tag. This will allow us to use this feature for pre existing tables.

**Comment by lunny** [comment]
Yes. Use single quote before and after the column name and use space split multiple keyword of xorm.

```Go
DateModified time.Time `xorm:"updated 'dateModified'"`
```

**Comment by codefx9** [comment]
Thanks for this hidden gem, @lunny. I wish things were better documented. :+1:

**Comment by lunny** [comment]
You can find the document [here](http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-02/4.columns.html). @codefx9
