### ISSUE TITLE
no way to getLastInsertId 

### ISSUE THREAD

**Issue by gauravgargtech** [go-xorm/xorm#335]
In Xorm, after Insert command, there is no way o get the last inserted id, please provide an method as Go language's default database/sql package has this function

**Comment by lunny** [comment]
The id will be assigned to the id field of struct. For example:
```Go
type User struct {
     Id int64 `xorm:"pk autoincr"`
     Name string
}
var user User
engine.Insert(&user)
fmt.Println(user.Id)
```
If insert succeed, this will print the user's id.

**Comment by lunny** [comment]
So I think xorm don't need another way to provide last inserted id. @gauravgargtech

**Comment by gauravgargtech** [comment]
Thanks a lot Lunny, Xorm is one of the best ORM i ever saw, thanks.

**Comment by lunny** [comment]
Thank you! @gauravgargtech
