### ISSUE TITLE
Insert method : no way to specify table name 

### ISSUE THREAD

**Issue by gauravgargtech** [go-xorm/xorm#340]
Hello, Insert function of Xorm , uses struct name and inserts data in specific table as depicted from struct, If i wan to insert in other table, is there any way, for example 

type NewOrder struct {
   id int
   order_nr int
}
order := NewOrder{"id":1,"order_nr":123}
engine.Insert($order)

I want to save the data in table "orders", please comment on this ...

**Comment by lunny** [comment]
There are two ways to do that:
```Go
func (NewOrder) TableName() string {
    return "orders"
}
```
another way is
```Go
engine.Table("orders").Insert(&order)
```

**Comment by gauravgargtech** [comment]
Thanks !!!
