### ISSUE TITLE
engine.Where("num =(select max(num))").Delete(redEnvelope)失败

### ISSUE THREAD

**Issue by SmarkSeven** [go-xorm/xorm#344]
affected, err := engine.Where("num =(select max(num))").Delete(redEnvelope)
affected始终等于0 ？
如果要删除RedEnvelope表中Num值最大的纪录，在不知道Num最大值的情况下，该怎样删除？

**Comment by lunny** [comment]
生成的SQL语句贴下。更新下xorm，最新的版本支持如下用法(mssql暂不支持)。
```Go
engine.Desc("num").Limit(1).Delete(redEnvelope)
```

**Comment by winxxp** [comment]
engine.Where("num = (select item from (select max(num) item from tablexxxx) as _tmptable)").Delete(new(xxxxx))

**Comment by lunny** [comment]
@winxxp 你这个应该也行。

**Comment by SmarkSeven** [comment]
以上两种方式都可以，但是还存在一个问题："删除"之后只返回了'deleted_at'的值，无法知道删除了哪一条记录

**Comment by SmarkSeven** [comment]
以上两种方式都可以，但是还存在一个问题："删除"之后只返回了'deleted_at'的值，无法知道删除了哪一条记录 @lunny

**Comment by lunny** [comment]
这个你就得自己去根据条件查询了。xorm要做到通用性，不能做得太多，否则会有性能问题。@SmarkSeven

**Comment by SmarkSeven** [comment]
嗯，在测试时发现在事务中使用engine.Desc("num").Limit(1).Delete(redEnvelope) 不会返回'deleted_at'的值 @lunny

**Comment by lunny** [comment]
目前的这个值应该是所有事务成功后才会执行。

**Comment by lunny** [comment]
解决你的问题了吗？@SmarkSeven

**Comment by SmarkSeven** [comment]
OK 了 @lunny
