### ISSUE TITLE
While import xorm got following error

### ISSUE THREAD

**Issue by gurbachan-singh-jabong** [go-xorm/xorm#348]
src/github.com/go-xorm/xorm/engine.go:835: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/engine.go:838: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/engine.go:1446: col.DisableTimeZone undefined (type *core.Column has no field or method DisableTimeZone)
src/github.com/go-xorm/xorm/engine.go:1448: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/engine.go:1449: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/session.go:1795: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/session.go:1798: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/session.go:1809: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/session.go:1812: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/session.go:2395: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/session.go:2395: too many errors

**Comment by lunny** [comment]
Please `go get -u github.com/go-xorm/xorm`, because `github.com/go-xorm/core` has been updated too.

**Comment by gurbachan-singh-jabong** [comment]
Still Show Same error

src/github.com/go-xorm/xorm/engine.go:834: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/engine.go:836: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/engine.go:839: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/engine.go:1447: col.DisableTimeZone undefined (type *core.Column has no field or method DisableTimeZone)
src/github.com/go-xorm/xorm/engine.go:1449: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/engine.go:1450: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/session.go:1795: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/session.go:1798: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/session.go:1809: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/session.go:1812: col.TimeZone undefined (type *core.Column has no field or method TimeZone)
src/github.com/go-xorm/xorm/session.go:1812: too many errors

**Comment by lunny** [comment]
Please delete your `github.com/go-xorm/core` and `go get github.com/go-xorm/core`, this should be a download problem.

**Comment by gurbachan-singh-jabong** [comment]
Done 

Thanks to your support
