### ISSUE TITLE
Support always updating columns

### ISSUE THREAD

**Issue by codefx9** [go-xorm/xorm#349]
We are facing an issue similar to https://github.com/go-xorm/xorm/issues/307 . `Cols` are solving the problems for now. But since we are doing soft deletes for most tables, updates are becoming bit cumbersome to write. Will it be possible to add these features:

1. Add a tag called `must-update` or something shorter to ensure that the column gets always updated.

2. Is it possible for xorm to detect blind writes and fail writes on those cases selectively?

**Comment by lunny** [comment]
For the first question, that's about how to build a condition always use. You can define a function, for example:
```Go
func MustUpdate() *xorm.Session {
return engine.MustCols("col1, col2")
}
```
Then you can use it
```Go
MustUpdate().Where().Update()
```

For the second, could you give some examples to describe it?

**Comment by codefx9** [comment]
Thanks for the idea @lunny for question #1. If I call `engine.MustCols("col1, col2")` on columns that does that exist on a particular table will it throw errors?

**Comment by lunny** [comment]
No, It will not throw errors.
