### ISSUE TITLE
Old Problems

### ISSUE THREAD

**Issue by hzmnet** [go-xorm/xorm#351]
2016/02/11 00:12:34 [D] SqlQuery:SELECT " * " FROM "module"   [[]]
2016/02/11 00:12:34 [E] [sql: converting Exec argument #0's type: unsupported type []string, a slice]

Pg 是不支持 类似SELECT " * " FROM "module"的
Query 不支持传入一个[]string
Query([]string{}...)

**Comment by lunny** [comment]
传入一个[]string，那么是作为多个参数还是json成一个参数呢？

**Comment by hzmnet** [comment]
1成为一个多参数，也就是当一个为nil的[]string变量传进来去Query 作为多参数时就错误
2当Cols(“*”)时会生成 SELECT " * " FROM 这样的句子

**Comment by lunny** [comment]
1. 那如果传的是[]byte呢？
2. 这个时候应该用`AllCols()`

**Comment by lunny** [comment]
1. 这个暂不考虑支持，后面如果有json支持，就无法支持了。
2. Select("*")

暂时先关闭此问题，如果有问题请重开。
