### ISSUE TITLE
xorm.NewSyslogLogger doesn't work

### ISSUE THREAD

**Issue by corvinusy** [go-xorm/xorm#353]
Hello. 
Problem: xorm syslogging doesn't write to system journal. All log messages still spam to console terminal.
Snippet: 

```go
	logWriter, err := syslog.New(syslog.LOG_DEBUG, "rest-xorm-example")
	if err != nil {
		log.Fatalf("Fail to create xorm system logger: %v\n", err)
	}
        s.engine.Logger = xorm.NewSyslogLogger(logWriter)
// next part with usual logger works fine
	// log.SetOutput(logWriter)
	// log.Println("hello rest-xorm-example")
```

Sources: [github.com/corvinusy/rest-xorm-example](https://github.com/corvinusy/rest-xorm-example)

Testing environment: 
Arch Linux: rolling
CPU: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
uname -rm:  4.4.1-2-ARCH x86_64
go version: go version go1.6rc2 linux/amd64
xorm SQL backend: xorm.NewEngine("sqlite3", "/tmp/rest-xorm.sqlite.db")

**Comment by lunny** [comment]
I will check this issue.

**Comment by lunny** [comment]
Please use `engine.SetLogger(logger)` instead of `engine.Logger = logger` And I will change `engine.Logger` to `engine.logger` in next release.

**Comment by corvinusy** [comment]
At this moment 
````go 
engine.SetLogger(logger)
``` 
breaks build with error:
//// cannot use logWriter (type *syslog.Writer) as type core.ILogger in argument to s.engine.SetLogger: *syslog.Writer does not implement core.ILogger (wrong type for Debug method) have Debug(string) error want Debug(...interface {}) error

**Comment by lunny** [comment]
I mean 
```Go
logWriter, err := syslog.New(syslog.LOG_DEBUG, "rest-xorm-example")
    if err != nil {
        log.Fatalf("Fail to create xorm system logger: %v\n", err)
    }
        s.engine.SetLogger(xorm.NewSyslogLogger(logWriter))
```
@corvinusy

**Comment by lunny** [comment]
OKay. I found that's my wrong. Just fix it. Please check again. @corvinusy

**Comment by corvinusy** [comment]
Build fixed. Log gone from terminal. 
But I still haven't found log messages in journal.
May be I should look in deeper.

**Comment by lunny** [comment]
Yes, I just found it.

**Comment by lunny** [comment]
I found if I changed
```Go
logWriter, err := syslog.New(syslog.LOG_DEBUG, "rest-xorm-example")
```
to
```Go
logWriter, err := syslog.New(syslog.LOG_ERR, "rest-xorm-example")
```
The log will be ok. But I don't know the reason.
@corvinusy

**Comment by corvinusy** [comment]
Hey, @lunny 

I've updated my example [github.com/corvinusy/rest-xorm-example](https://github.com/corvinusy/rest-xorm-example) so logging to syslog works fine.

It seems there is no necessity for exported 'SyslogLogger' any more.

**Comment by lunny** [comment]
Yes, I think you are right. `SyslogLogger` will be deprecated.

**Comment by corvinusy** [comment]
So I think the issue has been solved.
Of course, you can use any part of mentioned example for your goals/docs.

**Comment by lunny** [comment]
Thanks.
