### ISSUE TITLE
sync 过多字段同步不成功

### ISSUE THREAD

**Issue by DvHuang** [go-xorm/xorm#354]
type Xorm_item_emition_3 struct {
	ID        int64
	Item_word string
	//快乐
	PA_1      string
	PA_3      string
	PA_5      string
	PA_7      string
	PA_9      string
        //大概一百列........
}

if err3 := Global_val.Xorm_engine.Sync(new(Global_Struct.Xorm_item_emition_3));err3!=nil{
		fmt.Println("Xorm_item_emition_3 error",err)
	}

执行上面的语句之后无法生成表

用CreateTables也无法生成表，结构体字段少时，sync和CreateTables都是起作用的，但是字段多了都不行了。

**Comment by lunny** [comment]
返回的错误信息？

**Comment by davyh9** [comment]
已经解决了谢谢，在群里有人说返回了下面的错误，但是我这里没有返回，确实是改了长度之后就可以了

Error 1118: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs

**Comment by lunny** [comment]
你这个错误是从哪里获得的？

**Comment by DvHuang** [comment]
我也不知道啊哥们儿，在你们提供的群里，有个群友说他那里报了这个错误，然后我问他从哪里出来的，他好像太忙了，没回。
群号：280360085
那位大哥的id：付小黑（你们的群，你可能认识他吧）
谢谢你能这么及时回答我的问题，我后来没看到你的这个信息，所以没回～～

**Comment by fuxiaohei** [comment]
@DvHuang 

已经解决，那我close了
