### ISSUE TITLE
xorm是否能支持sql中虚拟字段和对应struct映射

### ISSUE THREAD

**Issue by officehome** [go-xorm/xorm#356]
xorm目前可以通过定义filed string `xorm"<-"`方式读取数据，但是数据库中依然被创建了filed字段，是否满足在struct中定义了filed字段 而数据库表中不创建该字段，同时又可以通过sql语句把数据映射到struct中？

**Comment by hzmnet** [comment]
这么简单

struct a{
}

struct b{
      a     xorm extand
      name string    // 你的虚拟字段
}
engine.sync2(a)
engine.jioint(xx).find(b)

**Comment by officehome** [comment]
可能需求没有描述清楚
假设
struct a{

id int

name string

field //虚拟字段
}

我需要查询结果为Json格式{id:1,name:"dddd",field:"虚拟字段值"}  而不是需要你提到的{a{};name:"虚拟字段"}这种结构

**Comment by hzmnet** [comment]
你的虚拟字段 值从何而来？虚拟字段是什么定义？

**Comment by mohong122** [comment]
相同的问题

type a struct {
name string
id string
count int `xorm:"-"`
}
在查询时，这个count 可能是count(id)的别名

**Comment by lunny** [comment]
我想本来就是支持的。
