### ISSUE TITLE
core.Row.ScanMap( )似乎包含一个错误。 

### ISSUE THREAD

**Issue by SmarkSeven** [go-xorm/xorm#357]
`
      
    row := engine.DB().QueryRow("select sum(shareTimes) as shareTimes,sum(accessAmount) as accessAmount from participant where userId = ?", params.UserId)

	result := make(map[string]int)

	err := row.ScanMap(&result)
	if err != nil {
		log.Printf("Error: %v \n", err)
		return
	}`
错误如下：
Error: sql: Scan called without calling Next

**Comment by SmarkSeven** [comment]
错误是在这里产生的：
`
   
    func (rs *Rows) ScanMap(dest interface{}) error {

	vv := reflect.ValueOf(dest)

	if vv.Kind() != reflect.Ptr || vv.Elem().Kind() != reflect.Map {
		return errors.New("dest should be a map's pointer")
	}

	cols, err := rs.Columns()
	if err != nil {
		return err
	}

	newDest := make([]interface{}, len(cols))
	vvv := vv.Elem()

	for i, _ := range cols {
		newDest[i] = ReflectNew(vvv.Type().Elem()).Interface()
		//v := reflect.New(vvv.Type().Elem())
		//newDest[i] = v.Interface()
	}
	rs.Rows.Next()
	err = rs.Rows.Scan(newDest...)
	if err != nil {
		log.Println("Just here")
		return err
	}

	for i, name := range cols {
		vname := reflect.ValueOf(name)
		vvv.SetMapIndex(vname, reflect.ValueOf(newDest[i]).Elem())
	}

	return nil
}`

**Comment by SmarkSeven** [comment]
错误是在这里产生的：
func (rs *Rows) ScanMap(dest interface{}) error {

vv := reflect.ValueOf(dest)

if vv.Kind() != reflect.Ptr || vv.Elem().Kind() != reflect.Map {
    return errors.New("dest should be a map's pointer")
}

cols, err := rs.Columns()
if err != nil {
    return err
}

newDest := make([]interface{}, len(cols))
vvv := vv.Elem()

for i, _ := range cols {
    newDest[i] = ReflectNew(vvv.Type().Elem()).Interface()
    //v := reflect.New(vvv.Type().Elem())
    //newDest[i] = v.Interface()
}
rs.Rows.Next()   // 这样修改后调用正常
err = rs.Rows.Scan(newDest...)
if err != nil {
    log.Println("Just here")
    return err
}

for i, name := range cols {
    vname := reflect.ValueOf(name)
    vvv.SetMapIndex(vname, reflect.ValueOf(newDest[i]).Elem())
}

return nil
} @lunny

**Comment by lunny** [comment]
我测试下。
