### ISSUE TITLE
自增字段设置不成功

### ISSUE THREAD

**Issue by DvHuang** [go-xorm/xorm#360]
自增字段设置不成功
结构体如下：
type User_Number_sq struct {
	Id int `xorm:"autoincr"`
	UserName string `xorm:"varchar(120)"`
}

代码：
new_user_number:=new(Global_Struct.User_Number_sq)

new_user_number.UserName=mac[0]

_,err_new_user_number:=Global_val.Xorm_engine.Insert(new_user_number)

if err_new_user_number!=nil{

	fmt.Println("new_user_number,error",err_new_user_number)

}else{

	fmt.Println("new_user_number,ok")
}
错误码 1364 ，某字段没有默认值，也就是应该给new_user_number 中的id赋值，但这个字段已经设置成自增的了，怎么还需要赋值呢？

**Comment by lunny** [comment]
mysql 里面应该是不允许非主键的自增字段的。所以如果是mysql，pk和autoincr应该始终是成对出现。

**Comment by DvHuang** [comment]
解决了，谢谢大哥
