### ISSUE TITLE
Mysql updated()不返回数据库中的数据

### ISSUE THREAD

**Issue by SmarkSeven** [go-xorm/xorm#362]
在执行以下语句时：
affected, err = db.Where("id = ?", c.Data["uid"].(string)).Cols(cols...).Update(&userProfile)

数据更新成功，但是userProfile中没有返回数据库中的数据

版本号 v0.5.1.0301
@lunny

**Comment by lunny** [comment]
本来也不返回啊。

**Comment by lunny** [comment]
暂时先关闭了，如果有问题请随时重开。
