### ISSUE TITLE
Insert 数组的时候, Omit方法不起作用

### ISSUE THREAD

**Issue by shengzhi** [go-xorm/xorm#364]
使用版本: v0.5.2.0303
数据库: MS SQL Server 2012

**Comment by shengzhi** [comment]
试着改了一下, 是因为column name大小写的问题
文件: session.go
line: 2213 & 2261

**Comment by lunny** [comment]
能PR下吗？ @shengzhi

**Comment by lunny** [comment]
请确认下是否解决。@shengzhi

**Comment by shengzhi** [comment]
@lunny , 不好意思, 最近项目赶, 没来得及回复, 我本地测试可以的

**Comment by lunny** [comment]
谢谢。
