### ISSUE TITLE
engine.go LINE 132 conflict with statement.go LINE 870

### ISSUE THREAD

**Issue by extrame** [go-xorm/xorm#365]
Quoting of "." execute twice

Generate SQL like：

`source```.```supply_company`

CHN: 最新的对上述132行的更新和原有的上述870的功能重复了

**Comment by lunny** [comment]
确认下是否解决。@extrame

**Comment by extrame** [comment]
需要解决，我们尝试去除了statement.go的LINE 870，目前还没有发现问题，因为没有测试就不提交了，您评估一下吧

发自我的 iPhone

**Comment by lunny** [comment]
5df1bc92dff719bc558db503ee3e3e370bf8a431

**Comment by lunny** [comment]
如果没有问题就先关闭了，随时可重开。
