### ISSUE TITLE
MySQL的Time类型是否能用string返回结果？

### ISSUE THREAD

**Issue by shenli** [go-xorm/xorm#373]
我用最新的xorm代码测试TiDB发现一个panic:
panic: rawValueType is string, value is 11:41:54 [recovered]
	panic: rawValueType is string, value is 11:41:54

goroutine 20 [running]:
testing.tRunner.func1(0xc82025c090)
	/usr/local/go/src/testing/testing.go:450 +0x171
github.com/go-xorm/xorm.(*Session)._row2Bean(0xc82044c780, 0xc82024b4e0, 0xc821423d40, 0x22, 0x22, 0x22, 0x9773e0, 0xc8200ed600, 0xc8213b5868, 0xc8211aa3c0, ...)
	/Users/shenli/workspace/go/src/github.com/go-xorm/xorm/session.go:1800 +0x5186

看了一下源代码，https://github.com/go-xorm/xorm/blob/master/session.go#L1800，发现如果是Time类，就会要求反回结果是time.Time/int/[]uint8 这几种。对于MySQL的Time，实际上对应的是go的Duration，TiDB中是用string返回。
我用go-sql-driver测试了一下mysql，发现用string去scan返回结果是对的，https://gist.github.com/shenli/bebb21bd997284f4b874

**Comment by lunny** [comment]
我已经修正了，但还没提交。你有测试代码吗？@shenli

**Comment by shenli** [comment]
@lunny 可以用最新的TiDB代码 跑一下那个testTypes.go 的case，我是跑这个case的时候发现的。目前TiDB跑完整的xorm test还有问题。所以可以只用那个testTypes来测试。
