### ISSUE TITLE
sql log 输出有疑问

### ISSUE THREAD

**Issue by sipt** [go-xorm/xorm#377]
查询方法：
`err := t.Engine.Cols("id", "disabled", "layoutid", "styleid", "colorid", "typeid", "rebate").Where("disabled = ?", 0).Find(&templates)`

输出log:
`2016-04-15 11:52:45.818 [log.go:37] [I] [sql] [SELECT `id`, `disabled`, `layoutid`, `styleid`, `colorid`, `typeid`, `rebate` FROM `orm_templates` WHERE disabled = ? [0]] [args] %!v(MISSING)`

后面的[args] %!v(MISSING)是啥

**Comment by lunny** [comment]
我这边测试没有这个问题。你更新到最新版本再试下。

**Comment by sipt** [comment]
已经更新到最新了。。。还是有这个问题，只要把where拼完了放进去就不会有问题

**Comment by lunny** [comment]
你这个是自定义的Logger实现吧？

**Comment by sipt** [comment]
前两天把go换成1.6了，不知道为什么就没有这个问题了。。。
