### ISSUE TITLE
Changing SEARCH_PATH in Postgres does not work intermittently

### ISSUE THREAD

**Issue by codefx9** [go-xorm/xorm#379]
Hi,
We are using xorm with great result with Postgres. But we are seeing an issue that happens intermittently. We use non-public schema and run the following command before accessing tables:

`store.Engine.Exec("SET SEARCH_PATH TO \"myschema\"")`

Sometimes, this does not seem to have any effect and queries keep running against the public schema. This will happen on one computer with same code but not on other computers. Then it will sort of fix on its own. Is there something we are doing wrong? Is xorm reusing connections is some way to cause this?

Thanks.

**Comment by codefx9** [comment]
We found out that if we roll back to v0.5.0 for xorm and core package then public schema error goes away. @lunny, can you please revert the schema connection param change and hopefully, we can start using master again.

**Comment by lunny** [comment]
@codefx9, I have remove all the schema code and you can test your code to confirm the issue is fixed. And you can reopen it if your issue is still not resolved.
