### ISSUE TITLE
Cannot use `Find` to access temporary table in in transaction operation

### ISSUE THREAD

**Issue by chiukit** [go-xorm/xorm#381]
type MyObject struct {
    MyParentObject    `xorm:"extends"`
}

func (m MyObject) TableName() string {
    return "my_object"
}

session := db.NewSession()
if err := session.Begin(); err != nil {
    return
}
q="CREATE TEMP TABLE temp1 AS SELECT \* FROM A"
if _, err := session.Exec(q); err != nil {
    return
}

var array []MyObject
if err := session.Find(&array); err != nil {
    return
}

I got an error `pq: relation "public.temp1" does not exist` occur during executing `Find` function in above code.

**Comment by lunny** [comment]
I think maybe you could use `session.Table("temp1").Find(&array)`.

**Comment by lunny** [comment]
I will close this. Please feel free to reopen it.
