### ISSUE TITLE
problem with SQL generation using IN methods

### ISSUE THREAD

**Issue by aerokite** [go-xorm/xorm#384]
I'm trying to check data using **In** method

    has, err := sess.In("status", "success", "pending").Get(&Snapshot{DatabasePHID: dbPhid, Name: snapshotName})

This generates following sql query which is wrong

    SELECT ... FROM "snapshot" WHERE "name" = $1 AND "databasePHID" = $2 AND ("status" IN ($3,$4)) LIMIT 1 [args] [success pending a1 ACID-DB-PG-pizfjre2hvhdqy3]

It should be like

    SELECT ... FROM "snapshot" WHERE "name" = $1 AND "databasePHID" = $2 AND ("status" IN ($3,$4)) LIMIT 1 [args] [a1 ACID-DB-PG-pizfjre2hvhdqy3 success pending ]

Check `status IN (success, pending)` not `(a1 ACID-DB-PG-pizfjre2hvhdqy3)`

**Comment by lunny** [comment]
I have fixed this on builder branch and this branch will be merged to master some time later.

**Comment by lunny** [comment]
This issue has been resolved on https://github.com/go-xorm/xorm/commit/bcc1d3eb5a5393c7bc22f4c6a0d1b58b1325d6ac. Please reopen it if it is still not resolved.
