### ISSUE TITLE
did not create foreign key

### ISSUE THREAD

**Issue by julor** [go-xorm/xorm#392]
I am new to xorm ,I have found a small problem that it didn't create foreign key in postgres 9.2 with the newest xorm.
I am glad ,if anyone could help me.

**Comment by qzyuanmu** [comment]
得贴一下代码！

**Comment by julor** [comment]
type Users struct {
	Uid      string `xorm:"notnull pk UUID"`
	UserName string `xorm:"notnull unique VARCHAR(30)"`
	NickName string `xorm:"notnull VARCHAR(30)"`
	Password string `xorm:"notnull VARCHAR(44)"`
	Email    string `xorm:"notnull unique VARCHAR(80)"`
	P *Profile `xorm:"has_one(profile_uid) varchar(25)"`

	Profile *Profile `xorm:"profile_id UUID"`

	CreatedAt   time.Time `xorm:"notnull TIMESTAMPZ created"`
	UpdatedAt   time.Time `xorm:"notnull TIMESTAMPZ updated"`
	CreatedUser *Users    `xorm:"created_user_id UUID"`
	UpdatedUser *Users    `xorm:"update_user_id UUID"`
}
type Profile struct {
	Uid string `xorm:"notnull pk UUID"`

	User *Users `xorm:"user_id varchar(50)"`

	CreatedAt   time.Time `xorm:"notnull TIMESTAMPZ created"`
	UpdatedAt   time.Time `xorm:"notnull TIMESTAMPZ updated"`
	CreatedUser *Users    `xorm:"created_user_id varchar(50)"`
	UpdatedUser *Users    `xorm:"update_user_id varchar(50)"`
}

**Comment by lunny** [comment]
It's not support `has_one` and foreign key now.

**Comment by julor** [comment]
我测试了可以关联查询，但是数九没有生成外键约束

**Comment by lunny** [comment]
目前没有支持外键

**Comment by julor** [comment]
好吧，我觉得xorm用起来挺好的，会考虑支持不？

**Comment by lunny** [comment]
考虑支持。

**Comment by lunny** [comment]
#141

**Comment by julor** [comment]
好的，谢谢！
