### ISSUE TITLE
希望能增加一个类似scan的方法

### ISSUE THREAD

**Issue by dxvgef** [go-xorm/xorm#395]
只查询一条记录的一个字段，只能用struct去接收感觉浪费资源，希望能增加一个类似Scan的方法用一个自定义的变量去接收，最好是能兼容标准包的sql.NullString，sql.NullBool，sql.NullInt之类的类型就更好了，谢谢！

**Comment by lunny** [comment]
DB().Scan其实有的。

**Comment by lunny** [comment]
最新版本已经可以用Get和Find来操作一般数和数组了。见https://github.com/go-xorm/tests/blob/master/testFind.go#L278
