### ISSUE TITLE
Set Session.IsAutoCommit to true after Commit/Rollback?

### ISSUE THREAD

**Issue by localvar** [go-xorm/xorm#397]
I'd like to reuse one session object for multiple transaction, but failed because `IsAutoCommit` is set to `false` in the first `Begin()` and does not set back to `true` after calling `Commit()` or `Rollback()`.

Is it possible to do this?

**Comment by lunny** [comment]
Yes, I think it's possible. Let me check.

**Comment by lunny** [comment]
Yes, you have to call `session.Begin()` again to begin another transaction. I will close this issue. Please feel free to reopen it if you have any further information.
