### ISSUE TITLE
oracle查询日期条件有bug

### ISSUE THREAD

**Issue by qingyun2016** [go-xorm/xorm#406]
```
err := engine.Where("length(card_no) = ? registering_date >= ? and registering_date < ?", 8, start, end).Find(&clinics)
```

使用上面的语句执行查询，日期条件报错，去掉日期条件，sql语句正常执行：
[xorm] [info]  2016/06/06 16:43:14.718078 [sql] SELECT name, registering_date, card_no FROM clinic_master WHERE length(card_no) = :1 registering_date >= :2 and registering_date < :3 [args] [8 2016-05-01 00:00:00 +0800 CST 2016-06-01 00:00:00 +0800 CST]
ORA-00933: SQL 命令未正确结束

**Comment by lunny** [comment]
你自己的SQL里面缺少AND啊。
