### ISSUE TITLE
Tag 重命名字段

### ISSUE THREAD

**Issue by hzmnet** [go-xorm/xorm#408]
Name string  `xorm:"varchar(25) 'usr_name'"`
Name string  `xorm:"varchar(25) usr_name"` 
好像是等效

是不是说所有没在规则里的字符串都归为字段的重命名？
这样导致乱码也可以别识别为字段名称。也就是没用的Tag 或者自定义的Tag都给搞混乱了！

CompanyId  int64       `field:"many2one(res.company) required(true) string(Current Company) help(The company this user is currently working for.)"` //-- Company

我的字段这样定义 最后XORM识别 “for.)”为 字段名称

由于Insert最终会重新调用XORM的typeMap解析，扩展库无法少量代码替换掉该解析！
有什么方案吗？

**Comment by lunny** [comment]
目前是等效的，但是建议用前者。

**Comment by lunny** [comment]
xorm的tag尽量不要和其它的tag混用。暂时先关掉此issue，有问题请重开。
