### ISSUE TITLE
any way to Sync2 and ignore fields?

### ISSUE THREAD

**Issue by toni-moreno** [go-xorm/xorm#409]
Hi guys.

I would like migrate my app data from a toml  formatted config file to a SQL db with Xorm and I would like to use the same structs as we use now (if possible)

This one:

```
type InfluxConfig struct {
	Host      string `toml:"host"`
	Port      int    `toml:"port"`
	DB        string `toml:"db"`
	User      string `toml:"user"`
	Password  string `toml:"password"`
	Retention string `toml:"retention"`
	iChan     chan *client.BatchPoints
	client    client.Client
	Sent      int64
	Errors    int64
}
```

My struct has data fields (toml:xxxxx) and also runtime fields, (iChan/Client/Sent/Errors) and I would like to map in SQL database only data fields.

```
x, err = xorm.NewEngine("sqlite3", "./mydb.db")
x.Sync2(new(InfluxConfig))
```

There is any way to sync only data ? something like `xorm:ignore` ?

Thank you very much.

**Comment by lunny** [comment]
```Go
xorm:"-"
```

**Comment by toni-moreno** [comment]
Hi @lunny and thank you very much for your fast response.

I 'have now this 

```
type InfluxConfig struct {
	Id        string `xorm:"unique"`
	Host      string `xorm:"host"`
	Port      int    `xorm:"port"`
	DB        string `xorm:"database"`
	User      string `xorm:"user"`
	Password  string `xorm:"password"`
	Retention string `xorm:"retention"`
	Sent      int64  `xorm:"-"`
	Errors    int64  `xorm:"-"`
}
```

There is any way to identify "id" field as unique and also change de name?

something like:

```
	Id        string `xorm:"myid":"unique"`
``` 
??
Thank you very much

**Comment by toni-moreno** [comment]
If I define a struct "field_id" that should match the "id" of other struct?  how can I define foreign keys?

something like...

````
type otherDada struct {
...
...
 influxconfid        string `xorm:"influxconf_id","fk InfluxConfig::Id"`
...
....
}
````

**Comment by lunny** [comment]
Use a quote to define a special name for a field 

   `xorm:"'my_id' unique"`

Xorm still don't support to define a forign key column.

**Comment by toni-moreno** [comment]
ok , thanks a lot!!
