### ISSUE TITLE
匿名结构且空Tag时不应该映射！

### ISSUE THREAD

**Issue by hzmnet** [go-xorm/xorm#412]
匿名结构且空Tag时不应该映射！

现在所有匿名结构都得加"-" 才不会导致错误！

**Comment by lunny** [comment]
这样会出现不一致，因为默认不加"-"才是不需要映射。

**Comment by hzmnet** [comment]
因为默认不加"-"才是不需要映射。这句话好像是说默认是不映射的对吧？

**Comment by lunny** [comment]
I will close this issue. Please feel free to reopen it if you have any further information.
