### ISSUE TITLE
get(s)数据时，如果s有不为零值的属性，s的字段会被当做条件加入sql语句

### ISSUE THREAD

**Issue by myafeier** [go-xorm/xorm#413]
如：cuser:=&User{
Id:1,
Phone:"133333333"
}
	stat,err:=Db.Where("phone=?",self.Phone).Get(cuser)

SQL语句：

SELECT `id`, `phone` FROM `sync_user` WHERE (phone=?) AND (｀id'=? and `phone` = ?) LIMIT 1 [args] [13888888882 1 13888888882]

**Comment by lunny** [comment]
这就是xorm的特性啊。

**Comment by myafeier** [comment]
这是个特性？
如果这是个特性，where的作用岂不是很尴尬？

**Comment by lunny** [comment]
有开关可以屏蔽掉自动条件。`NoAutoCondition`

**Comment by myafeier** [comment]
真棒 ！@lunny
