### ISSUE TITLE
Event hook is not invoked for the anonymous struct

### ISSUE THREAD

**Issue by ruiyang2015** [go-xorm/xorm#417]
If both the anonymous struct and current struct define the event hook, only the child one get triggered.

```
type P struct {
  Pid `xorm:"uuid"`
}

func (p *P) BeforeInsert(){
   fmt.Println("Parent")
}

type C struct {
  C `xorm:"extends"`
  Cid `xorm:"uuid"`
}

func (c *C) BeforeInsert(){
   fmt.Println("Child")
}
```

for above code snippet, only the Child get printed, if not define the child one, parent one will get invoked.
Ideally, both get invoked.

**Comment by lunny** [comment]
In fact, you have to invoke the embedded struct's `BeforeInsert()` yourself,
```Go
type P struct {
  Pid `xorm:"uuid"`
}

func (p *P) BeforeInsert(){
   fmt.Println("Parent")
}

type C struct {
  P `xorm:"extends"`
  Cid `xorm:"uuid"`
}

func (c *C) BeforeInsert(){
   c.P.BeforeInsert()
   fmt.Println("Child")
}
```
If we implemented your idea, it will cost more cpu time to traversing the struct's fields. I think it's no need since your can do that manually and no extra cpu time to cost.

**Comment by lunny** [comment]
I will close this issue. Please feel free to reopen it if you have any further information.
