### ISSUE TITLE
can not call store procedure in mysql

### ISSUE THREAD

**Issue by localvar** [go-xorm/xorm#418]
error message is: Not found table

this bug was introduced by the code change of last 2-3 days

**Comment by lunny** [comment]
Could you paste your example code here?

**Comment by localvar** [comment]
In my side, all query using a store procedure met the issue, below is an example (it is fine under tag v0.5.4, but encounter the issue with latest code)

GetDatabase().Sql("call p_template_heat(?, ?)", buf.String(), arg.Count).Find(&result)
