### ISSUE TITLE
count 和 distinct 翻译的成的sql语句顺序不对。

### ISSUE THREAD

**Issue by smilesometimes** [go-xorm/xorm#421]
## 1 想执行的sql语句

SELECT count(distinct(car_id)) FROM rrc_user.cm_user_scan_record_999 where phone = "15152961999" and disabled = 0;
## 2  用go写的语句

total, err := a.DB["user"].R().Table(tableName).Distinct("car_id").Where("phone = ? and disabled = ?", phone, 0).Count(userRecord)
## 3  翻译出来的sql语句

[sql] SELECT DISTINCT count(*) FROM `cm_user_scan_record_999` WHERE phone = ? and disabled = ? [args] [15152961999 0]
## 4 问题

发现count 和 distinct的位置不对。

**Comment by smilesometimes** [comment]
#  暂时有两个方法解决

## 1 通过find

err = a.DB["user"].R().Table(tableName).Distinct("car_id").Desc("scan_time").Where("phone = ? and disabled = ?", phone, 0).Find(&scanRecords) 
然后通过 len(scanRecords)获得

## 2 通过query

var sql string = "SELECT COUNT(DISTINCT(car_id)) FROM " + tableName + " WHERE disabled = 0 AND phone = " + phone
a.DB["user"].R().ShowSQL(true)
result, err =  a.DB["user"].R().Query(sql)
var recordCount int64
countString := string(result[0]["COUNT(DISTINCT(car_id))"])
recordCount, err = strconv.ParseInt(countString,10,64)

**Comment by lunny** [comment]
I think current master branch have been resolved your issue. Please test again.
