### ISSUE TITLE
DropTableSql 并没有使用Quote函数获得引号

### ISSUE THREAD

**Issue by hzmnet** [go-xorm/xorm#427]
func (db *Base) DropTableSql(tableName string) string {
    return fmt.Sprintf("DROP TABLE IF EXISTS `%s`", tableName)
}

某些数据库只支持双引号比如Pg

**Comment by lunny** [comment]
The quote \` will be replace to dialect SQL quote characters. I will close this issue. Please feel free to reopen it if you have any further information.
