### ISSUE TITLE
查询的时候字段正确，查询的时候，字段不正确。

### ISSUE THREAD

**Issue by xubing** [go-xorm/xorm#433]
我在使用xorm创建表和插入数据的时候，都是正常的，但是在查询的时候，打印出来的sql语句中的查询字段都不存在。不知道为何。 直接上代码和log
 我在结构中定义的是CreatedAt UpdatedAt 结果，插入正确，但是查询的时候不知道为什么名称变成Createddata   Lastlogindata 

//login 的结构定义
```Golang

type Login struct {
	Id            int64       `xorm:"not null pk autoincr INTEGER"`
	CreatedAt     time.Time `xorm:"TIMESTAMPZ created "`
	UpdatedAt     time.Time `xorm:"TIMESTAMPZ created"`
	DeletedAt     time.Time `xorm:"index TIMESTAMPZ created" `
	LastloginAt   time.Time `xorm:"TIMESTAMPZ created updated"` 
	Isactive      int       `xorm:"BOOL"`
	Isbanned      int       `xorm:"BOOL"`
	Tel           string    `xorm:"TEXT"`
	Pwd           string    `xorm:"TEXT"`
	ActiveCode    string    `xorm:"TEXT"`
	Username      string    `xorm:"TEXT"`
	Online        int       `xorm:"INTEGER"`
	AccessToken   string    `xorm:"TEXT"`
	AccessTime    int64
	RefreshToken  string    `xorm:"TEXT"`
	RefreshTime   int64
	Steps         int       `xorm:"INTEGER"`
	Complete      bool      `xorm:"BOOL"`
	Type          int       `xorm:"INTEGER"`
	UUID          string    `xorm:"TEXT"`
}

``` 

//插入一条数据的sql对应的日志

`
2016/07/29 00:43:39.807228 [sql] INSERT INTO "Login" ("CreatedAt","UpdatedAt","DeletedAt","LastloginAt","Isactive","Isbanned","Tel","Pwd","ActiveCode","Username","Online","AccessToken","AccessTime","RefreshToken","RefreshTime","Steps","Complete","Type","UUID") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "Id" [args] [2016-07-29T00:43:39.807146233+08:00 2016-07-29T00:43:39.807154064+08:00 2016-07-29T00:43:39.807156863+08:00 2016-07-29T00:43:39.807159438+08:00 0 0 1234  2596996162  0 523c0002206fea2954870048ef5b349a 1469731419 81dc9bdb52d04dc20036dbd8313ed055 1472316219 0 false 0 bfa5aa5d2f53586a01761bc154eb7ef9]**
`

// 我查询的代码

```
var login model.Login
has, err := ffdb.FFDB.Where("Tel=?", “1234”).Get(login)**
```

//查询时候的sql log

```
**[xorm] [info]  2016/07/29 00:43:39.812839 [sql] SELECT "Createddata", "Lastlogindata", "Isactive", "Isbanned", "Pwd", "Active", "Userid" FROM "Login" WHERE Tel=$1 LIMIT 1 [args] [1234]
error: pq: column "Createddata" does not exist**

```

**Comment by lunny** [comment]
Hi, Could you format your code? I cannot read that exactly.

**Comment by xubing** [comment]
重新格式化了。我查看输出的sql 语句，插入正常。用where进行查询的时候，输出的sql语句中字段是不存在的。

**Comment by lunny** [comment]
你的model是不是导入到不同的路径了？

**Comment by xubing** [comment]
谢谢。大意了。我另外一个工程的，IDEA自动帮我导入的，我没有发现。

**Comment by xubing** [comment]
Thanks for your suggestion

**Comment by xubing** [comment]
不过我现在用这个代码，仍旧提示一个tel列不存在。我查看数据库Tel存在，sql log中也是Tel，

**代码** 

```
telnumber :=   "1234"//ctx.Param("Tel")
	var login model.Login
	has, err := ffdb.FFDB.Where("Tel=?", telnumber).Get(login)

```

**sql log日志：**

```
[xorm] [info]  2016/07/29 13:41:28.567925 [sql] SELECT "Id", "CreatedAt", "UpdatedAt", "DeletedAt", "LastloginAt", "Isactive", "Isbanned", "Tel", "Pwd", "ActiveCode", "Username", "Online", "AccessToken", "AccessTime", "RefreshToken", "RefreshTime", "Steps", "Complete", "Type", "UUID" FROM "Login" WHERE Tel=$1 LIMIT 1 [args] [1234]
error: pq: column "tel" does not exist

```

**Comment by xubing** [comment]
我发现如果我用**SetMapper(core.SameMapper{})**这个就出现上面的问题。如果换成
core.SnakeMapper或者 core.GonicMapper就没有这个问题。

**Comment by lunny** [comment]
```Go
has, err := ffdb.FFDB.Where("`Tel`=?", telnumber).Get(&login)
```
把你的参数用Quote包含起来。
