### ISSUE TITLE
core.Table 需要以个可以记录旧Column名称的地方!

### ISSUE THREAD

**Issue by hzmnet** [go-xorm/xorm#434]
core.Table 需要以个可以记录旧Column名称的地方!

当传递core.Table时没有一个地方可以记录旧字段名称以便生成修改名称的SQL

**Comment by lunny** [comment]
没看明白

**Comment by hzmnet** [comment]
我的意思是和索引和唯一一样 添加一个记录旧Column名称的地方  ,以便生成修改Column名称的SQL

目前XORM 不是不支持修改Column名称吗?
