### ISSUE TITLE
Tables/Indexes trying to be recreated when not using the 'public' PostgreSQL schema

### ISSUE THREAD

**Issue by jerrykan** [go-xorm/xorm#436]
This is actually an issue I am experiencing with using the [gogs](https://github.com/gogits/gogs/) project, but the problem seems to be with xorm, so I'm reporting it here. Most of the specific details can be found in the original gogs issue (gogits/gogs#3359).

My best guess is that xorm seems to be overriding or ignoring the `search_path` set for the user connecting to the database.

**Comment by lunny** [comment]
This is related to #5
