### ISSUE TITLE
xorm支持分表吗， 或者有什么方法

### ISSUE THREAD

**Issue by cyuxlif** [go-xorm/xorm#438]
例如有1000万用户生成数据，每个用户1万条数据， 根据用户id维度分表。 这个时候使用xorm时该怎么写

**Comment by lunny** [comment]
有几种方法，一个是利用struct的TableName方法，一个是利用engien.Table().方法。

**Comment by cyuxlif** [comment]
@lunny  谢谢， 已使用TableName方法
