### ISSUE TITLE
.In and .Update(x, y) do not work togather

### ISSUE THREAD

**Issue by sadlil** [go-xorm/xorm#440]
The update query with In seems like not working

``` go
s.Engine.
    In(`"required"`, Required).
    Update(&Table{Status: postStatus}, &Table{Status: preStatus})
```

Generated SQL

```
UPDATE "name" SET "status" = $1, "dateModified" = $2 WHERE "status" = $3 AND ("required" IN ($4)) [args] [ALTER 1471420094 invalues OPEN]
```

The in values must be the `$4` args in the sql.

**Comment by lunny** [comment]
This is a bug on master branch. And I have fixed it on branch builder, I will merge builder to master some time later.

**Comment by sadlil** [comment]
merging this would be great.

**Comment by lunny** [comment]
I have merged it to master. Please check if the issue is resolved.

**Comment by lunny** [comment]
I thinks this issue have been resolved by current master. I will close this issue. Please feel free to reopen it if you have any further information.
