### ISSUE TITLE
engine.Cols() 和 ID() 无法生成update语句

### ISSUE THREAD

**Issue by shawnye** [go-xorm/xorm#442]
代码:
<pre>

type User struct {
	Id      int    `json:"id" xml:"id" form:"id"`
	Account string `json:"account" xml:"account" form:"account"`

	Name     string `json:"name" xml:"name" form:"name"`
	Password string `json:"password" xml:"password" form:"password"` //md5-ed

	LoginIp   string    `json:"loginIp" xml:"loginIp" form:"loginIp"`
	LoginTime time.Time `json:"loginTime" xml:"loginTime" form:"loginTime"`

	Status string `json:"status" xml:"status" form:"status"`
	Remark string `json:"remark" xml:"remark" form:"remark"`

	CreateTime time.Time `json:"createTime" xml:"createTime" form:"createTime"`
}

//----------------------------------------------------------
user:= &{Id:1, LoginIp:"127.0.0.1", LoginTime:time.Now() }
engine.ID(user.Id).Cols("LoginIp", "LoginTime").Update(user)
</pre>

生成语句:
<pre>
[xorm] [info]  2016/08/25 10:21:30.418506 [sql] UPDATE `spm_user` SET   - took: 0s
</pre>

百思不得其解中...

**Comment by lunny** [comment]
所有在双引号里面的，都应该填数据库中的字段名。`Cols("login_ip", "login_time")`

**Comment by shawnye** [comment]
非常感谢!

我修改代码为:

`engine.ID(user.Id).Cols("login_ip", "login_time").Update(user)`

但是没有生成where id=? , ID()似乎无用? 谢谢
<pre>
[xorm] [info]  2016/08/25 15:00:19.789371 [sql] UPDATE `spm_user` SET `login_ip` = ?, `login_time` = ?
</pre>

**Comment by lunny** [comment]
ID方法是给primary key使用的，你的没有被标记为primary key。要么标记下，要么用`Where("id = ?", id)`

**Comment by shawnye** [comment]
谢谢.

在struct中标记primary key 吗? 
在数据库表中是有标记的:
<pre>
create table spm_user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    account varchar(64) not null unique,   --帐号
    name varchar(256), 		--名称
   ...
</pre>

**Comment by lunny** [comment]
结构体中
```Go
type User struct {
    Id      int    `json:"id" xml:"id" form:"id" xorm:"pk autoincr"`
    ...
}
```

**Comment by lunny** [comment]
@shawnye  Is the issue still there?

**Comment by lunny** [comment]
I close this currently. And if you have any further question, please reopen it.
