### ISSUE TITLE
xorm支持mysql的存储过程和函数吗?

### ISSUE THREAD

**Issue by zhqqqy** [go-xorm/xorm#446]
我用xorm的Exec函数执行存储过程的sql语句的时候好像不能解析DELIMITER //这句的含义，
我的存储过程的sql是
DELIMITER //
CREATE PROCEDURE demo_in_parameter(IN p_in int)
BEGIN
SELECT p_in;
SET p_in=2;
SELECT p_in;
END //
DELIMITER ;
执行的时候会报
"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server ver sion for the right syntax to use near 'DELIMITER // CREATE PROCEDURE demo_in_parameter(IN p_in int) BEGIN SELECT p_in; ' at line 1"

**Comment by lunny** [comment]
这个是底层驱动支持的
