### ISSUE TITLE
可不可以把主键Id改为ID？

### ISSUE THREAD

**Issue by shookgao** [go-xorm/xorm#447]
`如果field名称为Id而且类型为int64并且没有定义tag，则会被xorm视为主键，并且拥有自增属性。`
这个Id不符合go语言的书写规范，每次这样写结构体的时候编辑器都会警告，可否把默认的Id改为ID？
虽然这个问题可以用Tag来解决，不过还是不方便的。

**Comment by lunny** [comment]
可以新增：如果是SameMapper或者GonicMapper并且ID和int64的自动为主键。

**Comment by lunny** [comment]
I think this have been resolved but document is not updated, please see the tests https://github.com/go-xorm/tests/blob/master/testID.go. I will close this issue, please feel free if you have any more question.

**Comment by shookgao** [comment]
Thanks!
