### ISSUE TITLE
xorm oracle驱动时join表操作和给表取别名时的问题

### ISSUE THREAD

**Issue by Jasonzz-he** [go-xorm/xorm#448]
roc1 := new(Roc)
    has, err := util.Engine.Table(`RPM_PAR_ROC`).Alias(`t`).
        Join("LEFT", []string{"RPM_DIM_PRODUCT", "t1"}, "t.PRODUCT = t1.PRODUCT_CODE").
        Get(roc1)
这段代码生成的sql是：
SELECT \* FROM (
     SELECT *,ROWNUM RN FROM (
SELECT \* FROM "RPM_PAR_ROC" "t" LEFT JOIN "RPM_DIM_PRODUCT" AS "t1" ON t.PRODUCT = t1.PRODUCT_CODE) at WHERE ROWNUM <= 1) aat WHERE RN > 0

这里拼接的sql应该是select aat.*,rownum rn from 
还有我的 表名 和 别名 不应该有双引号

**Comment by jjjachyty** [comment]
顺便提一下 oracle数据库 join查询form生成sql为：
SELECT *
FROM "RPM_BIZ_LN_COLTD_PRICING" "blcp_"
LEFT JOIN "RPM_BIZ_LN_COLTD_BUSINESS" AS "blcb_"
ON "blcp_".BUSINESS_CODE = "blcb_".BUSINESS_CODE
WHERE "blcp_".STATUS    != '0'
ORDER BY "blcp_"."CREATE_TIME" DESC

这段话：LEFT JOIN "RPM_BIZ_LN_COLTD_BUSINESS" AS "blcb_"
应该去掉AS

**Comment by dawndiy** [comment]
#1355 fixed this issue.
