### ISSUE TITLE
问一个打包的问题

### ISSUE THREAD

**Issue by xubing** [go-xorm/xorm#449]
我本地开发的时候，使用的是sqlite3。本地开发没问题。
服务器上没有golang环境，我直接把本地打包后放在服务器上运行。结果提示
```
error sql: unknown driver "sqlite3" (forgotten import?)
panic: failed to connect database

```

我代码中这样使用的,按照你的demo
```
import (
	"github.com/go-xorm/xorm"
	//_ "github.com/lib/pq"
	"fmt"
	"bingcms/end/model"
	_ "github.com/mattn/go-sqlite3"
	"database/sql"
	"errors"
	//"github.com/go-xorm/core"

	_ "github.com/go-sql-driver/mysql"
)
var FFDB *xorm.Engine
func postgresEngine() (*xorm.Engine, error) {

	return xorm.NewEngine("sqlite3", "./report.db")
｝
```

**Comment by lunny** [comment]
sqlite3驱动是cgo的，应该是不支持跨平台编译的。要么docker编译，要么找台linux编译。

**Comment by lunny** [comment]
这个问题先关闭了。有问题请重开。

**Comment by lengrongfu** [comment]
本地ubuntu，线上centos，在本地能执行批量插入，可是线上执行就报错。sql语句如下：
[xorm] [info]  2017/07/12 11:36:45.345194 [sql] INSERT INTO `user_role` (`user_id`,`role_id`) VALUES (?,?),(?,?) [args] [12 1 12 2]
[xorm] [info]  2017/07/12 11:36:45.345237 [sql] ROLL BACK

**Comment by lunny** [comment]
@lengrongfu 看下mysql的版本和配置

**Comment by lengrongfu** [comment]
@lunny 我用的是sqlite3,版本是最新版，本地系统的ubuntu，线上centos
