### ISSUE TITLE
Example for CreateIndexes/CreateUniques

### ISSUE THREAD

**Issue by dmke** [go-xorm/xorm#452]
Hello,

given this struct:

```go
type RuleMapping struct {
    RuleId     int64  `xorm:"not null index"`
    MacAddress string `xorm:"not null index"`
}
```

I would like to add the following unique index:

```sql
CREATE UNIQUE INDEX idx_whatever ON RuleMapping(RuleId, MacAddress)
```

How do I achieve this with [`Engine.CreateUniques`](https://github.com/go-xorm/xorm/blob/db48d70/engine.go#L1239)?

The [documentation](http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-03/3.indexes.html) is somewhat sparse on this topic, and I cannot figure out, how [`Session.CreateUniques`](https://github.com/go-xorm/xorm/blob/4c7f48f/session.go#L583) works...

**Comment by lunny** [comment]
```Go
engine.CreateUniques(new(RuleMapping))
```
The same to the `session`.

**Comment by dmke** [comment]
Hm. So that only creates an index on those colums with `xorm:"index"` struct tagging, right?

I need a programmatic way to create a new unique index, composed over multiple columns. I guess I have to resort to something like this?

```go
engine := xorm.NewEngine("driver", "source")
engine.Sync(new(RuleMapping))

engine.Query("CREATE UNIQUE INDEX IF NOT EXIST idx_name ON RuleMapping (RuleId, MacAddress)")
```

If so, what is the best way to figure out the column names, if I decide to change the mapping to something like

```go
type RuleMapping struct {
    RuleId int64 `xorm:"rule_number not null index"`
    // ...
}
```

i.e. `RuleId` → `rule_number`?

**Comment by lunny** [comment]
For the first question, name the two fields tags with the same index name, just like below, then `CreateIndexs` will create a composed index over the two columns.
```Go
type RuleMapping struct {
    RuleId int64 `xorm:"rule_number not null index(index_name)"`
    MacAddress string `xorm:"index(index_name)"
}
```

The second, yes, you'r right. This is the easiest way to do that. And if you have a specified name for a column, add single quote to the column name. i.e. 
```Go
type RuleMapping struct {
    RuleId int64 `xorm:"'rule_number' not null index(index_name)"`
    MacAddress string `xorm:"index(index_name)"
}
```

**Comment by dmke** [comment]
Okay, thank you!
