### ISSUE TITLE
int64自動新增時間的tag有問題

### ISSUE THREAD

**Issue by li76168** [go-xorm/xorm#465]
在目前這個提交上 8ea3308 新增時間都是0

我回復到9/21 bcc1d3eb5a5393c7bc22f4c6a0d1b58b1325d6ac 是正常的

謝謝

**Comment by lunny** [comment]
I think this issue have been resolved in current master. Could you test it?

**Comment by li76168** [comment]
It is working, thanks.

**Comment by lunny** [comment]
Thanks!
