### ISSUE TITLE
pg数据库UUID主码生成

### ISSUE THREAD

**Issue by bullub** [go-xorm/xorm#466]
> 模型

![image](https://cloud.githubusercontent.com/assets/5164246/19277022/d960b6f0-900a-11e6-9c76-10b7fe5c1d25.png)

> 插入数据的代码

![image](https://cloud.githubusercontent.com/assets/5164246/19277044/f15d6d8e-900a-11e6-8b1c-80be0bbf43c8.png)

> 报错内容

![image](https://cloud.githubusercontent.com/assets/5164246/19277058/01c85864-900b-11e6-8bb2-5a1d4d138676.png)

希望能给其它数据库也提供一下UUID/GUID等常用生成策略

**Comment by lunny** [comment]
这是因为postgres默认不带uuid函数

**Comment by lunny** [comment]
你可以先安装`uuid_generate_v4()`函数支持，方法自己搜索。然后
```
type User struct {
	Id   string `xorm:"pk uuid DEFAULT uuid_generate_v4()"`
	Name string `xorm:"varchar(20)"`
}

_, err = engine.Omit("id").Insert(&User{
		Name: "test",
	})
```
应该就可以了。

**Comment by lunny** [comment]
Have your question been resolved? I will close this issue. Please feel free to reopen it if you have any further information.
