### ISSUE TITLE
created updated tag for session.Insert method not implemention

### ISSUE THREAD

**Issue by bullub** [go-xorm/xorm#468]
>如下图中,`time.Time`上写的`created`和`updated`，在调用`session.Insert`方法进行插入的时候，不会自动填充当前时间，而`session.InsertMulti`方法运行正常

![image](https://cloud.githubusercontent.com/assets/5164246/19306407/1a4b6532-90a8-11e6-8744-3a8abf61e0d4.png)

**Comment by cctse** [comment]
It ocasionally not work on INSERT too,  I updated xorm last night
