### ISSUE TITLE
log 链接池大小 等第一次初始化成功后可以动态更改？

### ISSUE THREAD

**Issue by piaohailin** [go-xorm/xorm#473]
1、当得到NewEngine后就可以调用 log 连接池大小设置，在应用的运行态中是不是可以动态的修改？
2、如果把log  连接池大小封装自定义 NewEngine 中，那么应用每次调用NewEngine会不会重新加载一次配置文件，log设置等？
3、应用把NewEngine封装成单例，对操作数据有或并发性能有影响吗？

**Comment by lunny** [comment]
1. 可以动态修改，但是要注意自己加锁
2. NewEngine只是创建一个内存对象，不会重新加载配置文件
3. 没有影响

**Comment by piaohailin** [comment]
多谢。
关于第二个问题，如果是不会重新加载配置文件象就没有必要在封装单例了。做一个薄封装把初始化的杂七杂八的放到一起就可以了。

**Comment by lunny** [comment]
没必要每次都重新初始化
