### ISSUE TITLE
Need to make clear the designation of session.Before()

### ISSUE THREAD

**Issue by corvinusy** [go-xorm/xorm#476]
Hey. Just a question.

Can we use session.Before(closure) method to update some field in query (for example, replace time.Time by unixtime value). If we can then how to do this properly with Before()?

Is there any doc/info about such methods?

Thank you.

**Comment by lunny** [comment]
There are two ways to do that, one is 
```Go
type Box struct {
     Name string
}

func (b *Box) BeforeFind() {
     
}

engine.Find(&boxes)
```

Another way is temporarily when called `Find`,

```Go
engine.Before(func(box interface{}) {
    b := box.(*Box)
}).Find(&boxes)
```

you can find the doc here
http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-12/

or you can send a PR to github.com/go-xorm/manual-en-US

**Comment by lunny** [comment]
There are two ways to do that, one is 
```Go
type Box struct {
     Name string
}

func (b *Box) BeforeUpdate() {
     
}

engine.Id(id).Update(&box)
```

Another way is temporarily when called `Update`,

```Go
engine.Before(func(box interface{}) {
    b := box.(*Box)
}).Id(id).Update(&box)
```

you can find the doc here
http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-12/

or you can send a PR to github.com/go-xorm/manual-en-US

**Comment by lunny** [comment]
I will close this issue. Please feel free to reopen it if you have any further information.
