### ISSUE TITLE
x.ShowSQL(true)打印初始化问题？每一次应用调用才能打印

### ISSUE THREAD

**Issue by piaohailin** [go-xorm/xorm#478]
1、
// XormInit 初始化xorm组件，跟随应用启动初始化
func XormInit(config _setting.DBCfg) {
    dbconfig = config
    x, err = NewEngine()
    x.TZLocation, _ = time.LoadLocation("Asia/Shanghai")
        *_x.ShowSQL(true)                      //注意放在这里不能执行sql打印**
       。。。。。
    x.Logger().SetLevel(core.LOG_DEBUG)
    x.SetMaxIdleConns(config.SetMaxIdle)
    x.SetMaxOpenConns(config.SetMaxOpen)
}
2、
// NewEngine 应用得到x对象
func NewEngine() (x _xorm.Engine, err error) {
        。。。。。。。
    x, err = xorm.NewEngine(config.Type, cnnstr)
    *_x.ShowSQL(true)     //应用每次执行都会调用，此时才能正确打印。**

```
return x, err
```

}

这是bug吗？

**Comment by lunny** [comment]
x.ShowSQL(true)只要调用一次就可以了。

**Comment by piaohailin** [comment]
目前一致是用第二种方式才能打印，难道与我用到seelog有冲突？

**Comment by lunny** [comment]
I will close this issue. Please feel free to reopen it if you have any further information.
