### ISSUE TITLE
TAG “updated”和“varchar” 定义cloumn无效？

### ISSUE THREAD

**Issue by luopengift** [go-xorm/xorm#479]
定义如下：
type Test struct {
   Id      int64
  Name    string `xorm:"varchar(1024)"`
   Updated time.Time `xorm:"updated"`
}

完成后，查询建表语句和表结构，与希望的不一样：

mysql> show create table test\G;
*************************** 1. row ***************************
       Table: test
Create Table: CREATE TABLE `test` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(1024) DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
1 row in set (0.00 sec)

请问，是我哪个地方设置的不对吗？

**Comment by lunny** [comment]
哪里不对？

**Comment by luopengift** [comment]
我看文档的解释：“updated”这个Field将在Insert或Update时自动赋值为当前时间。可是我在新增或者修改数据的时候，Updated字段的值都是NULL，并没有赋值为当前时间。

**Comment by lunny** [comment]
你的xorm版本？升级到最新版本看下。

**Comment by luopengift** [comment]
已升级至“v0.6.0.1022”，还是无法解决自动赋值当前时间的问题。

**Comment by luopengift** [comment]
使用engine.Insert()正常，时间能自动赋值。使用Exec()不行...

**Comment by lunny** [comment]
Exec是不管的
