### ISSUE TITLE
Update的时候使用Omit无效

### ISSUE THREAD

**Issue by haitgo** [go-xorm/xorm#480]
我使用场景是这样的
database.Engine.Omit("SiteId", "HexAddr").Id(this.SiteId).Update(this)
打印的sql语句是
 UPDATE `cn_site` SET `SiteName` = ?, `DatabaseId` = ?, `Comment` = ?, `IntervalTime` = ?, `HexAddr` = ?, `UseStatus` = ? WHERE `SiteId`=? [args]
HexAddr没有被去掉

**Comment by lunny** [comment]
Is this resolved already?

**Comment by haitgo** [comment]
it seems ok

**Comment by haitgo** [comment]
已发现问题并重新提交了issue
