### ISSUE TITLE
mysql字段有一个默认字段设置了0,插入的时候变成了1,再次修改就不能变成0了呢？

### ISSUE THREAD

**Issue by zouhuigang** [go-xorm/xorm#496]
Newslist_tpl默认设置了0

type Anote struct {
	Id            int       `json:"id" xorm:"pk autoincr" `
	Cover         string    `json:"cover"`
	Title         string    `json:"title"`
	Content       string    `json:"content"`
	Commentnum    int       `json:"commentnum"`
	Uid           int       `json:"uid"`
	Newslist_tpl  int       `json:"newslist_tpl"`
	Ctime         time.Time `json:"ctime"  xorm:"created"`
	Is_open       int       `json:"is_open"`
	Password_code string    `json:"password_code"`
}

notes.Newslist_tpl = 0
_, err = MasterDB.Id(notes.Id).Update(notes)

**Comment by zouhuigang** [comment]
好吧，知道了。用engine.Id(1).AllCols().Update(&user)。这字段也太坑爹了。不能做成指定了字段就更新，没指定就不更新吗？

**Comment by lunny** [comment]
Hi, if you set it to 0, it cannot be determined since Golang's limitation. I will close this issue. Please feel free to reopen it if you have any further information.
