### ISSUE TITLE
xorm 工具下载 404

### ISSUE THREAD

**Issue by zjxpcyc** [go-xorm/xorm#501]
下载这个工具需要翻墙吗？怎么下载是 404 呢？

**Comment by lunny** [comment]
Show your download URL.

**Comment by zjxpcyc** [comment]
@lunny 
`got go-xorm/cmd/xorm`
不过，使用源码安装是好的，我用源码安装过了，谢谢！

**Comment by lunny** [comment]
github.com/go-xorm/cmd@b601a5b 已经更新了README
