### ISSUE TITLE
使用pk autoincr  id不是按1自增的 

### ISSUE THREAD

**Issue by reechou** [go-xorm/xorm#505]
id是增长的，但是是随机增加的，不是每个都自增1  怎么设置？
![image](https://cloud.githubusercontent.com/assets/949857/21090296/b81a934a-c079-11e6-8d9f-1c6761c66969.png)

**Comment by lunny** [comment]
你自己逆序排序了啊

**Comment by reechou** [comment]
是的啊  我的意思是 每次insert之后  id不是连续的

**Comment by lunny** [comment]
生成的SQL贴下

**Comment by reechou** [comment]
type Account struct {
	ID             int64   `xorm:"pk autoincr"`
	UnionId        string  `xorm:"not null default '' varchar(128) unique"`
	Phone          string  `xorm:"not null default '' varchar(16)"`
	Name           string  `xorm:"not null default '' varchar(128)"`
	Status         int64   `xorm:"not null default 0 int"`
	CreatedAt      int64   `xorm:"not null default 0 int index"`
	UpdatedAt      int64   `xorm:"not null default 0 int"`
}

**Comment by lunny** [comment]
SQL

**Comment by reechou** [comment]
CREATE TABLE `fx_account` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `union_id` varchar(128) NOT NULL DEFAULT '',
  `phone` varchar(16) NOT NULL DEFAULT '',
  `name` varchar(128) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `status` int(11) NOT NULL DEFAULT '0',
  `created_at` int(11) NOT NULL DEFAULT '0',
  `updated_at` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQE_fx_account_union_id` (`union_id`),
  KEY `IDX_fx_account_superior` (`superior`),
  KEY `IDX_fx_account_sign_time` (`sign_time`),
  KEY `IDX_fx_account_created_at` (`created_at`),
  KEY `IDX_fx_account_all_score` (`all_score`)
) ENGINE=InnoDB AUTO_INCREMENT=5881 DEFAULT CHARSET=utf8;

**Comment by lunny** [comment]
xorm生成的Insert语句啊

**Comment by micanzhang** [comment]
@reechou  加一下输出 SQL 的代码:

```
engine.ShowSQL(true)
```

**Comment by micanzhang** [comment]
这个有可能是数据库的配置决定的，你可以参考一下: http://stackoverflow.com/questions/23022574/why-the-auto-increment-id-does-not-increase-one-by-one-how-to-set-it

你可以通过 mysql client 查看: 

```
SHOW VARIABLES like 'auto_increment_increment';
```

预期或有类似如下的结果:

```
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| auto_increment_increment | 3     |
+--------------------------+-------+
1 row in set (0.11 sec)
```
