### ISSUE TITLE
xorm可以不定义struct直接把JSON 按照表格列名进行序列化然后插入吗

### ISSUE THREAD

**Issue by lyb124553153** [go-xorm/xorm#512]
RT 想写个工具，直接把table里面的数据全部取出，保存成JSON文件，然后再序列化插入到数据库里面，但是table躲起来以后struct就要写很多，可以直接根据table名，再内存中生成动态的STRUCT格式，然后把JSON encode一下插入到表吗

**Comment by lunny** [comment]
可以的。1.8可以动态创建struct。

**Comment by lauyoume** [comment]
有例子么？

**Comment by lauyoume** [comment]
有例子么？
