### ISSUE TITLE
In(..) clause with empty collection has no affect

### ISSUE THREAD

**Issue by ethantkoenig** [go-xorm/xorm#516]
If I do something like `engine.In("my_column", []int64{}).Find(&results)`, every row of the corresponding table will be returned (just like `engine.Find(&results)`). I would instead expect no rows to be returned, since a SQL query with an empty `IN` clause, such as `SELECT * FROM foo WHERE col in (SELECT 0 WHERE 0=1)` returns no rows.

If this is a bug, I would be happy to fix it.

**Comment by lunny** [comment]
Yes, I know this. Keep it no condition or a false condition for empty `In` which one is better?

**Comment by ethantkoenig** [comment]
I personally prefer false condition

**Comment by localvar** [comment]
agree with @ethantkoenig , false condition make sense
