### ISSUE TITLE
是否是阻塞导致的update失败？ 何种办法解决?

### ISSUE THREAD

**Issue by gonboy** [go-xorm/xorm#518]
## **代码：** 
```go
if cnt, err := sql.db.Id(1).Cols("password").Update(&dbUser); err != nil {
    fmt.Println("Update user failed. err = ", err)
} else {
    fmt.Println("Update user ok. cnt = ", cnt)
}
```
## **现象：** 
1. 测试时，浏览器刷新过快   **Update user ok. cnt = 0**
2. 测试时，浏览器正常刷新   **Update user ok. cnt = 1**

## **问题：** 
1. 是否是由于 block 的原因？ 难道每次都要检测 cnt, 判断是否成功吗？
2. 是否有其它的办法来解决此问题？ 是否是采用 session := engine.NewSession() 的方法？

**Comment by gonboy** [comment]
```
找到原因了，是由于 password 如果没有发生变化，则会导致返回 0。用过设置password = counter++, 则每次都是1.
```
**问题是：**
      1. 但是为什么密码相同的话， 连续刷新，cnt = 0 ?
      2. 如果存在乐观锁的话，锁的初始数值一定不改变，err == nil,  cnt 一直是 0。 为什么不报错呢？
      但是单次刷新，确实 cnt = 1 呢 ?

**Comment by lunny** [comment]
如果err==nil，如果有记录改变了，cnt就是1，没改变就是0。err!=nil，此值无意义

**Comment by gonboy** [comment]
了解，thanks
