### ISSUE TITLE
mysql 经常打印tcp  write: broken pipe, 而且xorm也没有打印日志。

### ISSUE THREAD

**Issue by cyuxlif** [go-xorm/xorm#522]
[mysql] 2017/01/12 09:35:09 packets.go:130: write tcp 127.0.0.1:41960->127.0.0.1:3306: write: broken pipe

经常出现以上这种情况 ，执行结果却没有返回error，xorm也没有打印这个日志。

**Comment by lunny** [comment]
这个日志是由驱动打印的。建议查看mysql驱动文档
