### ISSUE TITLE
About mocking ORM returned values (for testing purposes)

### ISSUE THREAD

**Issue by corvinusy** [go-xorm/xorm#528]
Hey.
There is a point with testing that related to ORM erroneous returns for some reason (such as db disconnection, for example). Can a special dialect be introduced (interface "mock" or something like this), where testers could redefine some methods to get desired behaviour?

Of course, this doesn't look like an easy case. But may be xorm developers did keep it mind while designing architecture.

I believe that this will be a great feature.
Thank you.

**Comment by lunny** [comment]
Hi, I have to say. In fact, there is a good tool to do this. `gopkg.in/testfixtures.v2`, below is an example to use it. And more examples you can find in https://github.com/go-gitea/gitea/tree/master/models

```Go
// CreateTestEngine create an xorm engine for testing
func CreateTestEngine() error {
	testfixtures.SkipDatabaseNameCheck(true)
	var err error
	x, err = xorm.NewEngine("sqlite3", "file::memory:?cache=shared")
	if err != nil {
		return err
	}
	x.SetMapper(core.GonicMapper{})
	if err = x.StoreEngine("InnoDB").Sync2(tables...); err != nil {
		return err
	}

	fixtures, err = testfixtures.NewFolder(x.DB().DB, &testfixtures.SQLite{}, "fixtures/")
	return err
}
```

**Comment by corvinusy** [comment]
Tesfixtures is always used for testing and works fine. But it doesn't help with testing adequate reaction of my application if I need to check behaviour on special errors:
- database disconnection
- database corruption
- database error respond (due to bugs in SPs/triggers )
- database response timeout

you can continue the list.

OK, may be I'll try to make a MITM driver
