### ISSUE TITLE
连接mysql进行delete操作报driver: bad connection错误？

### ISSUE THREAD

**Issue by skyleelove** [go-xorm/xorm#532]
你好，
    在使用xorm的时候我这边拼接了一个较大的sql执行删除操作，一段时间内返回了driver: bad connection的错误，过一阵子又恢复正常，请问这是什么问题？

        MasterEngine, err = xorm.NewEngine("mysql", mysqlHost)
	if err != nil {
		return err
	}
	MasterEngine.SetMaxIdleConns(10)
	MasterEngine.SetMaxOpenConns(200)
	MasterEngine.StoreEngine("innodb")
	MasterEngine.Charset("utf8")

**Comment by lunny** [comment]
```Go
MasterEngine.StoreEngine("innodb")
MasterEngine.Charset("utf8")
```
这两句用法不正确。
这个错误是mysql驱动返回的。

**Comment by skyleelove** [comment]
可否提供一个例子如何使用
MasterEngine.StoreEngine("innodb")
MasterEngine.Charset("utf8")

**Comment by lunny** [comment]
MasterEngine.StoreEngine("innodb").Charset("utf8").CreateTable()
