### ISSUE TITLE
请问xorm支持关系映射吗?

### ISSUE THREAD

**Issue by 765643729** [go-xorm/xorm#534]
请问xorm支持关系映射吗?文档里没有提到

**Comment by lunny** [comment]
不支持

**Comment by sqhua** [comment]
不支持才好，OO隐藏了数据库结构，对MIS开发来说并不友好。

**Comment by 765643729** [comment]
@sqhua 你能更多的描述一下原因吗?个人认为orm能使程序员专注于功能开发,不用去管数据库的实现.让orm去管理关联关系,不用让开发去管理中间表."对MIS开发来说并不友好"?不知从何得出的结论.你如果觉得希望自己去管理中间表,完全可以不使用该功能."不支持才好的结论"完全不知道你怎么得出来的?
