### ISSUE TITLE
Oracle的问题

### ISSUE THREAD

**Issue by ahlzhang** [go-xorm/xorm#537]
批量插入时。会报ORA-00933: SQL 命令未正确结束

原因是，oracle的批量插入sql变更造成的。

mysql:
`INSERT INTO a ("id", "name") VALUES (1, "aa"), (2, "bb") `

oracle:
`INSERT ALL INTO a ("id", "name") VALUES (1, "aa") INTO a ("id", "name") VALUES (2, "bb") SELECT 1 FROM DUAL`

**Comment by lunny** [comment]
`SELECT 1 FROM DUAL` 这句是什么意思？

**Comment by ahlzhang** [comment]
应该是定势。。
必须要加，我也做过测试，如果不加的话，执行语句会报错

**Comment by lunny** [comment]
插入单条返回自增呢？
