### ISSUE TITLE
Unable to compile with vendor conflict

### ISSUE THREAD

**Issue by Unknwon** [go-xorm/xorm#553]
Commit https://github.com/go-xorm/xorm/commit/20a684b85a847410b5827e854f71e312ecca31a7 forces any project that uses XORM's `core` and `builder` to have `vendor` directory. Otherwise fail to compile with error:

```
models/models.go:209: cannot use "github.com/go-xorm/core".LOG_WARNING (type "github.com/go-xorm/core".LogLevel) as type "github.com/go-xorm/xorm/vendor/github.com/go-xorm/core".LogLevel in argument to xorm.NewSimpleLogger3
```

Which makes `github.com/go-xorm/core` and `github.com/go-xorm/builder` useless by themselves. And even worse, project needs to vendor twice (one by XORM itself, one by project).

**Comment by lunny** [comment]
This is not a problem if you using `govendor` or other similar tool to manage the dependencies. The tool will merge all the vendors to the root dir's vendor.

**Comment by Unknwon** [comment]
>Commit 20a684b forces any project that uses XORM's core and builder to have vendor directory. 

This is a real problem, project is no longer go-get-able.

**Comment by lunny** [comment]
47cb51d should resolve this, please confirm that.

**Comment by Unknwon** [comment]
Seems worked, thanks!
