### ISSUE TITLE
建议 count 优先获取 statement.AltTableName 表名

### ISSUE THREAD

**Issue by Safircn** [go-xorm/xorm#554]
如题

func Find(sess *xorm.Session, dateList interface{}, page int) (total int64, err error) {
  total, err = sess.Clone().Select("").Count(reflect.New(sess.Statement.RefTable.Type).Interface())
  ShowError(err)
  if total > 0 {
    err = sess.Limit(10, (page-1)*10).Find(dateList)
    ShowError(err)
  }
  return
}

**Comment by lunny** [comment]
Could you give more detail for your issue ?

**Comment by lunny** [comment]
This issue should be resolved in some time. See the test code https://github.com/go-xorm/xorm/blob/master/session_stats_test.go#L135
