### ISSUE TITLE
about sqlite3 time format

### ISSUE THREAD

**Issue by haorendashu** [go-xorm/xorm#556]
why ``` engine.dialect.DBType() == "sqlite3" ``` use ``` v = t.UTC().Format("2006-01-02 15:04:05") ``` to format ``` Time ``` ?

See https://github.com/go-xorm/xorm/blob/master/engine.go#L1538

**Comment by fuxiaohei** [comment]
sqlite3 only doesn't save timezone in datetime. So save utc time string to text
