### ISSUE TITLE
两个表的Id属性相同，可其中一个 在 sync2 表结构同步时，死活不创建主键

### ISSUE THREAD

**Issue by lubaoyilang** [go-xorm/xorm#558]
![fav](https://cloud.githubusercontent.com/assets/10125942/24548597/95147940-1648-11e7-9eb6-73ad2b5186cf.JPG)
![user](https://cloud.githubusercontent.com/assets/10125942/24548603/9b578fcc-1648-11e7-9241-d3e6566a52c1.JPG)

下边是fav表 Debug信息
[xorm] [info]  2017/03/31 19:26:59.068544 [sql] CREATE TABLE IF NOT EXISTS `Favs
List` (`Id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL, `UserId` BIGINT(20)
NOT NULL, `FavId` BIGINT(20) NOT NULL, `GoodsType` INT NOT NULL, `Title` VARCHAR
(255) NOT NULL, `Cover` VARCHAR(255) NOT NULL, `CreateTime` BIGINT(20) NULL, `Ve
rsion` INT NULL DEFAULT 1) DEFAULT CHARSET utf8

下边是 用户表 debug
[xorm] [info]  2017/03/31 19:26:59.261555 [sql] CREATE TABLE IF NOT EXISTS `User
InfoTable` (`Id` BIGINT(20) NOT NULL, `Pwd` VARCHAR(255) NOT NULL, `Phone` VARCH
AR(255) NOT NULL, `Sex` INT NULL, `UserStatus` INT NOT NULL, `Age` INT NULL, `Is
Seller` INT NULL, `AvatarPic` VARCHAR(255) NULL, `NickName` VARCHAR(255) NULL, `
AreaName` VARCHAR(255) NULL, `AreaId` BIGINT(20) NULL, `CreateTime` BIGINT(20) N
ULL, `LoginTime` BIGINT(20) NULL, `Version` INT NULL DEFAULT 1, PRIMARY KEY ( `I
d`,`Phone` )) DEFAULT CHARSET utf8

**Comment by lunny** [comment]
因为你`Phone`上也加了`pk`，应该去掉，而且加了`pk`一般不要加`unique`.
