### ISSUE TITLE
sum 用法

### ISSUE THREAD

**Issue by jerryxjm** [go-xorm/xorm#570]
da.Where.Sum(md, "CASE WHEN ViewSeconds<=Seconds THEN TotalSeconds ELSE Seconds END")
之前的版本支持这种写法，今天更新最新版本后，报错。

case when 语句被加上``，报：Unknown column 'CASE WHEN ViewSeconds<=Seconds THEN TotalSeconds ELSE Seconds END' in 'field list'

**Comment by lunny** [comment]
15f11df resolved #336 not this one.
