### ISSUE TITLE
Defalut 不生效

### ISSUE THREAD

**Issue by porson** [go-xorm/xorm#571]
不知道是我用的方法不对还是什么问题，
给列设置了default值，插入的时候对象并没有进行赋值，然而插入到数据库中的数据为空，
default并没有生效

```
type UserPermissionInfo struct {
	UserEmail        string `xorm:"varchar(64) pk"`
	SaltStack        string `xorm:"varchar(2) default 'N' notnull"`
	ConfigCenter     string `xorm:"varchar(2) default 'N' notnull"`
	UserInfoSelect   string `xorm:"varchar(2) default 'Y' notnull"`
	UserInfoUpdate   string `xorm:"varchar(2) default 'N' notnull"`
	ServerInfoSelect string `xorm:"varchar(2) default 'Y' notnull"`
	ServerInfoUpdate string `xorm:"varchar(2) default 'N' notnull"`
	AppInfoSelect    string `xorm:"varchar(2) default 'Y' notnull"`
	AppInfoUpdate    string `xorm:"varchar(2) default 'N' notnull"`
}

func (p *UserPermissionInfo) Save() bool {
	_, err := Engine.Insert(p)
	if err != nil {
		revel.ERROR.Printf("权限信息插入失败，错误: %v", err)
		return false
	}
	return true
}
```

**Comment by lunny** [comment]
```Go
Engine.Cols(cols...).Insert() // 指定列插入，非指定列将会被数据库设置为默认值
Engine.Omit(cols...).Insert() // 忽略列插入，忽略的列将会被数据库设置为默认值
```
因为Go中无法判断你是插入空还是没有值，所以只能这样。

**Comment by porson** [comment]
感谢！

**Comment by DDtan** [comment]
不知道我的写法是不是对的，麻烦您帮我看下
`
type Product struct {
	Id             int         `json:"id" xorm:"'id'"`
	Name      string     `json:"name,omitempty" xorm:"varchar(40) notnull"`
	Url           string     `json:"url,omitempty" xorm:"varchar(40) notnull"`
	Enable     int          `json:"enable,omitempty" xorm:"varchar(40) notnull"`
	State       int           `json:"start,omitempty" xorm:"int(3) default 1 notnull"`
}
affected, err := db.Omit("state").Insert(&addProduct)
`
Error 1364: Field 'state' doesn't have a default value
