### ISSUE TITLE
join加select过滤在xorm里应该怎样写才对呢？

### ISSUE THREAD

**Issue by jacoblai** [go-xorm/xorm#575]
select ni.node_id,ni.node_name,ni.node_type,ni.node_standard_code,ni.parent_template_id,ni.administrative_level,ni.is_valid 
from tab_flow_node_info as ni
**JOIN (SELECT * from tab_flow_template where template_id=3388872717171163136) as nni ON** ni.parent_template_id=nni.template_id

////上边那样的join加select有什么直接xorm操作能得到这个效果的吗？

**Comment by lunny** [comment]
暂不支持Join子查询

**Comment by lunny** [comment]
duplicated with #388
