### ISSUE TITLE
Join不支持子查询吗？

### ISSUE THREAD

**Issue by zouhuigang** [go-xorm/xorm#591]
SELECT a.id,a.s_names,a.e_names,b.s_num FROM `user_img_cls` AS `a` LEFT  JOIN ( SELECT pid,count(id) as s_num FROM user_gif_bg_cls where is_open=1 GROUP BY pid ) AS `b` ON a.id = b.pid ORDER BY a.is_sort ASC

err = MasterDB.Select("a.id,a.s_names,a.e_names,b.s_num").Table("user_img_cls").Alias("a").
		Join("LEFT ", []string{"( SELECT pid,count(id) as s_num FROM user_gif_bg_cls where is_open=1 GROUP BY pid )", "b"}, "a.id = b.pid").
		OrderBy("a.is_sort ASC").Find(&list)

**Comment by lunny** [comment]
Not supported yet

**Comment by zouhuigang** [comment]
还有如果使用这样的查询，	err = MasterDB.Sql("SELECT a.id,a.s_names,a.e_names,b.s_num FROM `user_img_cls` a LEFT JOIN ( SELECT pid,count(id) as s_num FROM user_gif_bg_cls where is_open=1 GROUP BY pid) b ON a.id=b.pid where 1=1 ORDER BY is_sort asc ").Find(&list)

count这个函数会被转义掉~~。

**Comment by lunny** [comment]
@zouhuigang the second one is a bug I think. Please fire another issue to describe it.

**Comment by zouhuigang** [comment]
好的，谢谢。

**Comment by lunny** [comment]
duplicated with #575
