### ISSUE TITLE
Sql查询,count函数被转义掉

### ISSUE THREAD

**Issue by zouhuigang** [go-xorm/xorm#592]
err = MasterDB.Sql("SELECT a.id,a.s_names,a.e_names,b.s_num FROM user_img_cls a LEFT JOIN ( SELECT pid,count(id) as s_num FROM user_gif_bg_cls where is_open=1 GROUP BY pid) b ON a.id=b.pid where 1=1 ORDER BY is_sort asc ").Find(&list)

count这个函数会被转义掉~~。

变成：
SELECT a.id,a.s_names,a.e_names,b.s_num FROM `user_img_cls` a LEFT JOIN ( SELECT pid,count`id` as s_num FROM user_gif_bg_cls where is_open=1 GROUP BY pid) b ON a.id=b.pid where 1=1 ORDER BY is_sort asc

**Comment by lunny** [comment]
Please paste your count statement.

**Comment by lunny** [comment]
I have write a test on #609 and don't reproduce this issue.
