### ISSUE TITLE
Distinct and limit (top) with mssql 

### ISSUE THREAD

**Issue by 22222** [go-xorm/xorm#593]
In gogs gogits/gogs#4419, using `Distinct` and `Limit` together in MSSQL results in a syntax error.  I think that problem might be coming from xorm?  Possibly from a [Sprintf in statement.go](https://github.com/go-xorm/xorm/blob/6b6721cccc0015ea5275fdb3ae233872e1f654df/statement.go#L1281).

Currently the generated SQL looks like this:

```sql
SELECT TOP 10 DISTINCT ...
```

It should have `DISTINCT` before `TOP`, like this:

```sql
SELECT DISTINCT TOP 10 ...
```

**Comment by lunny** [comment]
@22222 please confirm that #596 fixed this issue.

**Comment by 22222** [comment]
Looks good to me.  I tested with a local copy of gogs (using mssql), and the error stopped after updating to the version of xorm with this fix (the `lunny/fix_mssql_top_distinct` branch).

Thanks for getting a fix in so quickly.
