### ISSUE TITLE
没有SetConnMaxLifetime这个设置

### ISSUE THREAD

**Issue by waterloopwm** [go-xorm/xorm#605]
golang官方的db接口有这个SetConnMaxLifetime设置,xorm没有这个

**Comment by lunny** [comment]
Which Go version are this method added?

**Comment by waterloopwm** [comment]
golang1.5

**Comment by waterloopwm** [comment]
建议把xorm升级到golang1.7或以上，毕竟从1.7版本golang的性能和gc都有很大的提升

**Comment by lunny** [comment]
XORM 应该是兼容go1.1以上版本都可以。如果是go1.5，应该可以加这个方法

**Comment by waterloopwm** [comment]
不明白为什么xorm还要兼容golang的1.1,1.2,1.3,1.4,1.5这些低版本,这些版本的性能和gc不怎么样
