### ISSUE TITLE
session复用

### ISSUE THREAD

**Issue by lesterpang** [go-xorm/xorm#607]
分页查询需求，一堆where条件之后的session，不能复用？比如下面的代码，find和count两次查询，只有第一次的find带where条件，后面的count没有where条件了。
请问怎么实现我的需求？
``` go
session := engine.NewSession()
if a{
	session.Where("...")
}

if b{
	session.Where("...")
}

user := User{}
session.Limit(take, skip).Find(&tables)

count, err := session.Count(new(User))
```

**Comment by lunny** [comment]
当你使用了Find之后，这些条件会被清除。请使用`github.com/go-xorm/builder`来进行条件复用

**Comment by hurisheng** [comment]
builder怎样写orderby？如果查询是包含orderby的，分页查询不能复用session的话，那就比较麻烦了
