### ISSUE TITLE
mssql分页排序问题

### ISSUE THREAD

**Issue by jdongdong** [go-xorm/xorm#610]
使用mssql数据库分页查询排序报错：
mssql: ORDER BY 子句中的列 "account.createDate" 无效，因为该列没有
包含在聚合函数或 GROUP BY 子句中。

**Comment by lunny** [comment]
有详细点的代码吗？这个找不到原因啊。

**Comment by jdongdong** [comment]
主要代码如下：	
session.Table("account").Alias("a")
	if this.Unicode != "" {
		session.And("a.Unicode = ?", this.Unicode)
	}
	if this.Password != "" {
		session.And("a.Password = ?", this.Password)
	}
	if this.Status != "" {
		session.And("a.Status = ?", this.Status)
	}
	if this.LoginKey != "" {
		session.And("(a.Mobile=? or a.AccountName=?)", this.LoginKey, this.LoginKey)
	}
	if this.SearchKey != "" {
		session.And("(a.Mobile like ? or a.AccountName like ?)", toLike(this.SearchKey), toLike(this.SearchKey))
	}
	session.Desc("a.createDate")
        session.Limit(toPaging(this.PageIndex, this.PageSize)).
		Find(item)

**Comment by jdongdong** [comment]
这个问题原因我找到了，是因为mssql在count(*)的时候带了order by条件导致报错，生成的sql如下：
`SELECT count(*) FROM "account" AS "a" WHERE a.RoleId = 1 ORDER BY a.createDate desc`
现在的解决方法是count时把Statement.OrderStr 置成空，这个是算我使用问题还是个bug呢？

**Comment by lunny** [comment]
Order by 的条件不是你自己加的？

**Comment by jdongdong** [comment]
我是在分页的时候共用的同一个session，获取数据的时候需要order by，在count的时候也把order by 自动加上了

**Comment by lunny** [comment]
https://github.com/go-xorm/xorm/blob/master/session_cond_test.go#L269，参考这个里面的用法。

**Comment by jdongdong** [comment]
3q 这个问题已经解决了
