### ISSUE TITLE
Go 1.5 support

### ISSUE THREAD

**Issue by Unknwon** [go-xorm/xorm#611]
Hi, if I want to compile XORM with Go 1.5, it is no longer possible with compile error:

```
vendor/github.com/go-xorm/xorm/engine.go:200: engine.db.SetConnMaxLifetime undefined (type *core.DB has no field or method SetConnMaxLifetime)
```

I'm not sure Go 1.5 is officially dropped support or just didn't notice this problem?

Thanks.

**Comment by lunny** [comment]
I just noticed `SetConnMaxLifetime` is introduced by go1.6, not go1.5 and I will send a PR to fix the requirement. 
I have to say yes, we will drop go1.1 ~ go 1.5 and go1.6 is the minimal requirement.

**Comment by Unknwon** [comment]
AFAIK, back support is just a simple fix to add a file only compile under go1.6 and manually copy code. But that's OK if you don't want, thanks for the confirmation.
