### ISSUE TITLE
go-sql-driver/mysql已经不支持go1.2,1.3,1.4了

### ISSUE THREAD

**Issue by waterloopwm** [go-xorm/xorm#614]
go-sql-driver/mysql最近两次提交已经不支持go1.2,1.3,1.4了
https://github.com/go-sql-driver/mysql/commit/72e0ac3f5f08a49db42c27233733873f95ba9576
https://github.com/go-sql-driver/mysql/commit/a825be04c652d01442384e9dcdf2cdc3f1eda67f

xorm是否考虑也最低支持golang1.5

**Comment by lunny** [comment]
需要做什么呢？

**Comment by waterloopwm** [comment]
Implement Context Interface
Implement Pinger interface
