### ISSUE TITLE
mysql  write: broken pipe错误

### ISSUE THREAD

**Issue by kjfcpua** [go-xorm/xorm#621]
在使用xorm操作mysql时碰到此问题,看网上解决方案是自动重连，或者设置maxIdleTime<mysql的wait_timeout,不过好像xorm里面没有设置maxIdleTime的地方

**Comment by waterloopwm** [comment]
有个SetConnMaxLifetime参数，设置这个参数小于mysql的空闲时间，就没有这个问题了

**Comment by lunny** [comment]
SetConnMaxLifetime 已经支持了。
