### ISSUE TITLE
怎样管理一个全局的ORM实例？

### ISSUE THREAD

**Issue by AbooJan** [go-xorm/xorm#628]
一个web服务器会有很多个控制器，在控制器需要对数据库进行操作，那是不是需要每个控制器里面都 `xorm.NewEngine` 来创建一个新的ORM实例？

还是说使用一个单例，在单例里创建一次 ORM 实例，然后其他地方都通过这个单例来操作数据库？

新手一枚，望指教一二😁

**Comment by lunny** [comment]
一般一个数据库就单例就可以了，在main里面初始化，然后各个go routine可以安全调用。
