### ISSUE TITLE
about xorm Exec 'use ?' 

### ISSUE THREAD

**Issue by itchenyi** [go-xorm/xorm#645]
my model like this:

```
var Db *xorm.Engine
...
```

my handler like this:

```
_, err := Db.Exec("use ?", "SomeDbName")
...
```

err:

```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1
```

can not use '?' in Exec ?

**Comment by lunny** [comment]
Yes, just ```Db.Exec("use SomeDbName")```.  Only values use `?` but not table names, column names.

**Comment by itchenyi** [comment]
@lunny  ok, i'm just confirming, thank you very much.
