### ISSUE TITLE
xorm更新后的bug

### ISSUE THREAD

**Issue by ivessong** [go-xorm/xorm#674]
您好，刚更新最新版本的xorm后，以前的session里面的两个属性statement 以及autoResetStatement 变成了私有变量。

statement是因为在join的时候如果函数里面有GROUP_CONCAT 会报错。
autoResetStatement  每次查询结束后会reset参数，但有时候不需要清楚，比如在分页查找的时候，先count，后find，那么每次count查询前，都要clone一下session，很不方便。

**Comment by lunny** [comment]
https://github.com/go-xorm/xorm/blob/master/session_cond_test.go#L269
参考这个里面的用法。
