### ISSUE TITLE
Log 不能控制台和文件同时输出

### ISSUE THREAD

**Issue by AbooJan** [go-xorm/xorm#677]
Golang: `1.8.2`
xorm: 最新发布版
数据库：`Postgres`

---

代码:
```
	eng.ShowSQL(true)
	eng.Logger().SetLevel(core.LOG_DEBUG)
	f, err := os.Create("./logs/pgSql.log")
	if err != nil {
		logs.Error("output sql log to file failed")
		println(err.Error())
		return
	}
	eng.SetLogger(xorm.NewSimpleLogger(f))
```

文档上说可以同时输出，可是我添加了文件输出之后，控制台就没有输出了，
是我添加的方法不对么？

----

另外一个就是，文件输出，新的会覆盖掉旧的, 能不能做到类似 `beego` 框架里面的log一样，能按日期创建log，一天一个log文件，不会被覆盖。

谢谢😊

**Comment by lunny** [comment]
您这个是只输出到文件啊。你可以用```io.MultiWriter(f, os.Stdout)```

**Comment by AbooJan** [comment]
@lunny 那如果要同时输出到控制台和文件，正确的写法是怎样的呢？

我看 `http://xorm.io/docs` 的文档上的示例基本上就是我问题中的写法
