### ISSUE TITLE
ID condition is error, expect 0 primarykeys, there are 1

### ISSUE THREAD

**Issue by aslackers** [go-xorm/xorm#687]
数据库表是这样的：
CREATE TABLE `roles` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户角色';

model里是这样的：
type Roles struct {
	Id   int
	Name string
}

控制器里是这样的：
var role models.Roles

id, _ := strconv.Atoi(c.Params.Form.Get("id"))
role.Name = c.Params.Form.Get("name")

_, err := engine.Id(id).Update(&role)
会报错：ID condition is error, expect 0 primarykeys, there are 1

但如果改成这样：_, err := engine.Where("id = ?", id).Update(&role) 就没事，这是什么原因？？

**Comment by lunny** [comment]
```Go
type Roles struct {
Id int  `xorm:"pk autoincr"`
Name string
}
```
因为你没有定义Id为主键，所以`ID()`函数不认。
