### ISSUE TITLE
[bug]mysql，字段类型为bit时，0值被转化成了空串

### ISSUE THREAD

**Issue by Leadrive** [go-xorm/xorm#701]
mysql, 字段A 为bit类型。值为0
在QueryString("select A from test")
后，应该返回值为0才对，实际是返回一个""，注意，并不是空字符串，如果用编辑器显示不可见字符，是"<NUL>"，是个不可见字符
问题是出在session_raw.go第228行
if data, err := value2String(&rawValue); err == nil {
这里转换时，做了处理。
如果字段类型为int，好像没问题。字段类型为bit，就有错误。

**Comment by lunny** [comment]
Hi, I think your code is older than master. Which version are you using?

**Comment by Leadrive** [comment]
用的是最新版本。建议你弄个表测试下。
