### ISSUE TITLE
created  字段 在更新的时候也更更新了

### ISSUE THREAD

**Issue by yqbaa** [go-xorm/xorm#726]
CreateAt time.Time  `xorm:"created" json:"create_at"`
UpdateAt time.Time `xorm:"updated" json:"update_at"`

执行的sql 显示是
update xxx set update_at = ?  , ['2017-09-09 09:09:09'] 
但实际上 created_at 也被更新了

版本: ba71ae6665c011ae861a7093e170d995151eb56f

**Comment by lunny** [comment]
请查看 #727，测试代码未能重现你的问题。
