### ISSUE TITLE
xorm运行失败

### ISSUE THREAD

**Issue by chs97** [go-xorm/xorm#731]
![_20170920214934](https://user-images.githubusercontent.com/12679581/30647185-8bd5a31c-9e4d-11e7-9aa3-103239242f91.png)

**Comment by lunny** [comment]
Hi, update github.com/go-xorm/core to latest version

**Comment by chs97** [comment]
@lunny  it has been update to the last version .look the picture

**Comment by lunny** [comment]
你是固定tag了

**Comment by chs97** [comment]
@lunny ☺️☺️好的，为啥上一条要用english啊。

**Comment by wxkj001** [comment]
@chs97 兄弟你是怎么解决的

**Comment by chs97** [comment]
@wxkj001  升级到最新版

**Comment by wxkj001** [comment]
@chs97   github.com/go-xorm/core  这个我怎么升级都是0.5.6

**Comment by chs97** [comment]
@wxkj001  我是因为dep包管理 lock了0.5.6的版本，把他用master覆盖了就好了

**Comment by wxkj001** [comment]
@chs97  我的覆盖也不行
