### ISSUE TITLE
Limit没效果？

### ISSUE THREAD

**Issue by aqtata** [go-xorm/xorm#733]
`err := db.SQL("SELECT xxx FROM a, b WHERE a.id = b.id").Limit(5, 10).Find(out)`
打印出的语句后面没有看到limit。所以我暂时改成下面这样了
`err := db.SQL("SELECT xxx FROM a, b WHERE a.id = b.id LIMIT ?,?", x, y).Find(out)`

**Comment by lunny** [comment]
调用SQL后，其它条件都将失效

**Comment by WhiteBatman** [comment]
xormplus/xorm中支持这种模式

https://www.kancloud.cn/xormplus/xorm/250337

但是如果是mssql的话还需要和OrderBy函数配合一起使用
