### ISSUE TITLE
Insert  Data Error

### ISSUE THREAD

**Issue by chs97** [go-xorm/xorm#734]
![mmexport1506047791981](https://user-images.githubusercontent.com/12679581/30727162-1763f070-9f82-11e7-9137-7de9ef0bf514.jpg)
![mmexport1506047786922](https://user-images.githubusercontent.com/12679581/30727168-1cf355ee-9f82-11e7-86f2-f36bdd17bd78.jpg)

**Comment by lunny** [comment]
DB为nil
