### ISSUE TITLE
复合主键无法添加自增特性

### ISSUE THREAD

**Issue by aqtata** [go-xorm/xorm#747]
go结构定义
`type Log struct {
	Id    int64 `xorm:"pk autoincr"`
	Date  int   `xorm:"pk notnull"`
}`

使用Sync2方法同步数据库结构。

然后插入数据时发现ID都是0，于是用Navicat Premium连接数据库查看表属性发现"自动递增"选项框没有勾上。去掉Date的pk属性后正常。所以推断是xorm创建复合主键时没有加入自增属性的逻辑。。。

xorm版本：0.6.4.0910

**Comment by lunny** [comment]
Which database did you used?

**Comment by aqtata** [comment]
MySQL

**Comment by lunny** [comment]
这个数据库本身不支持
