### ISSUE TITLE
高并发insert数据问题

### ISSUE THREAD

**Issue by FengJunLiu** [go-xorm/xorm#751]
在开启了事物的insert过程中，对一个表的高并发插入数据（多协程同时向一张表insert数据）的时候，会出现insert的affected条数为0或者-1时，但是insert的error返回为nil的情况。
insert返回error为nil，不可以判别数据insert是success的？会有其他的可能吗？
insert代码如下：
func Insert(insertArr ...interface{}) (int64, error) {
	engine, err := GetDbEngine()
	if err != nil {
		return -1, err
	}
	defer CloseDbEngine(engine)
	session := engine.NewSession()
	defer session.Close()
	err = session.Begin()
	if err != nil {
		return -1, err
	}
	affected, err := session.Insert(insertArr...)
	if err != nil {
		session.Rollback()
		return -1, err
	}
	return affected, session.Commit()
}
部分测试结果：
<<<<<<<<< insert no error >>>>>>>> affected: 0
<<<<<<<<< insert no error >>>>>>>> affected: -1
<<<<<<<<< insert no error >>>>>>>> affected: 0
<<<<<<<<< insert no error >>>>>>>> affected: -1
<<<<<<<<< insert no error >>>>>>>> affected: 0
<<<<<<<<< insert no error >>>>>>>> affected: 0
<<<<<<<<< insert no error >>>>>>>> affected: 0

**Comment by lunny** [comment]
Which database did you test ?
Which version of your XORM ?

**Comment by FengJunLiu** [comment]
database is mysql
XROM version is master branch code

**Comment by lunny** [comment]
```Go
engine, err := GetDbEngine()
if err != nil {
return -1, err
}
defer CloseDbEngine(engine)
```
Should only be initialized once.

**Comment by t57root** [comment]
I'm using one `xorm.Engine' instance in multiple goroutines to insert record into one same table. 
The call to Insert() method sometimes return an error says `database is locked'.
The backend database is sqlite3 and the code is like this:

db, err = xorm.NewEngine("sqlite3")
for i:=1; i<10;i++{
  go func() {
    db.Insert()  // this call somethings return `database is lockec' error
  }()
}

Why this error occurred and is this the correct way to do parallel insertion?  
Thanks in advance.

**Comment by lunny** [comment]
@t57root this is an known sqlite3 driver's issue. Please send an issue to that driver repository.

**Comment by t57root** [comment]
@lunny  
thanks for the info.
Is it possible to retry Insert() serval times if this error occurred as a workaround for this issue?
