### ISSUE TITLE
no primary key for col xxx?

### ISSUE THREAD

**Issue by ipiao** [go-xorm/xorm#761]
type Waybill struct {
	ID           int64              `xorm:"id pk autoincr" json:"id" validate:"gt=0"` 
	No           string             `xorm:"no unique" json:"no"`                 
	Status       int32              `xorm:"status" json:"status"`    
	Tag          WaybillTag         `xorm:"tag" json:"tag"`             
	Attr         WaybillAttr        `xorm:"attr" json:"attr"`             
	DeliveryDate int64              `xorm:"delivery_date" json:"delivery_date"`     
	Spots        []WaybillSpot  `xorm:"spots json" json:"spots"`
}

type WaybillSpot struct {
	ID             int64  `xorm:"-" json:"id"`                                  
	Code           string `xorm:"code unique" json:"code"`                       
	Name           string `xorm:"name" json:"name"`                            
	Coord          Coord  `xorm:"coord json" json:"coord"`                       
	TakingDistance int32  `xorm:"taking_distance" json:"taking_distance"`         
	Address        string `xorm:"address" json:"address"`                        
	Priority       int32  `xorm:"priority" json:"priority" validate:"gte=0,lt=99"`
}

在Insert收出现错误 : "no primary key for col tag",请问这是什么问题？

**Comment by lunny** [comment]
```Go
Tag WaybillTag xorm:"tag" json:"tag"
```
You define a struct as a column and no other related tag. You can use `xorm:"extends"` if you want copy all columns from struct `WaybillSpot` to this table.

**Comment by ipiao** [comment]
sorry ,but it is a slice,and i do not mean to extend the struct.i just want to use it as json

**Comment by lunny** [comment]
Than please add `xorm:"json"`

**Comment by ipiao** [comment]
you can see,i have add tag ：
`Spots  [] WaybillSpot xorm:"spots json" json:"spots"`

**Comment by lunny** [comment]
It's `Tag` field with type `WaybillTag` on struct `Waybill`:

```Go
Tag WaybillTag xorm:"tag json" json:"tag"
```

**Comment by ipiao** [comment]
sorry ,my bad
