### ISSUE TITLE
xorm 编译之后运行找不到timezone.zip 

### ISSUE THREAD

**Issue by rookiejin** [go-xorm/xorm#769]
```shell
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\gopath\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

在本机上编译的，然后拷贝到没有go环境上的机器上运行，报错结果：

```Shell
$ ./main.exe
2017/11/03 14:20:20 数据库连接失败: %vopen /usr/local/go\lib\time\zoneinfo.zip: The system cannot find the path specified.
[14:20:20 CST 2017/11/03] [DEBG] (protobuf/model.XormLogger.Infof:36) PING DATABASE [mysql]
```

**Comment by rookiejin** [comment]
`
func init()  {
	var err error
	engine , err = xorm.NewEngine("mysql", setting.DSN)
	if err != nil {
		l4g.Error(err)
	}
	engine.ShowSQL(true)
	log := XormLogger{
		S: true ,
		L:  core.LOG_DEBUG ,
	}
	engine.SetLogger(log)
	engine.SetMaxIdleConns(setting.MYSQL_POOL_MAX_ID_LE_CONN)
	engine.SetMaxOpenConns(setting.MYSQL_POOL_MAX_OPEN_CONN)
	err = engine.Ping()
	if err != nil {
		log1.Fatal("数据库连接失败: %v" , err)
	}
	l4g.Info("数据库连接成功")
}
`

**Comment by lunny** [comment]
This is not a xorm related issue.
