### ISSUE TITLE
Update map[string]interface{} support

### ISSUE THREAD

**Issue by runner-mei** [go-xorm/xorm#771]
session.Table("xxxx").ID(id).Update(map[string]interface{}{
  "id": "xxxx",
})
或者
session.Table(&XXXX{}).ID(id).Update(map[string]interface{}{
  "id": "xxxx",
})

就会
panic(0xb5c320, 0x10a8400)
        d:/tools/go_amd64/src/runtime/panic.go:491 +0x291
github.com/go-xorm/xorm.(*Statement).processIDParam(0xc042330498, 0xc0426def30,0xc0422668d8)
        d:/developing/go/meijing/tpt_vendor/src/github.com/go-xorm/xorm/statement.go:1163 +0x4e
github.com/go-xorm/xorm.(*Session).Update(0xc042330480, 0xb58040, 0xc0426df020,0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        d:/developing/go/meijing/tpt_vendor/src/github.com/go-xorm/xorm/session_update.go:239 +0x1198

**Comment by lunny** [comment]
@runner-mei it's not supported usage `Update(map[string]interface{})` now.

**Comment by runner-mei** [comment]
可不可以加上呢，这也是一个常见的场景啊

**Comment by runner-mei** [comment]
修正一下

session.Table(&XXXX{}).ID(id).Update(map[string]interface{}{
  "field1": "xxxx",
})

不会报错, 但 


session.Table(“tablexxx”).ID(id).Update(map[string]interface{}{
  "field1": "xxxx",
})
会报错

**Comment by lunny** [comment]
本来是一次写操作，如果新增一次读操作，似乎没必要。

**Comment by runner-mei** [comment]
你应该在初始时载入元模型，以后就不加载了， 我记得 bee orm 是这么做的，当然不一定是，我不记得了
