### ISSUE TITLE
查询结果能否自动映射类型?

### ISSUE THREAD

**Issue by zjxpcyc** [go-xorm/xorm#774]
我看源码里面  有个 [QueryInterface](https://github.com/go-xorm/xorm/blob/a620571388c685fde76f4dda04dfd840196262e4/session_query.go#L165) 方法，这个是查询结果用 map[string]interface{} 的方式返回的, 我这边是 mysql 数据库, 用的时候发现, 这个 interface{} 实际上就  []byte 。

那么能否这个 interface{} 是实际上数据库的类型的映射呢，比如 varchar, 就是 string, 而不是 不管数据库中字段类型是 int , 还是 varchar 都是 []byte ?

**Comment by lunny** [comment]
这个是数据库驱动返回的，目前xorm没有做处理

**Comment by happyEgg** [comment]
@lunny 那我怎么获取未知字段的类型呀？有方法吗

**Comment by lunny** [comment]
@happyEgg 只能写函数switch断言

**Comment by happyEgg** [comment]
断言也是[]byte类型呀，我现在用engine.DB().Query(xx).Rows()，这个方法来进行操作断言的，可以完美解决

**Comment by huahuayu** [comment]
> @lunny 断言也是[]byte类型呀，我现在用engine.DB().Query(xx).Rows()，这个方法来进行操作断言的，可以完美解决

你好，我试了一下，没有Rows()这个方法啊，只有到engine.DB().Query(xx)
