### ISSUE TITLE
postgres dialect panics if password contains a space

### ISSUE THREAD

**Issue by daniellee** [go-xorm/xorm#775]
With the following code (the password should be escaped but isn't):

```go
cntStr := "postgres://badpass:test space@localhost:5432/grafana?sslmode=disable"
engine, err := xorm.NewEngine("postgres", cntStr)
```

The [parseOpts](https://github.com/go-xorm/xorm/blob/master/dialect_postgres.go#L1178-L1182) method panics instead of returning an error.

Would you accept a PR that does the following:

Removes the [errorf function](https://github.com/go-xorm/xorm/blob/master/dialect_postgres.go#L1120) that is used in the parseOpts function and that returns an error if the parsing fails.

**Comment by lunny** [comment]
Please feel free to send a PR.

**Comment by daniellee** [comment]
@lunny are the instructions in [CONTRIBUTING.md](https://github.com/go-xorm/xorm/blob/master/CONTRIBUTING.md) up to date? Should tests be placed in https://github.com/go-xorm/tests ? 

Also, noticed that the code for parsing is from an old version of pq and it does more than is needed. For example, it parses out a full uri but only the db name is returned. Is it ok to remove that code (for example [this](https://github.com/go-xorm/xorm/blob/master/dialect_postgres.go#L1142-L1156))?

**Comment by lunny** [comment]
It's out date. All tests now merged into this repository. Please add test with your PR.

**Comment by lunny** [comment]
It's OK to remove unused code.
