### ISSUE TITLE
Select columns order ensuring

### ISSUE THREAD

**Issue by mingrammer** [go-xorm/xorm#782]
Is there a way for ensuring the order of select columns?

```sql
SELECT id, name, gender FROM users LIMIT 100;
```

I hope this query would be resulted in `id, name, gender` order, not `gender, id, name`

**Comment by lunny** [comment]
If you haven't use `Join`, the sequence of columns is the sequence of fields on the struct. If you have `Join`, the select sequence is the sequence on table.

**Comment by mingrammer** [comment]
The above table is not defined as Go struct, but created manually. In this case, can't xorm ensure the select sequence?

**Comment by lunny** [comment]
If not `Join` and you use Struct `Get` or `Find`, xorm will use struct's sequence. If use `Join` will use database columns sequence.

**Comment by mingrammer** [comment]
Oh sorry, ok I got it. So, I should use `Join` for using the DB columns seq. :|

**Comment by lunny** [comment]
Or you can `engine.Select("*")` to to that.

**Comment by mingrammer** [comment]
Wait, so, the same rule is applied to raw query?

**Comment by mingrammer** [comment]
Oh .. this problem was not about xorm. The built-in json package force sort the all keys of a map. Sorry
