### ISSUE TITLE
Question: Possible to extract single value with ease?

### ISSUE THREAD

**Issue by marefr** [go-xorm/xorm#788]
Hi,

I'm having some issues with a query like

```SQL
SELECT max(id) as id FROM some_table WHERE something > 1
```

The only solution that I've found works for getting out the value without having a struct is the following:

```golang
func someFunc() {
	var maxId int64
	sql := "SELECT max(id) as id FROM some_table WHERE something < 1000)
	result, err := sess.Query(sql)

	if err != nil {
		return err
	}
  	maxId = toInt64(result[0]["id"])
}

func toInt64(i interface{}) int64 {
	switch i.(type) {
	case []byte:
		n, _ := strconv.ParseInt(string(i.([]byte)), 10, 64)
		return n
	case int:
		return int64(i.(int))
	case int64:
		return i.(int64)
	}
	return 0
}
```

Using the toInt64 feels like a hack. I've read the documentation and tried to use `Get` and `Find` instead, but couldn't get that to work.

Are there an easy way of getting out a single value? 

Thanks in advance

**Comment by lunny** [comment]
```Go
var maxId int64
_, err := sess.SQL(sql).Get(&maxId)
```

**Comment by lunny** [comment]
See the test https://github.com/go-xorm/xorm/blob/master/session_get_test.go#L37

**Comment by marefr** [comment]
Thanks a lot! That made it obvious how to do it :+1:

**Comment by lunny** [comment]
And there is a know issue see #811. You should change `max(id)` to `max(`id`)`
