### ISSUE TITLE
What is a "cascade struct"

### ISSUE THREAD

**Issue by stevenroose** [go-xorm/xorm#794]
This page: http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-02/1.mapping.html

It mentions a difference between a "struct" and a "cascade struct". What is the latter? I can't find any references in Google.. Is it a pointer?

Also, fwiw, that mapping of Go types to SQL types is really hard to find. Most pages ([like this one](http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-02/4.columns.html)) link to another page on the URL (`https://github.com/go-xorm/xorm/blob/master/docs/COLUMNTYPE.md`) that doesn't exist anymore.

**Comment by lunny** [comment]
@stevenroose `cascade struct` is a struct which has mapping to some table and has association with this struct. 
This links has been fixed.
