### ISSUE TITLE
API接口兼容性

### ISSUE THREAD

**Issue by bensinos** [go-xorm/xorm#801]
建议多考虑下API接口的兼容性，
现在我们项目很多地方使用的是：
// Query a raw sql and return records as []map[string][]byte
func (engine *Engine) Query(sql string, paramStr ...interface{}) (resultsSlice []map[string][]byte, err error) 

但是新版里面成了：

func (engine *Engine) Query(sqlorArgs ...interface{}) (resultsSlice []map[string][]byte, err error) 

这就造成我们大量的代码修改。

**Comment by lunny** [comment]
@bensinos 这样应该是兼容的啊。可以看下你们怎么用的吗？

**Comment by bensinos** [comment]
db.Engine.Query(buf.String(),params...)

大概是这个样子,就是Sql会动态生成，参数也是 @lunny

**Comment by lunny** [comment]
稍微改造下应该就可以了吧？

**Comment by bensinos** [comment]
改造不少，db.Engine.Query(buf.String(),params...)  中params是数组来的.

**Comment by bensinos** [comment]
@lunny

**Comment by lunny** [comment]
```Go
newParams := make([]inerface{}, len(params)+1)
copy(newParams[1:], params)
newParams[0] = buf.String()
db.Engine.Query(newParams...)
```

**Comment by bensinos** [comment]
这样当然可以，还是注意下。
