### ISSUE TITLE
How to get last autoincrement ID on insert with go-xorm?

### ISSUE THREAD

**Issue by toni-moreno** [go-xorm/xorm#803]
I've looking for a way to get the last auto incremented ID on the last insert

````golang
type TestTable struct {
	ID           int64            `xorm:"'id' pk autoincr"`
	Name         string           `xorm:"'name'  not null unique""`
}
````

After googling I've seen the way to do this on certain databses.

* SQLite 
(https://stackoverflow.com/questions/2127138/how-to-retrieve-the-last-autoincremented-id-from-a-sqlite-table) 

````sql
SELECT last_insert_rowid()
````
* Mysql
https://stackoverflow.com/questions/17627126/getting-last-auto-increment-value-in-database
````sql
LAST_INSERT_ID() 
````

* Postgresql
https://stackoverflow.com/questions/2944297/postgresql-function-for-last-inserted-id
````sql
LASTVAL();
````
But there is a common way  to do it  with go-xorm?

**Comment by lunny** [comment]
Yes. XORM have helped you to do this. See the code below.
```Go
var myobj TestTable
engine.Insert(&myobj)
fmt.Println(myobj.ID)
```
