### ISSUE TITLE
Golang Debug 失败

### ISSUE THREAD

**Issue by bensinos** [go-xorm/xorm#806]
GOROOT=E:\software\Go1.9.2 #gosetup
GOPATH=E:\SourceCode\GO_CODE #gosetup
E:\software\Go1.9.2\bin\go.exe build -o C:\Users\Administrator\AppData\Local\Temp\___main_go.exe -gcflags "-N -l" -a E:/SourceCode/GO_CODE/src/gzweb/main.go #gosetup
# github.com/go-xorm/xorm
..\github.com\go-xorm\xorm\engine_group.go:36:10: engine.engineGroup undefined (type *Engine has no field or method engineGroup)
..\github.com\go-xorm\xorm\engine_group.go:48:9: master.engineGroup undefined (type *Engine has no field or method engineGroup)
..\github.com\go-xorm\xorm\engine_group.go:50:13: slaves[i].engineGroup undefined (type *Engine has no field or method engineGroup)
..\github.com\go-xorm\xorm\engine_group.go:120:11: eg.Engine.SetLogLevel undefined (type *Engine has no field or method SetLogLevel)
..\github.com\go-xorm\xorm\engine_group.go:122:15: eg.slaves[i].SetLogLevel undefined (type *Engine has no field or method SetLogLevel)
..\github.com\go-xorm\xorm\interface.go:100:2: cannot use Session literal (type *Session) as type Interface in assignment:
	*Session does not implement Interface (wrong type for Query method)
		have Query(string, ...interface {}) ([]map[string][]byte, error)
		want Query(...interface {}) ([]map[string][]byte, error)
..\github.com\go-xorm\xorm\interface.go:101:2: cannot use Engine literal (type *Engine) as type EngineInterface in assignment:
	*Engine does not implement EngineInterface (missing GetColumnMapper method)
..\github.com\go-xorm\xorm\interface.go:102:2: cannot use EngineGroup literal (type *EngineGroup) as type EngineInterface in assignment:
	*EngineGroup does not implement EngineInterface (missing GetColumnMapper method)

Process finished with exit code 2

**Comment by lunny** [comment]
@bensinos don't know what you mean. Please confirm you have update xorm correctly.
 `go get -u -v github.com/go-xorm/xorm`.

**Comment by bensinos** [comment]
E:\SourceCode\GO_CODE\src\gzweb>gopm list
Dependency list (7):
-> github.com/achiku/xml
-> github.com/astaxie/beego @ tag:v1.9.0
-> github.com/dgrijalva/jwt-go
-> github.com/go-sql-driver/mysql
-> github.com/go-xorm/xorm @ tag:v0.6.4
-> github.com/satori/go.uuid
-> github.com/xuri/excelize

最新版本，在mac下可以。但在windows下不行。

**Comment by lunny** [comment]
应该是一样的啊
