### ISSUE TITLE
update go-xorm to newest ,has many errors

### ISSUE THREAD

**Issue by dolfly** [go-xorm/xorm#813]
Code/gocode/src/github.com/go-xorm/xorm/engine.go:384:30: cannot use index.Type (type int) as type bool in assignment
Code/gocode/src/github.com/go-xorm/xorm/engine.go:879:27: cannot use indexType (type int) as type bool in assignment
Code/gocode/src/github.com/go-xorm/xorm/engine.go:884:27: cannot use indexType (type int) as type bool in assignment
Code/gocode/src/github.com/go-xorm/xorm/engine.go:933:60: cannot use make(map[string]int) (type map[string]int) as type map[string]bool in field value
Code/gocode/src/github.com/go-xorm/xorm/engine.go:958:17: cannot use indexType (type bool) as type int in argument to addIndex
Code/gocode/src/github.com/go-xorm/xorm/mssql_dialect.go:355:15: cannot use make(map[string]int) (type map[string]int) as type map[string]bool in assignment
Code/gocode/src/github.com/go-xorm/xorm/mysql_dialect.go:314:15: cannot use make(map[string]int) (type map[string]int) as type map[string]bool in assignment
Code/gocode/src/github.com/go-xorm/xorm/oracle_dialect.go:695:15: cannot use make(map[string]int) (type map[string]int) as type map[string]bool in assignment
Code/gocode/src/github.com/go-xorm/xorm/postgres_dialect.go:939:15: cannot use make(map[string]int) (type map[string]int) as type map[string]bool in assignment
Code/gocode/src/github.com/go-xorm/xorm/session.go:1605:42: undefined: core.BytesType
Code/gocode/src/github.com/go-xorm/xorm/session.go:1605:42: too many errors

**Comment by lunny** [comment]
Please also update `github.com/xorm/core`
