### ISSUE TITLE
Exists api has problem!

### ISSUE THREAD

**Issue by bensinos** [go-xorm/xorm#814]
I use this:
db.Engine.Where("ORDER_ID = ?", c.OrderId).Cols("ORDER_ID").Exist(c)

but SQL is:
SELECT `order_id` FROM `TB_ORDER_CONTENT` WHERE ORDER_ID = ? AND `ORDER_ID`=? AND `CRM`=? AND `PERSON`=? AND `PHONE`=? AND `REVIEW`=? LIMIT 1 []interface {}{1, 1, "xxx", "xxx", "vvv", "Chinese"}

I think the SQL is : SELECT `order_id` FROM `TB_ORDER_CONTENT` WHERE ORDER_ID = ?

**Comment by lunny** [comment]
c's value fields will be conditions. You can use `.NoAutoConditions().Exist(c)` or you can `.Table("table_name").Exist()`.

**Comment by bensinos** [comment]
tks!
