### ISSUE TITLE
插入多条数据时无法使用TableName()返回的名字

### ISSUE THREAD

**Issue by lwhile** [go-xorm/xorm#815]
version: 3480244cd27f8a3ca33e51e7

```go
func (w *Warn) TableName() string {
	return "name_self"
}
```

使用```InsertOne(warns[0])```可以正确插入到表```name_self```中,
而```Insert(warns)```则会插入到默认的```warn```表,即```TableName()```无效

**Comment by lunny** [comment]
@lwhile didn't reproduce the problem. see #816

**Comment by Skifary** [comment]
`func (w *Warn) TableName() string` does not work, but `func (Warn) TableName() string` can
