### ISSUE TITLE
Duplicate key on migrating

### ISSUE THREAD

**Issue by silverlovesl** [go-xorm/xorm#817]
Sorry for my poor English!
After creating migration sql file and called Migrate function. I got follow error 
_pg: Duplicate key value violates unique constraint "migrations_pkey"_
I have checked source code [migrate.go] path:go-xorm/xorm/migrate/migrate.go

Line:197 function migrationDidRun
`
row := m.db.DB().QueryRow(fmt.Sprintf("SELECT COUNT(*) FROM %s WHERE %s = ?", m.options.TableName,` m.options.IDColumnName, mig.ID))
`
It does raise any errors,but the count is always zero even record has been inserted.

It should be $ mark not question mark if you were using postgresql ,right?
I tried the fixed to it by:
`
row := m.db.DB().QueryRow(fmt.Sprintf("SELECT COUNT(*) FROM %s WHERE %s = '%s'", m.options.TableName, m.options.IDColumnName, mig.ID))
`

**Comment by lunny** [comment]
@silverlovesl please confirm #818 will resolve this issue.

**Comment by museghost** [comment]
@lunny at first, thank you for your patch
However, unfortunately, the patch does not work because of below.

```golang
count, err := m.db.SQL(fmt.Sprintf("SELECT COUNT(*) FROM %s WHERE %s = ?", m.options.TableName, m.options.IDColumnName), mig.ID).Count()
```
In the statement " count, err := brbrbr .....", the variable "err" is not used so that cannot be compiled.

If possible, could you please ignore err variable or handle the err variable ?

**Comment by lunny** [comment]
@museghost I think you are right. Fixed now.
