### ISSUE TITLE
session.Engine change to  session.engine, why?

### ISSUE THREAD

**Issue by mumuniao** [go-xorm/xorm#821]
From v0.6.3, session field 'Engine' change to private 'engine'？

In a function, I only has session, and I want to use some engine function, such as Engine.IdOf, now I can not find a function to settle it. （This function we use in many places, we can pass the engine parameter to the function, but it may modify many codes.）

**Comment by lunny** [comment]
maybe add a function named `Engine()`.

**Comment by mumuniao** [comment]
👍
