### ISSUE TITLE
日期字段默认值是CURRENT_TIMESTAMP的问题

### ISSUE THREAD

**Issue by neverhuy** [go-xorm/xorm#827]
struct定义日期类字段时，如果xorm:'CURRENT_TIMESTAMP'，engine.Sync2()报错：
_Invalid default value for 'created_at'_

去掉单引号则可以同步表结构成功，但是再次同步时，会提示默认值不一样：
_Table medicine Column created_at db default is 'CURRENT_TIMESTAMP', struct default is CURRENT_TIMESTAMP_

是否在session_schema.go做默认值判断时做下区分？

**Comment by lunny** [comment]
`xorm:"default CURRENT_TIMESTAMP"`
