### ISSUE TITLE
Failed to get xorm package

### ISSUE THREAD

**Issue by 361007018** [go-xorm/xorm#839]
![image](https://user-images.githubusercontent.com/13548195/35601510-70da95ac-066e-11e8-88db-3b47144727c5.png)

**Comment by lunny** [comment]
go get -u github.com/go-xorm/core
go get -u github.com/go-xorm/builder
go get -u github.com/go-xorm/xorm

**Comment by 361007018** [comment]
@lunny It work.Thanks
