### ISSUE TITLE
If dont close session what will happen?

### ISSUE THREAD

**Issue by Ericxiushu** [go-xorm/xorm#843]
why I need to close session?

    func Trans(){

      sess := engine.NewSession()

      // defer sess.Close()         withOut close session ,  it seems ok?

      sess.Begin()

       updateUser(sess,"user_name")
       updateAccount(sess,"account_name")

       sess.Commit()
    }

    func updateUser( sess *xorm.Session , name string){
      ....
    }

    func updateAccount(sess *xorm.Session , name string){
      ....
    }

**Comment by lunny** [comment]
`Close` will automatically rollback if you didn't commit. `Close` will release all statement cache. If you don't invoke that. Resource leaks maybe happen.

**Comment by lunny** [comment]
@Ericxiushu currently it is. But I cannot guarantee if it will not be changed in future.

**Comment by Ericxiushu** [comment]
thanks @lunny
