### ISSUE TITLE
Does session's rollback work?

### ISSUE THREAD

**Issue by Catofes** [go-xorm/xorm#850]
In session.Init() function, session.isAutoCommit is set to true.
https://github.com/go-xorm/xorm/blob/2e295feace1835837c90e225d1bbf56e8977ec4d/session.go#L66-L68
And in session.Rollback() function it checks session.isAutoCommit. Seems Rollback will not work at all?
https://github.com/go-xorm/xorm/blob/2e295feace1835837c90e225d1bbf56e8977ec4d/session_tx.go#L23-L25

Test code: 

``` golang
package main

import (
	"github.com/go-xorm/xorm"
	"os"
	"log"
	_ "github.com/lib/pq"
)

func main() {
	url := os.Getenv("POSTGRES")
	e, err := xorm.NewEngine("postgres", url)
	if err != nil {
		log.Fatal(err)
	}
	type User struct {
		Id       int64
		Username string
	}
	e.Sync2(new(User))
	s := e.NewSession()
	defer s.Close()
	user := User{
		Username: "test",
	}
	s.Insert(&user)
	s.Rollback()
	has, err := e.Get(&user)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Expect has==false, but has==%t", has)
}
```

**Comment by lunny** [comment]
You should call `s.Begin()` before call any statement if you want transactions.

**Comment by Catofes** [comment]
Thanks. I apology for my carelessness.
