### ISSUE TITLE
groupby的用法

### ISSUE THREAD

**Issue by CellOcean** [go-xorm/xorm#856]
您好！

我想通过xorm的orm功能，生成以下语句，不知道怎么实现。能否指点一下
select name, sum(quantity) as quantity from cost group by name

type Cost struct {
	ID        int
	Name      string
	Quantity  int
	Store     string
	OccurDate time.Time
}

**Comment by lunny** [comment]
```Go
type Cost struct {
ID int
Name string
Quantity int
Store string
OccurDate time.Time
}
var costs []Cost
err := engine.Select("name, sum(quantity) as quantity").GroupBy("name").Find(&costs)
```
