### ISSUE TITLE
Question: Locking - noob question

### ISSUE THREAD

**Issue by happilymarrieddad** [go-xorm/xorm#861]
Hey guys,

I was wondering if there is a way to lock a particular field in the db so that other requests have to wait until the current request is done. Basically, I have many servers sharing a field in the db for ordering purposes and I want to make sure that the return from the cluster of servers always returns a unique number in order.  This is what I'm doing now but I'm pretty sure it's not doing what I want it to do because the locking is only on each server instead of across the cluster. Thanks!

    // Get next order number and assign
    mutex.Lock()
    customer := Customers.Customer{Id: customer_id}
    err := ORM.FindBy(db, &customer)

    if len(customer.NextOrderNum) < 0 {
        order.Number = customer.NextOrderNum
        if numberToInt, err := strconv.Atoi(customer.NextOrderNum); err != nil {
            log.Println(err)
            http.Error(w, ERRORS.STR_TO_INT.String(), http.StatusInternalServerError)
            return
        } else {
            customer.NextOrderNum = strconv.Itoa(numberToInt + 1)
        }
    }
    ORM.Update(db, customer.Id, &customer)
    mutex.Unlock()

**Comment by happilymarrieddad** [comment]
Here's the full code

```
package orders

import (
	ORM "../../../../system/db"
	. "../../../../system/errors"
	Customers "../../models/customers"
	Orders "../../models/orders"

	"encoding/json"
	"github.com/gorilla/schema"
	"log"
	"net/http"
	"strconv"
	"sync"
)

var mutex = &sync.Mutex{}

func Store(w http.ResponseWriter, r *http.Request) {
	//userId := r.Header.Get("user_id")
	customerId := r.Header.Get("customer_id")

	customer_id, _ := strconv.Atoi(customerId)

	var order Orders.Order

	// Parse form data and POST into user
	decoder := schema.NewDecoder()
	if err := decoder.Decode(&order, r.PostForm); err != nil {
		log.Println(err)
		http.Error(w, ERRORS.UNABLE_TO_FILL_OBJECT_FROM_FORM.String(), http.StatusInternalServerError)
		return
	}

	order.CustomerId = customer_id

	// If passed in number from the post request then ensure that the order doesn't already exist.
	if len(order.Number) > 0 {
		verifyOrder := Orders.Order{Number: order.Number, CustomerId: customer_id}

		// If order exists then update
	} else {
		// Get next order number and assign
		mutex.Lock()
		customer := Customers.Customer{Id: customer_id}
		err := ORM.FindBy(db, &customer)

		if len(customer.NextOrderNum) < 0 {
			order.Number = customer.NextOrderNum
			if numberToInt, err := strconv.Atoi(customer.NextOrderNum); err != nil {
				log.Println(err)
				http.Error(w, ERRORS.STR_TO_INT.String(), http.StatusInternalServerError)
				return
			} else {
				customer.NextOrderNum = strconv.Itoa(numberToInt + 1)
			}
		}

		ORM.Update(db, customer.Id, &customer)
		mutex.Unlock()
	}

	err := ORM.Store(db, &order)

	packet, err := json.Marshal(order)
	if err != nil {
		log.Println(err)
		http.Error(w, UNABLE_TO_PARSE_JSON.String(), http.StatusUnauthorized)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.Write(packet)
}

```

**Comment by happilymarrieddad** [comment]
Authentication and verification is done before this function is hit so I don't have to worry about that.

**Comment by lunny** [comment]
This is a database-level support. You can use autoincrement or uuid to do that if your database support that feature. And also you can lock a row use `ForUpdate()` on update it on the same connection if you are using mysql.

**Comment by happilymarrieddad** [comment]
@lunny Thanks!
