### ISSUE TITLE
vgo build missing go.mod

### ISSUE THREAD

**Issue by xjwy** [go-xorm/xorm#867]
vgo build  失败：
提示：gopkg.in/stretchr/testify.v1/assert v0.0.0-20160925015416-69483b4bd14f: missing go.mod

vgo get -u  失败
提示：panic: unexpected status (https://api.github.com/repos/stretchr/testify/commits?sha=v1&until=2018-03-22T08%3A44%3A41Z&per_page=2): 404 Not Found

是否当前不支持 vgo?

**Comment by lunny** [comment]
resolved by 18b1524
