### ISSUE TITLE
time.Time在mysql读取时是utc时间

### ISSUE THREAD

**Issue by meilihao** [go-xorm/xorm#87]
os:win7 x86_64
mysql:oracle mysql 社区版 5.6
驱动:github.com/go-sql-driver/mysql 最新

描述:
time.Time.Local()后存入mysql的datetime类型,读取时时间变成utc时间.

**Comment by franknova** [comment]
db, err := xorm.NewEngine("mysql", "root:xxxx@(127.0.0.1:3306)/xxx")
if err != nil {
    fmt.Println(err)
    return
}
db.DatabaseTZ = time.UTC
db.TZLocation = time.UTC
