### ISSUE TITLE
`TableName` not called in `Find`

### ISSUE THREAD

**Issue by localvar** [go-xorm/xorm#891]
```go
type ABC struct {
  ID uint64 `xorm:"'ID' pk autoincr"`
}

func (abc *ABC) TableName() {
    return "abc"
}

var arr []ABC
db.Find(&arr)
```

failed with error: Error 1146: Table 'db1.a_b_c' doesn't exist

go version: go1.10.1 linux/amd64
xorm: v0.6.4

**Comment by lunny** [comment]
@localvar please upgrade to lastest version. This issue has been reported in https://github.com/go-xorm/xorm/issues/881 and resolved by https://github.com/go-xorm/xorm/pull/887

**Comment by localvar** [comment]
ok, I will try it.
but seems this fix is only in master but not v0.6.5, and I'd like to use a **stable** version. so, could a new version be release soon?

**Comment by lunny** [comment]
done. v0.6.6

**Comment by localvar** [comment]
thanks, confirm fixed!
