### ISSUE TITLE
Doc about Scaling with Read/Write Split missing?

### ISSUE THREAD

**Issue by sleagon** [go-xorm/xorm#898]
No document about database scaling with R/W split found in github or xorm.io. However, as mentioned [here][1], master-slave model is supported by EngineGroup in xorm. Is there any reason for this, is EngineGroup not stable enough or just lack of time?

[1]: https://www.kancloud.cn/xormplus/xorm/413729

**Comment by lunny** [comment]
resolved by https://github.com/go-xorm/manual-zh-CN/commit/b9ba7bd4c01c17fa3213263ded4653cd86fe588d
