### ISSUE TITLE
怎么用乐观锁

### ISSUE THREAD

**Issue by dalixu** [go-xorm/xorm#928]
代码如下
type UserBean struct {
	ID       int64
	User     string `xorm:"index"`
	Password string
	Version  int `xorm:"version"`
}

func(si *xorm.Session) error {
		bean := &models.UserBean{User: user}
		found, err := si.Get(bean)
		if err != nil {
			return err
		}
		if !found || hash(oldPassword) != bean.Password {
			return fmt.Errorf("帐号或密码错误")
		}
		_, err = si.Update(&models.UserBean{Password: hash(newPassword)}, bean)
		return err
}
这段代码生成了2个sql 语句 第2条有2个version语句 多了一个 `version`=? 变成了version=0 导致查找不到数据 是不是我用的方法有问题

sql日志如下 
[xorm] [info]  2018/05/04 17:39:04.895788 [SQL] SELECT `i_d`, `user`, `password`, `version` FROM `user_bean` WHERE `user`=? LIMIT 1 []interface {}{"test"}
[xorm] [info]  2018/05/04 17:39:06.316497 [SQL] UPDATE `user_bean` SET `password` = ?, `version` = `version` + 1 WHERE `i_d`=? AND `user`=? AND `password`=? AND `version`=? AND `version`=? []interface {}{"66666", 1, "test", "55555", 1, 0}

**Comment by dalixu** [comment]
用sql语句可以成功更新 xorm commit版本是d85bb49
//_, err = si.Update(&models.UserBean{Password: hash(newPassword)}, bean)
		_, err = si.Exec("UPDATE `user_bean` SET `password` = ?, `version` = `version` + 1 WHERE `i_d`=? AND `user`=? AND `password`=? AND `version`=?",
			hash(newPassword), bean.ID, bean.User, bean.Password, bean.Version)

**Comment by lunny** [comment]
```Go
bean.Password = hash(newPassword)
si.ID(bean.ID).Cols("password").Update(bean)
```

**Comment by dalixu** [comment]
bean.Password = hash(newPassword)
si.ID(bean.ID).Cols("password").Update(bean)
用这个的确可以了，我看了下 Update的说明 是把第二个参数condiBean 非空field 当作 where条件的 是不是加了乐观锁后就不能用Update(bean, condiBean)这种形式了?

**Comment by lunny** [comment]
@dalixu 可以用第二个参数，但是第一个参数中必须version字段有内容。

**Comment by dalixu** [comment]
啊 那之前where条件多出来的等于0的version 其实是update第一个参数bean的version值，因为我第一个参数version没设置吗
