### ISSUE TITLE
pk autoincr not working

### ISSUE THREAD

**Issue by mich4s** [go-xorm/xorm#930]
Hello, I found something very strange.

When I use 
`affected, err := globals.Database.Table("cars").Insert(*car)`
With this struct
`type Car struct {
	Id					uint64		`xorm:"'id' pk autoincr" json:"id"`
...`
log.Println of car.Id gives me 0. I dont know what can be wrong here ;/

**Comment by localvar** [comment]
try replace `Insert(*car)` with `Insert(car)`
