### ISSUE TITLE
Engine.Find(),Engine.Get() not working when querying with boolean values

### ISSUE THREAD

**Issue by SolomonAbel** [go-xorm/xorm#942]
Hi I am new to XORM

type Model struct{
ID int64
Checked bool `xorm:"bool 'Checked '"`
IsFine bool `xorm:"bool 'IsFine '"`
}

Engine.InsertOne() - works fine

var M Model
M.Checked = false
M.IsFine = true

Engine.Find(M) & Engine.Get(M) - not working fine
also Engine..Update updating boolean fields not working properly

Kindly help me in this

**Comment by lunny** [comment]
Boolean will be ignored since we cannot differ false and none.

**Comment by SolomonAbel** [comment]
so what is an alternative...

**Comment by lunny** [comment]
You can use `where("a =?", true).Get` to do that.

**Comment by SolomonAbel** [comment]
ya sure I will try that..

**Comment by coolaj86** [comment]
To be more clear, it should look like this?

```go
m := &Model{}
has, err := engine.Where("is_true = ?", true).Find(m)
if nil != err {
  panic(err)
}
if !has {
  fmt.Println("no rows returned")
}
```

**Comment by lunny** [comment]
@coolaj86 yes. And a typo on second one.
```
affected, err := engine.ID(m.ID).Cols("is_true").Update(m)
```
