### ISSUE TITLE
mysql5.7 DATETIAM default '0000-00-00 00:00:00' error

### ISSUE THREAD

**Issue by Safircn** [go-xorm/xorm#945]
现在time.Time 默认值是 '0000-00-00 00:00:00' 
mysql5.7 sql_mode 中有 NO_ZERO_DATE, NO_ZERO_IN_DATE
导致 Sync2 同步表出错
Incorrect datetime value: '0000-00-00 00:00:00' for column 'created' at row 1
临时解决:
https://stackoverflow.com/questions/35565128/mysql-incorrect-datetime-value-0000-00-00-000000

**Comment by lunny** [comment]
I think you should change the default '0000-00-00 00:00:00' yourself. I will close this and please feel free to reopen it.
