### ISSUE TITLE
如何使用xorm复杂查询

### ISSUE THREAD

**Issue by godcong** [go-xorm/xorm#990]
如何使用xorm复杂查询

我有一条mysql执行语句
SELECT * FROM (SELECT * FROM subscribe WHERE user_id = "161ca871-5f42-11e8-9f4a-00163e13acaa") subscribe  RIGHT JOIN token_rank ON `subscribe`.subscribe_id = `token_rank`.id
WHERE (`token_rank`.`deleted_at` IS NULL OR `token_rank`.`deleted_at`="0001-01-01 00:00:00")

如果不使用SQL，QUERY这些直接执行的方法如何把
SELECT * FROM subscribe WHERE user_id = "161ca871-5f42-11e8-9f4a-00163e13acaa") subscribe
放入Table的Name

我试过用Table，执行过程中会自动添加"`"符号
或者能否添加手动关闭自动添加“`”符号的函数？

**Comment by lunny** [comment]
Please use builder package `github.com/go-xorm/builder`

**Comment by godcong** [comment]
i will try it
