### ISSUE TITLE
当参数为空时，能否自动忽略查询语句中对应的feild?

### ISSUE THREAD

**Issue by dreadbird** [go-xorm/xorm#992]
比如
```
Engine.Where("name=? ", name).Add("age=?",age).OrderBy("update_time desc").Find(&user)
```
当入参age为空时，就只根据name进行过滤。
select * from user where name=? order by update_time

若age不为空，就会根据age进行过滤
select * from user where name=? and age=? order by update_time

**Comment by lunny** [comment]
age是*int?

**Comment by dreadbird** [comment]
@lunny 谢谢你的回复
这只是个例子，age是int或string都可以的
我的问题是如果传进来的参数是空，是否可以就不要根据这个字段进行过滤

比如：这个语句的含义是查询名字为“张三”且年龄为“10”的所有用户，如果没有传年龄，是否可以直接就查询名称为“张三”的所有用户，而不是查询出：名字为“张三”且年龄为“”的所有用户

**Comment by lunny** [comment]
如果你要自动过滤，你用结构体，用Where的话，即使为0和nil都会成为条件，否则没有任何方法可以设置为0或为nil的条件。

**Comment by dreadbird** [comment]
@lunny 你说的很对，不可兼得
请问使用结构体如何操作？谢谢~

**Comment by lunny** [comment]
```Go
Engine.Where("name=? ", name).OrderBy("update_time desc").Find(&user,&User{
Age:age,
})
```

**Comment by dreadbird** [comment]
@lunny 非常感谢！代码不用再写各种if判空逻辑了
